ALTER TABLE VALORES 
ADD (OBSOLETO NUMBER(1) DEFAULT 0 NOT NULL);

COMMENT ON COLUMN VALORES.OBSOLETO IS '1:Obsoleto,0:Activo';

ALTER TABLE INDICADORES 
ADD (OBSOLETO NUMBER(1) DEFAULT 0 NOT NULL);

COMMENT ON COLUMN INDICADORES.OBSOLETO IS '1:Obsoleto,0:Activo';

ALTER TABLE VALORES_OTRAS_AREAS 
DROP CONSTRAINT VALORES_AREAS_OTROS_FK2;

ALTER TABLE VALORES_OTRAS_AREAS
ADD CONSTRAINT VALORES_AREAS_OTROS_FK2 FOREIGN KEY
(
  ID_VALOR 
)
REFERENCES VALORES
(
  ID 
)
ON DELETE CASCADE ENABLE;