CREATE TABLE COMITES 
(
  ID NUMBER NOT NULL 
, NOMBRE VARCHAR2(50) NOT NULL 
, OBSOLETO NUMBER(1) NOT NULL 
, CONSTRAINT COMITES_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

COMMENT ON COLUMN COMITES.ID IS 'Id autonumerico';

COMMENT ON COLUMN COMITES.NOMBRE IS 'Nombre del comite';

COMMENT ON COLUMN COMITES.OBSOLETO IS '0: Activo, 1: Obsoleto';

COMMENT ON TABLE COMITES IS 'Se definen para poder agrupar indicadores para los informes de Cognos';


CREATE SEQUENCE  "KPI"."SEQ_COMITES"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;

create or replace TRIGGER "KPI"."TR_COMITES" BEFORE
  INSERT ON COMITES REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW BEGIN
  SELECT SEQ_COMITES.NEXTVAL INTO :NEW.id FROM dual;
END ;


CREATE TABLE COMITES_INDICADORES 
(
  ID_COMITE NUMBER NOT NULL 
, ID_INDICADOR NUMBER NOT NULL 
, CONSTRAINT COMITES_INDICADORES_PK PRIMARY KEY 
  (
    ID_COMITE 
  , ID_INDICADOR 
  )
  ENABLE 
);

ALTER TABLE COMITES_INDICADORES
ADD CONSTRAINT COMITES_INDICADORES_FK1 FOREIGN KEY
(
  ID_COMITE 
)
REFERENCES COMITES
(
  ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE COMITES_INDICADORES
ADD CONSTRAINT COMITES_INDICADORES_FK2 FOREIGN KEY
(
  ID_INDICADOR 
)
REFERENCES INDICADORES
(
  ID 
)
ON DELETE CASCADE ENABLE;

COMMENT ON TABLE COMITES_INDICADORES IS 'Se asignan los indicadores a cada comite';

COMMENT ON COLUMN COMITES_INDICADORES.ID_COMITE IS 'Id del comite';

COMMENT ON COLUMN COMITES_INDICADORES.ID_INDICADOR IS 'Id del indicador';
