ALTER TABLE INDICADORES 
ADD (ID_AREA_RESPONSABLE NUMBER );

ALTER TABLE INDICADORES
ADD CONSTRAINT INDICADORES_FK3 FOREIGN KEY
(
  ID_AREA_RESPONSABLE 
)
REFERENCES AREAS
(
  ID 
)
ENABLE;

COMMENT ON COLUMN INDICADORES.ID_AREA_RESPONSABLE IS 'Id del area responsable';

//Le ponemos el mismo valor que el idArea por defecto
update indicadores set id_area_responsable=id_area where 1=1

ALTER TABLE INDICADORES  
MODIFY (ID_AREA_RESPONSABLE NOT NULL);
