'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace plmcadutilsservice
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="BzServicesPLMCADUtilsSoapBinding", [Namespace]:="http://bzServices")>  _
    Partial Public Class PLMCADUtilsService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private CADCheckoutFileOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CADCheckinFileOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CADCheckoutRequestOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.DerivedOutputs.My.MySettings.Default.DerivedOutputs_plmcadutilsservice_PLMCADUtilsService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event CADCheckoutFileCompleted As CADCheckoutFileCompletedEventHandler
        
        '''<remarks/>
        Public Event CADCheckinFileCompleted As CADCheckinFileCompletedEventHandler
        
        '''<remarks/>
        Public Event CADCheckoutRequestCompleted As CADCheckoutRequestCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://bzServices", ResponseNamespace:="http://bzServices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CADCheckoutFile(ByVal in0 As String, ByVal in1 As String, ByVal in2 As String, ByVal in3 As String) As <System.Xml.Serialization.XmlElementAttribute("CADCheckoutFileReturn")> String
            Dim results() As Object = Me.Invoke("CADCheckoutFile", New Object() {in0, in1, in2, in3})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CADCheckoutFileAsync(ByVal in0 As String, ByVal in1 As String, ByVal in2 As String, ByVal in3 As String)
            Me.CADCheckoutFileAsync(in0, in1, in2, in3, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CADCheckoutFileAsync(ByVal in0 As String, ByVal in1 As String, ByVal in2 As String, ByVal in3 As String, ByVal userState As Object)
            If (Me.CADCheckoutFileOperationCompleted Is Nothing) Then
                Me.CADCheckoutFileOperationCompleted = AddressOf Me.OnCADCheckoutFileOperationCompleted
            End If
            Me.InvokeAsync("CADCheckoutFile", New Object() {in0, in1, in2, in3}, Me.CADCheckoutFileOperationCompleted, userState)
        End Sub
        
        Private Sub OnCADCheckoutFileOperationCompleted(ByVal arg As Object)
            If (Not (Me.CADCheckoutFileCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CADCheckoutFileCompleted(Me, New CADCheckoutFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://bzServices", ResponseNamespace:="http://bzServices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CADCheckinFile(ByVal in0 As String, ByVal in1 As String, ByVal in2 As String, ByVal in3 As String) As <System.Xml.Serialization.XmlElementAttribute("CADCheckinFileReturn")> String
            Dim results() As Object = Me.Invoke("CADCheckinFile", New Object() {in0, in1, in2, in3})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CADCheckinFileAsync(ByVal in0 As String, ByVal in1 As String, ByVal in2 As String, ByVal in3 As String)
            Me.CADCheckinFileAsync(in0, in1, in2, in3, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CADCheckinFileAsync(ByVal in0 As String, ByVal in1 As String, ByVal in2 As String, ByVal in3 As String, ByVal userState As Object)
            If (Me.CADCheckinFileOperationCompleted Is Nothing) Then
                Me.CADCheckinFileOperationCompleted = AddressOf Me.OnCADCheckinFileOperationCompleted
            End If
            Me.InvokeAsync("CADCheckinFile", New Object() {in0, in1, in2, in3}, Me.CADCheckinFileOperationCompleted, userState)
        End Sub
        
        Private Sub OnCADCheckinFileOperationCompleted(ByVal arg As Object)
            If (Not (Me.CADCheckinFileCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CADCheckinFileCompleted(Me, New CADCheckinFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://bzServices", ResponseNamespace:="http://bzServices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CADCheckoutRequest(ByVal in0 As String, ByVal in1 As String, ByVal in2 As String, ByVal in3 As String) As <System.Xml.Serialization.XmlElementAttribute("CADCheckoutRequestReturn")> String
            Dim results() As Object = Me.Invoke("CADCheckoutRequest", New Object() {in0, in1, in2, in3})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CADCheckoutRequestAsync(ByVal in0 As String, ByVal in1 As String, ByVal in2 As String, ByVal in3 As String)
            Me.CADCheckoutRequestAsync(in0, in1, in2, in3, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CADCheckoutRequestAsync(ByVal in0 As String, ByVal in1 As String, ByVal in2 As String, ByVal in3 As String, ByVal userState As Object)
            If (Me.CADCheckoutRequestOperationCompleted Is Nothing) Then
                Me.CADCheckoutRequestOperationCompleted = AddressOf Me.OnCADCheckoutRequestOperationCompleted
            End If
            Me.InvokeAsync("CADCheckoutRequest", New Object() {in0, in1, in2, in3}, Me.CADCheckoutRequestOperationCompleted, userState)
        End Sub
        
        Private Sub OnCADCheckoutRequestOperationCompleted(ByVal arg As Object)
            If (Not (Me.CADCheckoutRequestCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CADCheckoutRequestCompleted(Me, New CADCheckoutRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub CADCheckoutFileCompletedEventHandler(ByVal sender As Object, ByVal e As CADCheckoutFileCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CADCheckoutFileCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub CADCheckinFileCompletedEventHandler(ByVal sender As Object, ByVal e As CADCheckinFileCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CADCheckinFileCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub CADCheckoutRequestCompletedEventHandler(ByVal sender As Object, ByVal e As CADCheckoutRequestCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CADCheckoutRequestCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
