'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace zubizanba
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="PrgJobserverWSSoapBinding", [Namespace]:="http://DefaultNamespace")>  _
    Partial Public Class prgJobserverWSService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private descargarEstructuraOperationCompleted As System.Threading.SendOrPostCallback
        
        Private descargarEstructura1OperationCompleted As System.Threading.SendOrPostCallback
        
        Private upload3dXMlOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Troqueleria.My.MySettings.Default.Troqueleria_zubizanba_prgJobserverWSService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event descargarEstructuraCompleted As descargarEstructuraCompletedEventHandler
        
        '''<remarks/>
        Public Event descargarEstructura1Completed As descargarEstructura1CompletedEventHandler
        
        '''<remarks/>
        Public Event upload3dXMlCompleted As upload3dXMlCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://DefaultNamespace", ResponseNamespace:="http://DefaultNamespace")>  _
        Public Overloads Function descargarEstructura(ByVal in0 As String, ByVal in1 As String) As <System.Xml.Serialization.SoapElementAttribute("descargarEstructuraReturn")> String
            Dim results() As Object = Me.Invoke("descargarEstructura", New Object() {in0, in1})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub descargarEstructuraAsync(ByVal in0 As String, ByVal in1 As String)
            Me.descargarEstructuraAsync(in0, in1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub descargarEstructuraAsync(ByVal in0 As String, ByVal in1 As String, ByVal userState As Object)
            If (Me.descargarEstructuraOperationCompleted Is Nothing) Then
                Me.descargarEstructuraOperationCompleted = AddressOf Me.OndescargarEstructuraOperationCompleted
            End If
            Me.InvokeAsync("descargarEstructura", New Object() {in0, in1}, Me.descargarEstructuraOperationCompleted, userState)
        End Sub
        
        Private Sub OndescargarEstructuraOperationCompleted(ByVal arg As Object)
            If (Not (Me.descargarEstructuraCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent descargarEstructuraCompleted(Me, New descargarEstructuraCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.WebMethodAttribute(MessageName:="descargarEstructura1"),  _
         System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://DefaultNamespace", ResponseNamespace:="http://DefaultNamespace")>  _
        Public Overloads Function descargarEstructura(ByVal in0 As String, ByVal in1 As String, ByVal in2 As String, ByVal in3 As String) As <System.Xml.Serialization.SoapElementAttribute("descargarEstructuraReturn")> String
            Dim results() As Object = Me.Invoke("descargarEstructura1", New Object() {in0, in1, in2, in3})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub descargarEstructura1Async(ByVal in0 As String, ByVal in1 As String, ByVal in2 As String, ByVal in3 As String)
            Me.descargarEstructura1Async(in0, in1, in2, in3, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub descargarEstructura1Async(ByVal in0 As String, ByVal in1 As String, ByVal in2 As String, ByVal in3 As String, ByVal userState As Object)
            If (Me.descargarEstructura1OperationCompleted Is Nothing) Then
                Me.descargarEstructura1OperationCompleted = AddressOf Me.OndescargarEstructura1OperationCompleted
            End If
            Me.InvokeAsync("descargarEstructura1", New Object() {in0, in1, in2, in3}, Me.descargarEstructura1OperationCompleted, userState)
        End Sub
        
        Private Sub OndescargarEstructura1OperationCompleted(ByVal arg As Object)
            If (Not (Me.descargarEstructura1CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent descargarEstructura1Completed(Me, New descargarEstructura1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://DefaultNamespace", ResponseNamespace:="http://DefaultNamespace")>  _
        Public Function upload3dXMl(ByVal in0 As String, ByVal in1 As String, ByVal in2 As String) As <System.Xml.Serialization.SoapElementAttribute("upload3dXMlReturn")> Boolean
            Dim results() As Object = Me.Invoke("upload3dXMl", New Object() {in0, in1, in2})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub upload3dXMlAsync(ByVal in0 As String, ByVal in1 As String, ByVal in2 As String)
            Me.upload3dXMlAsync(in0, in1, in2, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub upload3dXMlAsync(ByVal in0 As String, ByVal in1 As String, ByVal in2 As String, ByVal userState As Object)
            If (Me.upload3dXMlOperationCompleted Is Nothing) Then
                Me.upload3dXMlOperationCompleted = AddressOf Me.Onupload3dXMlOperationCompleted
            End If
            Me.InvokeAsync("upload3dXMl", New Object() {in0, in1, in2}, Me.upload3dXMlOperationCompleted, userState)
        End Sub
        
        Private Sub Onupload3dXMlOperationCompleted(ByVal arg As Object)
            If (Not (Me.upload3dXMlCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent upload3dXMlCompleted(Me, New upload3dXMlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub descargarEstructuraCompletedEventHandler(ByVal sender As Object, ByVal e As descargarEstructuraCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class descargarEstructuraCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub descargarEstructura1CompletedEventHandler(ByVal sender As Object, ByVal e As descargarEstructura1CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class descargarEstructura1CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub upload3dXMlCompletedEventHandler(ByVal sender As Object, ByVal e As upload3dXMlCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class upload3dXMlCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
End Namespace
