ALTER TABLE TMP_MOVIMIENTOS_VISA 
ADD (ID_HGLIBRE NUMBER );
COMMENT ON COLUMN TMP_MOVIMIENTOS_VISA.ID_HGLIBRE IS 'Id de la hoja de gastos sin viaje con la que se asocia';

ALTER TABLE MOVIMIENTOS_VISA 
ADD (ID_HGLIBRE NUMBER );
COMMENT ON COLUMN MOVIMIENTOS_VISA.ID_HGLIBRE IS 'Id de la hoja de gastos sin viaje con la que se asocia';

CREATE TABLE AVISO_REIMPRIMIR_HG 
(
  ID_VIAJE NUMBER NOT NULL 
, ID_USUARIO NUMBER NOT NULL 
, CONSTRAINT AVISO_REIMPRIMIR_HG_PK PRIMARY KEY 
  (
    ID_VIAJE 
  , ID_USUARIO 
  )
  ENABLE 
);

ALTER TABLE AVISO_REIMPRIMIR_HG
ADD CONSTRAINT AVISO_REIMPRIMIR_HG_FK1 FOREIGN KEY
(
  ID_VIAJE 
)
REFERENCES VIAJES
(
  ID 
)
ENABLE;

ALTER TABLE AVISO_REIMPRIMIR_HG
ADD CONSTRAINT AVISO_REIMPRIMIR_HG_FK2 FOREIGN KEY
(
  ID_USUARIO 
)
REFERENCES SAB.USUARIOS
(
  ID 
)
ENABLE;

COMMENT ON TABLE AVISO_REIMPRIMIR_HG IS 'Tabla para guardar los avisos para cuando se tenga que reimprimir una hoja de gasto de un viaje por unos gastos de visas, que hayan llegado una vez enviada la hoja de gastos';
COMMENT ON COLUMN AVISO_REIMPRIMIR_HG.ID_VIAJE IS 'Id del viaje';
COMMENT ON COLUMN AVISO_REIMPRIMIR_HG.ID_USUARIO IS 'Id del usuario';
