CREATE TABLE PRESUPUESTOS_AGENCIA_ESTADOS 
(
  ID_VIAJE NUMBER NOT NULL 
, ID_USER NUMBER NOT NULL 
, FECHA DATE NOT NULL 
, ESTADO NUMBER NOT NULL 
, CONSTRAINT PRESUPUESTOS_AGENCIA_ESTAD_PK PRIMARY KEY 
  (
    ID_VIAJE 
  , FECHA 
  )
  ENABLE 
);

ALTER TABLE PRESUPUESTOS_AGENCIA_ESTADOS
ADD CONSTRAINT PRESUPUESTOS_AGENCIA_ESTA_FK1 FOREIGN KEY
(
  ID_VIAJE 
)
REFERENCES VIAJES
(
  ID 
)
ENABLE;

ALTER TABLE PRESUPUESTOS_AGENCIA_ESTADOS
ADD CONSTRAINT PRESUPUESTOS_AGENCIA_ESTA_FK2 FOREIGN KEY
(
  ID_USER 
)
REFERENCES SAB.USUARIOS
(
  ID 
)
ENABLE;

COMMENT ON TABLE PRESUPUESTOS_AGENCIA_ESTADOS IS 'Estados por los que pasa un presupuesto';

COMMENT ON COLUMN PRESUPUESTOS_AGENCIA_ESTADOS.ID_VIAJE IS 'Viaje al que pertenece';

COMMENT ON COLUMN PRESUPUESTOS_AGENCIA_ESTADOS.ID_USER IS 'Id del usuario que da la respuesta';

COMMENT ON COLUMN PRESUPUESTOS_AGENCIA_ESTADOS.FECHA IS 'Fecha del movimiento con hora para que pueda ser clave';

COMMENT ON COLUMN PRESUPUESTOS_AGENCIA_ESTADOS.ESTADO IS 'Estado del movimiento.0: Creado,1:Enviado,2:Aceptado,3:Denegado';
