ALTER TABLE TMP_MOVIMIENTOS_VISA 
ADD (ID_MONEDA_GASTO NUMBER NOT NULL);

COMMENT ON COLUMN TMP_MOVIMIENTOS_VISA.ID_MONEDA_GASTO IS 'Id de la moneda del gasto';

ALTER TABLE MOVIMIENTOS_VISA 
ADD (ID_MONEDA_GASTO NUMBER DEFAULT 90 NOT NULL);

COMMENT ON COLUMN MOVIMIENTOS_VISA.MONEDA IS 'Moneda en la que nos facturan. Es siempre en EUR';

COMMENT ON COLUMN MOVIMIENTOS_VISA.ID_MONEDA IS 'Id de la moneda en la que nos facturan. Siempre en EUR';

COMMENT ON COLUMN MOVIMIENTOS_VISA.ID_MONEDA_GASTO IS 'Id de la moneda origen del pago. Es meramente informativa ya que siempre nos cobran en EUR';
----------------------
ALTER TABLE TMP_MOVIMIENTOS_VISA 
ADD (IMPORTE_MONEDA_GASTO NUMBER NOT NULL);

COMMENT ON COLUMN TMP_MOVIMIENTOS_VISA.IMPORTE_MONEDA_GASTO IS 'Importe en la moneda del gasto';

ALTER TABLE MOVIMIENTOS_VISA 
ADD (IMPORTE_MONEDA_GASTO NUMBER );

COMMENT ON COLUMN MOVIMIENTOS_VISA.IMPORTE_MONEDA_GASTO IS 'Importe en la moneda del gasto';


UPDATE MOVIMIENTOS_VISA SET IMPORTE_MONEDA_GASTO=IMPORTE WHERE 1=1

