ALTER TABLE CUENTAS_CONTRAPARTIDA 
ADD (CUOTA NUMBER );

ALTER TABLE CUENTAS_CONTRAPARTIDA RENAME COLUMN CUENTA TO CONTRAPARTIDA;

COMMENT ON COLUMN CUENTAS_CONTRAPARTIDA.CONTRAPARTIDA IS 'Cuenta de contrapartida';

COMMENT ON COLUMN CUENTAS_CONTRAPARTIDA.CUOTA IS 'Cuenta para las cuotas de las tarjetas';

CREATE TABLE PLANTAS_BIDAIAK 
(
  ID_PLANTA NUMBER NOT NULL 
, CONSTRAINT PLANTAS_BIDAIAK_PK PRIMARY KEY 
  (
    ID_PLANTA 
  )
  ENABLE 
);

ALTER TABLE PLANTAS_BIDAIAK
ADD CONSTRAINT PLANTAS_BIDAIAK_FK1 FOREIGN KEY
(
  ID_PLANTA 
)
REFERENCES SAB.PLANTAS
(
  ID 
)
ENABLE;

COMMENT ON TABLE PLANTAS_BIDAIAK IS 'Se muestran las plantas que funcionan en Bidaiak';

COMMENT ON COLUMN PLANTAS_BIDAIAK.ID_PLANTA IS 'Id de la planta';

INSERT INTO PLANTAS_BIDAIAK VALUES(1)

ALTER TABLE ASIENTOS_CONT_VISAS  
MODIFY (COD_DEPART NULL);

ALTER TABLE TMP_ASIENTO_CONT_VISAS 
ADD (IS_CUOTA NUMBER(1) NOT NULL);

COMMENT ON COLUMN TMP_ASIENTO_CONT_VISAS.IS_CUOTA IS 'Indicara si es de cuota o no';

ALTER TABLE ASIENTOS_CONT_VISAS 
ADD (IS_CUOTA NUMBER(1) DEFAULT 0 NOT NULL);

COMMENT ON COLUMN ASIENTOS_CONT_VISAS.IS_CUOTA IS '1:Es de cuota,0:no es de cuota';

ALTER TABLE TMP_ASIENTO_CONT_VISAS RENAME COLUMN IS_CUOTA TO TIPO;

COMMENT ON COLUMN TMP_ASIENTO_CONT_VISAS.TIPO IS '0:Movimiento,1:Cuota';

ALTER TABLE ASIENTOS_CONT_VISAS RENAME COLUMN IS_CUOTA TO TIPO;

COMMENT ON COLUMN ASIENTOS_CONT_VISAS.TIPO IS '0:Movimiento,1:Cuota';

ALTER TABLE TMP_MOVIMIENTOS_VISA 
ADD (TIPO NUMBER(1) NOT NULL);

COMMENT ON COLUMN TMP_MOVIMIENTOS_VISA.TIPO IS '0:Movimiento usuario,1:Cuotas';

ALTER TABLE MOVIMIENTOS_VISA 
ADD (TIPO NUMBER(1) DEFAULT 0 NOT NULL);

COMMENT ON COLUMN MOVIMIENTOS_VISA.TIPO IS 'Tipo de movimiento. 0:Gasto,1:Cuota';
