CREATE TABLE TARIFAS_GEN_CAB 
(
  ID NUMBER NOT NULL 
, ID_SERVICIO NUMBER NOT NULL 
, NIVEL NUMBER(1, 0) NOT NULL 
, ID_PLANTA NUMBER NOT NULL 
, OBSOLETA NUMBER(1, 0) NOT NULL 
, CONSTRAINT TARIFAS_GEN_CAB_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX TARIFAS_GEN_CAB_PK ON TARIFAS_GEN_CAB (ID ASC) 
      LOGGING 
      TABLESPACE BIDAIAK 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE BIDAIAK 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS;

ALTER TABLE TARIFAS_GEN_CAB
ADD CONSTRAINT TARIFAS_GEN_CAB_FK1 FOREIGN KEY
(
  ID_PLANTA 
)
REFERENCES SAB.PLANTAS
(
  ID 
)
ENABLE;

ALTER TABLE TARIFAS_GEN_CAB
ADD CONSTRAINT TARIFAS_GEN_CAB_FK2 FOREIGN KEY
(
  ID_SERVICIO 
)
REFERENCES SERV_AGENCIA
(
  ID 
)
ENABLE;

COMMENT ON TABLE TARIFAS_GEN_CAB IS 'Cabecera de las tarifas objetivo genericas';

COMMENT ON COLUMN TARIFAS_GEN_CAB.ID IS 'Id autonumerico';

COMMENT ON COLUMN TARIFAS_GEN_CAB.ID_SERVICIO IS 'Id del servicio';

COMMENT ON COLUMN TARIFAS_GEN_CAB.NIVEL IS '1:Nacional,2:Internacional,3:Resto del mundo';

COMMENT ON COLUMN TARIFAS_GEN_CAB.ID_PLANTA IS 'Id de la planta';

COMMENT ON COLUMN TARIFAS_GEN_CAB.OBSOLETA IS 'Indica si la tarifa esta obsoleta(1) o no';

CREATE TABLE TARIFAS_GEN_LIN 
(
  ID_TARIFA NUMBER NOT NULL 
, ANNO NUMBER NOT NULL 
, TARIFA NUMBER NOT NULL 
, CONSTRAINT TARIFAS_GEN_LIN_PK PRIMARY KEY 
  (
    ID_TARIFA 
  , ANNO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX TARIFAS_GEN_LIN_PK ON TARIFAS_GEN_LIN (ID_TARIFA ASC, ANNO ASC) 
      LOGGING 
      TABLESPACE BIDAIAK 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE BIDAIAK 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS;

ALTER TABLE TARIFAS_GEN_LIN
ADD CONSTRAINT TARIFAS_GEN_LIN_FK1 FOREIGN KEY
(
  ID_TARIFA 
)
REFERENCES TARIFAS_GEN_CAB
(
  ID 
)
ENABLE;

COMMENT ON TABLE TARIFAS_GEN_LIN IS 'Se guardan las distintas tarifas objetivos genericas para cada año';

COMMENT ON COLUMN TARIFAS_GEN_LIN.ID_TARIFA IS 'Id de la tarifa cabecera';

COMMENT ON COLUMN TARIFAS_GEN_LIN.ANNO IS 'Año al que corresponden las tarifas';

COMMENT ON COLUMN TARIFAS_GEN_LIN.TARIFA IS 'Tarifa objetivo';

 CREATE SEQUENCE  "BIDAIAK"."SEQ_TARIFAS_GEN"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
 
 create or replace TRIGGER "BIDAIAK"."TR_TARIFAS_GEN" BEFORE
  INSERT ON TARIFAS_GEN_CAB REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW BEGIN
  SELECT SEQ_TARIFAS_GEN.NEXTVAL INTO :NEW.id FROM DUAL;
END TR_TARIFAS_GEN;

CREATE UNIQUE INDEX TARIFAS_GEN_CAB_INDEX1 ON TARIFAS_GEN_CAB (ID_SERVICIO ASC, NIVEL ASC, ID_PLANTA ASC);

ALTER TABLE TARIFAS_GEN_LIN 
DROP CONSTRAINT TARIFAS_GEN_LIN_FK1;

ALTER TABLE TARIFAS_GEN_LIN
ADD CONSTRAINT TARIFAS_GEN_LIN_FK1 FOREIGN KEY
(
  ID_TARIFA 
)
REFERENCES TARIFAS_GEN_CAB
(
  ID 
)
ON DELETE CASCADE ENABLE;