ALTER TABLE PRESUPUESTOS_AGENCIA 
DROP CONSTRAINT PRESUPUESTOS_AGENCIA_TARI_FK1;

ALTER TABLE PRESUPUESTOS_AGENCIA 
DROP COLUMN ID_TARIFA_VUELOS;

ALTER TABLE PRESUPUESTOS_AGENCIA 
ADD (PRESUP_NUEVO NUMBER(1) DEFAULT 0 NOT NULL);

COMMENT ON COLUMN PRESUPUESTOS_AGENCIA.FECHA_LIMITE IS 'Fecha limite de validez del presupuesto. CON LOS PRESPUESTOS NUEVOS, NO SE VA A USAR';

COMMENT ON COLUMN PRESUPUESTOS_AGENCIA.PRESUP_NUEVO IS '0: Para los presupuestos antiguos anteriores a Abril 2019 y 1 para los nuevos';

ALTER TABLE PRESUPUESTOS_SERVICIOS 
ADD (NUM_DIAS NUMBER );

ALTER TABLE PRESUPUESTOS_SERVICIOS 
ADD (ID_SERVICIO NUMBER );

ALTER TABLE PRESUPUESTOS_SERVICIOS 
ADD (TARIFA_OBJ NUMBER );

COMMENT ON COLUMN PRESUPUESTOS_SERVICIOS.TIPO IS 'Indica de que tipo es el servicio=>0:Avion,1:Hotel,2:Tren,3:Coche alquiler. PREPUESTOS ANTIGUOS';

COMMENT ON COLUMN PRESUPUESTOS_SERVICIOS.CIUDAD_1 IS 'Ciudad numero 1. En algunos casos sera la ciudad de origen, en otros como en el hotel, sera simplemente la ciudad.PREPUESTOS ANTIGUOS';

COMMENT ON COLUMN PRESUPUESTOS_SERVICIOS.CIUDAD_2 IS 'La segunda ciudad en caso de ser necesario. Sera la ciudad destino por ejemplo.PREPUESTOS ANTIGUOS';

COMMENT ON COLUMN PRESUPUESTOS_SERVICIOS.FECHA_2 IS 'Segunda fecha y hora en caso de ser necesario. Por ejemplo, fecha hasta.PREPUESTOS ANTIGUOS';

COMMENT ON COLUMN PRESUPUESTOS_SERVICIOS.TIPO_HABIT IS 'Tipo de habitacion. Se usa en hoteles. 0:DUI,1:Doble,2:Individual.PREPUESTOS ANTIGUOS';

COMMENT ON COLUMN PRESUPUESTOS_SERVICIOS.REGIMEN IS 'Regimen utilizado para los hoteles. 0:A+D,1:SA.PREPUESTOS ANTIGUOS';

COMMENT ON COLUMN PRESUPUESTOS_SERVICIOS.CLASE IS 'Clase del viaje. Utilizado para el tren.PREPUESTOS ANTIGUOS';

COMMENT ON COLUMN PRESUPUESTOS_SERVICIOS.NOMBRE IS 'De momento, se utiliza para el nombre del hotel.PREPUESTOS ANTIGUOS';

COMMENT ON COLUMN PRESUPUESTOS_SERVICIOS.ID_TARIFADEST IS 'Id de la tarifa destino si tuviera.PREPUESTOS ANTIGUOS';

COMMENT ON COLUMN PRESUPUESTOS_SERVICIOS.NUM_DIAS IS 'Numero de dias para cuando corresponda. Hotel (nº noches), Coches (nº dias)';

COMMENT ON COLUMN PRESUPUESTOS_SERVICIOS.ID_SERVICIO IS 'Id del servicio del que se registra';

COMMENT ON COLUMN PRESUPUESTOS_SERVICIOS.TARIFA_OBJ IS 'Tarifa objetivo. Solo se informará cuando se valide para que si algun dia cambia la tarifa objetivo, no se modifique el presupuesto';

ALTER TABLE PRESUPUESTOS_SERVICIOS  
MODIFY (TIPO NULL);

COMMENT ON COLUMN PRESUPUESTOS_SERVICIOS.CATEGORIA IS 'Categoria. Utilizado para el coche de alquiler.PREPUESTOS ANTIGUOS';

COMMENT ON COLUMN PRESUPUESTOS_SERVICIOS.FECHA_1 IS 'Fecha y hora usada como tal o la primera fecha de un rango. Por ej. Fecha desde.PREPUESTOS ANTIGUOS';

--------------------------------------------
//REGISTRADA
ALTER TABLE VIAJES 
ADD (ID_TARIFA_DESTINO NUMBER DEFAULT 0 );

COMMENT ON COLUMN VIAJES.ID_TARIFA_DESTINO IS 'Id de la tarifa destino. Si es 0, se leera del campo destino';
//FIN


ALTER TABLE VIAJES  
MODIFY (DESTINO NULL);

ALTER TABLE PRESUPUESTOS_SERVICIOS  
MODIFY (NUM_PLAN NULL);
