ALTER TABLE CONCEPTOS_BATZ 
ADD (MOSTRAR_HG_SIN_RECIBO NUMBER(1) DEFAULT 0 NOT NULL);

ALTER TABLE CONCEPTOS_BATZ RENAME COLUMN MOSTRAR_HG TO MOSTRAR_HG_RECIBO;

COMMENT ON COLUMN CONCEPTOS_BATZ.MOSTRAR_HG_RECIBO IS 'Indica si el concepto se mostrara en las hojas de gastos con recibo';

COMMENT ON COLUMN CONCEPTOS_BATZ.MOSTRAR_HG_SIN_RECIBO IS 'Indica si el concepto se mostrara en las hojas de gastos sin recibo';
