ALTER TABLE CAB_FAKTURA_EROSKI  
MODIFY (DOCBATZ NVARCHAR2(20) );

ALTER TABLE ASIENTOS_CONT_FACT_LINEAS 
ADD (LANTEGI VARCHAR2(20) );

ALTER TABLE ASIENTOS_CONT_FACT_LINEAS 
ADD (DESCRIPCION VARCHAR2(30) );

COMMENT ON COLUMN ASIENTOS_CONT_FACT_LINEAS.LANTEGI IS 'Lantegi';

COMMENT ON COLUMN ASIENTOS_CONT_FACT_LINEAS.DESCRIPCION IS 'Descripcion del asiento';

ALTER TABLE ASIENTOS_CONT_FACT_CAB 
ADD (CODTERPAGO VARCHAR2(10) );

ALTER TABLE ASIENTOS_CONT_FACT_CAB 
ADD (FORPAGO VARCHAR2(10) );

ALTER TABLE ASIENTOS_CONT_FACT_CAB 
ADD (DIVISA VARCHAR2(10) );

ALTER TABLE ASIENTOS_CONT_FACT_CAB 
ADD (FACTORDIV NUMBER );

ALTER TABLE ASIENTOS_CONT_FACT_CAB 
ADD (ANNO NUMBER );

ALTER TABLE ASIENTOS_CONT_FACT_CAB 
ADD (CODPRO VARCHAR2(20) );

ALTER TABLE ASIENTOS_CONT_FACT_CAB 
ADD (FECHA_IVA DATE );

COMMENT ON COLUMN ASIENTOS_CONT_FACT_CAB.CODTERPAGO IS 'Codigo termino de pago';

COMMENT ON COLUMN ASIENTOS_CONT_FACT_CAB.FORPAGO IS 'Forma de pago';

COMMENT ON COLUMN ASIENTOS_CONT_FACT_CAB.DIVISA IS 'Abreviatura de la divisa';

COMMENT ON COLUMN ASIENTOS_CONT_FACT_CAB.FACTORDIV IS 'Factor de conversion';

COMMENT ON COLUMN ASIENTOS_CONT_FACT_CAB.ANNO IS 'Año de contabilizacion';

COMMENT ON COLUMN ASIENTOS_CONT_FACT_CAB.CODPRO IS 'Codigo de proveedor';

COMMENT ON COLUMN ASIENTOS_CONT_FACT_CAB.FECHA_IVA IS 'Fecha del IVA';

ALTER TABLE ASIENTOS_CONT_FACT_CAB 
ADD (EMPRESA VARCHAR2(10) );

COMMENT ON COLUMN ASIENTOS_CONT_FACT_CAB.EMPRESA IS 'Empresa';

ALTER TABLE ASIENTOS_CONT_FACT_LINEAS 
ADD (COSTE_UNI NUMBER );

COMMENT ON COLUMN ASIENTOS_CONT_FACT_LINEAS.COSTE_UNI IS 'Coste unitario';

COMMENT ON COLUMN ASIENTOS_CONT_FACT_CAB.FECHA_IVA IS 'Fecha del IVA. La misma que la contabilidad';

COMMENT ON COLUMN ASIENTOS_CONT_FACT_LINEAS.COSTE_UNI IS 'Coste unitario. En nuestro caso, el mismo que el importe';
