ALTER TABLE ASIENTOS_CONT_VISAS 
ADD (IMPORTE_DEBE NUMBER );

ALTER TABLE ASIENTOS_CONT_VISAS 
ADD (IMPORTE_HABER NUMBER );

ALTER TABLE ASIENTOS_CONT_VISAS 
ADD (LANTEGI VARCHAR2(20) );

COMMENT ON COLUMN ASIENTOS_CONT_VISAS.IMPORTE_DEBE IS 'El importe debe que se mete en Navision';

COMMENT ON COLUMN ASIENTOS_CONT_VISAS.IMPORTE_HABER IS 'El importe haber que se mete en Navision';

COMMENT ON COLUMN ASIENTOS_CONT_VISAS.LANTEGI IS 'El lantegi que se mete en Navision';


ALTER TABLE ASIENTOS_CONT_VISAS 
ADD (DOC_BATZ VARCHAR2(15) );

COMMENT ON COLUMN ASIENTOS_CONT_VISAS.DOC_BATZ IS 'Documento de Batz';