
  CREATE TABLE "BIDAIAK"."MOVIMIENTOS_VISA_EXCEP" 
   (
   "ID" NUMBER, 
   "USUARIO" VARCHAR2(75 BYTE), 
   "TARJETA" VARCHAR2(16 BYTE), 
	 "SECTOR" VARCHAR2(75 BYTE), 
	 "ESTABLECIMIENTO" VARCHAR2(75 BYTE), 
	 "FECHA" DATE, 
	 "MONEDA" VARCHAR2(5 BYTE), 
	 "IMPORTE" NUMBER(8,2), 
	 "ID_PLANTA" NUMBER, 
	 "FECHA_INSERCION" DATE, 
	 "LOCALIDAD" VARCHAR2(50 BYTE), 
	 "ID_MONEDA" NUMBER,    
	 "ID_IMPORTACION" NUMBER, 	
	"ID_MONEDA_GASTO" NUMBER DEFAULT 90, 
	"IMPORTE_MONEDA_GASTO" NUMBER	
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BIDAIAK" ;

   COMMENT ON COLUMN "BIDAIAK"."MOVIMIENTOS_VISA_EXCEP"."ID" IS 'Autonumerico';
   COMMENT ON COLUMN "BIDAIAK"."MOVIMIENTOS_VISA_EXCEP"."USUARIO" IS 'Nombre del usuario';
   COMMENT ON COLUMN "BIDAIAK"."MOVIMIENTOS_VISA_EXCEP"."TARJETA" IS 'Numero de tarjeta';
   COMMENT ON COLUMN "BIDAIAK"."MOVIMIENTOS_VISA_EXCEP"."SECTOR" IS 'Sector al que pertenece el establecimiento';
   COMMENT ON COLUMN "BIDAIAK"."MOVIMIENTOS_VISA_EXCEP"."ESTABLECIMIENTO" IS 'Establecimiento del pago';
   COMMENT ON COLUMN "BIDAIAK"."MOVIMIENTOS_VISA_EXCEP"."FECHA" IS 'Fecha del pago';
   COMMENT ON COLUMN "BIDAIAK"."MOVIMIENTOS_VISA_EXCEP"."MONEDA" IS 'Moneda en la que nos facturan. Es siempre en EUR';
   COMMENT ON COLUMN "BIDAIAK"."MOVIMIENTOS_VISA_EXCEP"."IMPORTE" IS 'Importe pagado';
   COMMENT ON COLUMN "BIDAIAK"."MOVIMIENTOS_VISA_EXCEP"."ID_PLANTA" IS 'Planta en la que se realiza la gestion';
   COMMENT ON COLUMN "BIDAIAK"."MOVIMIENTOS_VISA_EXCEP"."FECHA_INSERCION" IS 'Fecha en la que se inserta el registro';
   COMMENT ON COLUMN "BIDAIAK"."MOVIMIENTOS_VISA_EXCEP"."LOCALIDAD" IS 'Localidad del pago';
   COMMENT ON COLUMN "BIDAIAK"."MOVIMIENTOS_VISA_EXCEP"."ID_MONEDA" IS 'Id de la moneda en la que nos facturan. Siempre en EUR';      
   COMMENT ON COLUMN "BIDAIAK"."MOVIMIENTOS_VISA_EXCEP"."ID_IMPORTACION" IS 'Id de la importacion para poder relacionarla';      
   COMMENT ON COLUMN "BIDAIAK"."MOVIMIENTOS_VISA_EXCEP"."ID_MONEDA_GASTO" IS 'Id de la moneda origen del pago. Es meramente informativa ya que siempre nos cobran en EUR';
   COMMENT ON COLUMN "BIDAIAK"."MOVIMIENTOS_VISA_EXCEP"."IMPORTE_MONEDA_GASTO" IS 'Importe en la moneda del gasto'; 
   
   ALTER TABLE MOVIMIENTOS_VISA_EXCEP  
MODIFY (ID NOT NULL);

ALTER TABLE MOVIMIENTOS_VISA_EXCEP  
MODIFY (ID_PLANTA NOT NULL);

ALTER TABLE MOVIMIENTOS_VISA_EXCEP  
MODIFY (FECHA_INSERCION NOT NULL);

ALTER TABLE MOVIMIENTOS_VISA_EXCEP  
MODIFY (ID_MONEDA NOT NULL);

ALTER TABLE MOVIMIENTOS_VISA_EXCEP  
MODIFY (ID_IMPORTACION NOT NULL);

ALTER TABLE MOVIMIENTOS_VISA_EXCEP  
MODIFY (ID_MONEDA_GASTO NOT NULL);

CREATE INDEX MOVIMIENTOS_VISA_EXCEP_INDEX1 ON MOVIMIENTOS_VISA_EXCEP (TARJETA ASC);

ALTER TABLE MOVIMIENTOS_VISA_EXCEP
ADD CONSTRAINT MOVIMIENTOS_VISA_EXCEP_PK PRIMARY KEY 
(
  ID 
)
ENABLE;

ALTER TABLE MOVIMIENTOS_VISA_EXCEP
ADD CONSTRAINT MOVIMIENTOS_VISA_EXCEP_FK1 FOREIGN KEY
(
  ID_IMPORTACION 
)
REFERENCES IMPORTACION_DOCS
(
  ID 
)
ENABLE;

COMMENT ON TABLE MOVIMIENTOS_VISA_EXCEP IS 'Se guardan los movimientos de visa de excepcion porque luego tienen que ir a una cuenta de Navision';


 CREATE SEQUENCE SEQ_MOV_VISA_EXCEP INCREMENT BY 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 NOCACHE;
   CREATE OR REPLACE TRIGGER "BIDAIAK"."TR_MOV_VISA_EXCEP" 
   BEFORE INSERT
   ON BIDAIAK.MOVIMIENTOS_VISA_EXCEP    REFERENCING NEW AS New OLD AS Old
   FOR EACH ROW
BEGIN
   SELECT SEQ_MOV_VISA_EXCEP.NEXTVAL INTO :NEW.id FROM DUAL;
END TR_MOV_VISA_EXCEP;

CREATE TABLE TMP_MOVIMIENTOS_VISA_EXCEP 
(
 USUARIO VARCHAR2(75 BYTE) 
, TARJETA VARCHAR2(16 BYTE) 
, SECTOR VARCHAR2(75 BYTE) 
, ESTABLECIMIENTO VARCHAR2(75 BYTE) 
, FECHA DATE 
, MONEDA VARCHAR2(5 BYTE) 
, IMPORTE NUMBER(8, 2) 
, ID_PLANTA NUMBER NOT NULL 
, FECHA_INSERCION DATE NOT NULL 
, LOCALIDAD VARCHAR2(50 BYTE) 
, ID_MONEDA NUMBER 
, ID_USUARIO NUMBER 
, ID_MONEDA_GASTO NUMBER NOT NULL 
, IMPORTE_MONEDA_GASTO NUMBER NOT NULL 
); 

COMMENT ON COLUMN TMP_MOVIMIENTOS_VISA_EXCEP.ID_MONEDA_GASTO IS 'Id de la moneda del gasto';

COMMENT ON COLUMN TMP_MOVIMIENTOS_VISA.IMPORTE_MONEDA_GASTO IS 'Importe en la moneda del gasto';




ALTER TABLE TMP_ASIENTO_CONT_VISAS 
ADD (LANTEGI VARCHAR2(20) );

ALTER TABLE TMP_ASIENTO_CONT_VISAS  
MODIFY (ID_SAB NULL);

ALTER TABLE TMP_ASIENTO_CONT_VISAS  
MODIFY (NUM_TRA NULL);

ALTER TABLE TMP_ASIENTO_CONT_VISAS  
MODIFY (NOMBRE NULL);

COMMENT ON COLUMN TMP_ASIENTO_CONT_VISAS.TIPO IS '0:Movimiento,1:Cuota,2: Visa excepcion';

COMMENT ON COLUMN TMP_ASIENTO_CONT_VISAS.LANTEGI IS 'Cuando es de tipo visas excepcion, se especificara aqui el lantegi ya que no se podra sacar del departamento';


ALTER TABLE VISAS_EXCEPCION 
ADD (NOMBRE_TARJETA VARCHAR2(75) );

COMMENT ON COLUMN VISAS_EXCEPCION.NOMBRE_TARJETA IS 'Nombre de la persona a la que esta asignada la visa';

CREATE TABLE CUENTAS_VISAS_EXCEPCION 
(
  ID_PLANTA NUMBER NOT NULL 
, CUENTA NUMBER NOT NULL 
, LANTEGI VARCHAR2(20) NOT NULL 
, CONSTRAINT CUENTAS_GASTOS_CONSUMIBLES_PK PRIMARY KEY 
  (
    ID_PLANTA 
  )
  ENABLE 
);

ALTER TABLE CUENTAS_VISAS_EXCEPCION
ADD CONSTRAINT CUENTAS_GASTOS_CONSUMIBLE_FK1 FOREIGN KEY
(
  ID_PLANTA 
)
REFERENCES SAB.PLANTAS
(
  ID 
)
ENABLE;

COMMENT ON TABLE CUENTAS_VISAS_EXCEPCION IS 'Cuentas de los gastos de consumibles (visas excepcion)';

COMMENT ON COLUMN CUENTAS_VISAS_EXCEPCION.ID_PLANTA IS 'Id de la planta';

COMMENT ON COLUMN CUENTAS_VISAS_EXCEPCION.CUENTA IS 'Cuenta';

COMMENT ON COLUMN CUENTAS_VISAS_EXCEPCION.LANTEGI IS 'Lantegi';

ALTER TABLE MOVIMIENTOS_VISA_EXCEP 
ADD (CUENTA NUMBER NOT NULL);

ALTER TABLE MOVIMIENTOS_VISA_EXCEP 
ADD (LANTEGI VARCHAR2(20) NOT NULL);

COMMENT ON COLUMN MOVIMIENTOS_VISA_EXCEP.CUENTA IS 'Cuenta contable';

COMMENT ON COLUMN MOVIMIENTOS_VISA_EXCEP.LANTEGI IS 'Lantegi asignado';

ALTER TABLE TMP_MOVIMIENTOS_VISA_EXCEP 
DROP COLUMN ID_USUARIO;

ALTER TABLE MOVIMIENTOS_VISA_EXCEP  
MODIFY (CUENTA NULL);

ALTER TABLE MOVIMIENTOS_VISA_EXCEP  
MODIFY (LANTEGI NULL);
