COMMENT ON COLUMN VIAJES.ESTADO IS 'Indica el estado de la solicitud. 1:Validada, 0:Cancelada,2: Pendiente de validacion,3:No validada';

CREATE TABLE VIAJES_ESTADOS 
(
  ID_VIAJE NUMBER NOT NULL 
, ESTADO NUMBER NOT NULL 
, FECHA DATE NOT NULL 
, ID_USUARIO NUMBER NOT NULL 
, CONSTRAINT VIAJES_ESTADOS_PK PRIMARY KEY 
  (
    ID_VIAJE 
  , FECHA 
  )
  ENABLE 
);

ALTER TABLE VIAJES_ESTADOS
ADD CONSTRAINT VIAJES_ESTADOS_FK1 FOREIGN KEY
(
  ID_VIAJE 
)
REFERENCES VIAJES
(
  ID 
)
ENABLE;

ALTER TABLE VIAJES_ESTADOS
ADD CONSTRAINT VIAJES_ESTADOS_FK2 FOREIGN KEY
(
  ID_USUARIO 
)
REFERENCES SAB.USUARIOS
(
  ID 
)
ENABLE;

COMMENT ON TABLE VIAJES_ESTADOS IS 'Tabla donde se guardará todos los estados por los que pasa un viaje';

COMMENT ON COLUMN VIAJES_ESTADOS.ID_VIAJE IS 'Id del viaje';

COMMENT ON COLUMN VIAJES_ESTADOS.ESTADO IS '0: Cancelado,1:Validado,2:Pendiente de validacion,3:No validado';

COMMENT ON COLUMN VIAJES_ESTADOS.FECHA IS 'Fecha';

COMMENT ON COLUMN VIAJES_ESTADOS.ID_USUARIO IS 'Id del usuario que hace la acción';

ALTER TABLE VIAJES_ESTADOS 
ADD (COMENTARIO NVARCHAR2(150) );

COMMENT ON COLUMN VIAJES_ESTADOS.COMENTARIO IS 'Comentario que se puede asignar en el rechazo/validacion';
