'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection

Namespace DAL_KaPlan
	
	<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="KAPLAN")>  _
	Partial Public Class ELL
		Inherits System.Data.Linq.DataContext
		
		Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
		
    #Region "Definiciones de métodos de extensibilidad"
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub InsertActualizaciones(instance As Registro.Actualizaciones)
    End Sub
    Partial Private Sub UpdateActualizaciones(instance As Registro.Actualizaciones)
    End Sub
    Partial Private Sub DeleteActualizaciones(instance As Registro.Actualizaciones)
    End Sub
    Partial Private Sub InsertHistorico_DOC(instance As Registro.Historico_DOC)
    End Sub
    Partial Private Sub UpdateHistorico_DOC(instance As Registro.Historico_DOC)
    End Sub
    Partial Private Sub DeleteHistorico_DOC(instance As Registro.Historico_DOC)
    End Sub
    #End Region
		
		Public Sub New()
			MyBase.New(Global.KaPlanLib.My.MySettings.Default.KAPLANConnectionString, mappingSource)
			OnCreated
		End Sub
		
		Public Sub New(ByVal connection As String)
			MyBase.New(connection, mappingSource)
			OnCreated
		End Sub
		
		Public Sub New(ByVal connection As System.Data.IDbConnection)
			MyBase.New(connection, mappingSource)
			OnCreated
		End Sub
		
		Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
			MyBase.New(connection, mappingSource)
			OnCreated
		End Sub
		
		Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
			MyBase.New(connection, mappingSource)
			OnCreated
		End Sub
		
		Public ReadOnly Property Actualizaciones() As System.Data.Linq.Table(Of Registro.Actualizaciones)
			Get
				Return Me.GetTable(Of Registro.Actualizaciones)
			End Get
		End Property
		
		Public ReadOnly Property Historico_DOC() As System.Data.Linq.Table(Of Registro.Historico_DOC)
			Get
				Return Me.GetTable(Of Registro.Historico_DOC)
			End Get
		End Property
	End Class
End Namespace

Namespace Registro
	
	<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.Actualizaciones")>  _
	Partial Public Class Actualizaciones
		Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
		
		Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
		
		Private _Catalogo As String
		
		Private _Conexion As String
		
		Private _Fecha As Date
		
    #Region "Definiciones de métodos de extensibilidad"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnCatalogoChanging(value As String)
    End Sub
    Partial Private Sub OnCatalogoChanged()
    End Sub
    Partial Private Sub OnConexionChanging(value As String)
    End Sub
    Partial Private Sub OnConexionChanged()
    End Sub
    Partial Private Sub OnFechaChanging(value As Date)
    End Sub
    Partial Private Sub OnFechaChanged()
    End Sub
    #End Region
		
		Public Sub New()
			MyBase.New
			OnCreated
		End Sub
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Catalogo", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false, IsPrimaryKey:=true)>  _
		Public Property Catalogo() As String
			Get
				Return Me._Catalogo
			End Get
			Set
				If (String.Equals(Me._Catalogo, value) = false) Then
					Me.OnCatalogoChanging(value)
					Me.SendPropertyChanging
					Me._Catalogo = value
					Me.SendPropertyChanged("Catalogo")
					Me.OnCatalogoChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Conexion", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false)>  _
		Public Property Conexion() As String
			Get
				Return Me._Conexion
			End Get
			Set
				If (String.Equals(Me._Conexion, value) = false) Then
					Me.OnConexionChanging(value)
					Me.SendPropertyChanging
					Me._Conexion = value
					Me.SendPropertyChanged("Conexion")
					Me.OnConexionChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Fecha", DbType:="DateTime NOT NULL")>  _
		Public Property Fecha() As Date
			Get
				Return Me._Fecha
			End Get
			Set
				If ((Me._Fecha = value)  _
							= false) Then
					Me.OnFechaChanging(value)
					Me.SendPropertyChanging
					Me._Fecha = value
					Me.SendPropertyChanged("Fecha")
					Me.OnFechaChanged
				End If
			End Set
		End Property
		
		Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
		
		Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
		
		Protected Overridable Sub SendPropertyChanging()
			If ((Me.PropertyChangingEvent Is Nothing)  _
						= false) Then
				RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
			End If
		End Sub
		
		Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
			If ((Me.PropertyChangedEvent Is Nothing)  _
						= false) Then
				RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
			End If
		End Sub
	End Class
	
	<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.Historico_DOC")>  _
	Partial Public Class Historico_DOC
		Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
		
		Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
		
		Private _ID As Integer
		
		Private _FechaGeneracion As System.Nullable(Of Date)
		
		Private _FechaInsercion As System.Nullable(Of Date)
		
		Private _Tipo As System.Nullable(Of Short)
		
		Private _Referencia As String
		
		Private _IdNivel As System.Nullable(Of Integer)
		
		Private _Documento As System.Data.Linq.Binary
		
		Private _Usuario As System.Nullable(Of Integer)
		
		Private _Maquina As String
		
		Private _IdPlanta As System.Nullable(Of Integer)
		
    #Region "Definiciones de métodos de extensibilidad"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnIDChanged()
    End Sub
    Partial Private Sub OnFechaGeneracionChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnFechaGeneracionChanged()
    End Sub
    Partial Private Sub OnFechaInsercionChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnFechaInsercionChanged()
    End Sub
    Partial Private Sub OnTipoChanging(value As System.Nullable(Of Short))
    End Sub
    Partial Private Sub OnTipoChanged()
    End Sub
    Partial Private Sub OnReferenciaChanging(value As String)
    End Sub
    Partial Private Sub OnReferenciaChanged()
    End Sub
    Partial Private Sub OnIdNivelChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnIdNivelChanged()
    End Sub
    Partial Private Sub OnDocumentoChanging(value As System.Data.Linq.Binary)
    End Sub
    Partial Private Sub OnDocumentoChanged()
    End Sub
    Partial Private Sub OnUsuarioChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnUsuarioChanged()
    End Sub
    Partial Private Sub OnMaquinaChanging(value As String)
    End Sub
    Partial Private Sub OnMaquinaChanged()
    End Sub
    Partial Private Sub OnIdPlantaChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnIdPlantaChanged()
    End Sub
    #End Region
		
		Public Sub New()
			MyBase.New
			OnCreated
		End Sub
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ID", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
		Public Property ID() As Integer
			Get
				Return Me._ID
			End Get
			Set
				If ((Me._ID = value)  _
							= false) Then
					Me.OnIDChanging(value)
					Me.SendPropertyChanging
					Me._ID = value
					Me.SendPropertyChanged("ID")
					Me.OnIDChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FechaGeneracion", DbType:="DateTime")>  _
		Public Property FechaGeneracion() As System.Nullable(Of Date)
			Get
				Return Me._FechaGeneracion
			End Get
			Set
				If (Me._FechaGeneracion.Equals(value) = false) Then
					Me.OnFechaGeneracionChanging(value)
					Me.SendPropertyChanging
					Me._FechaGeneracion = value
					Me.SendPropertyChanged("FechaGeneracion")
					Me.OnFechaGeneracionChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FechaInsercion", DbType:="DateTime")>  _
		Public Property FechaInsercion() As System.Nullable(Of Date)
			Get
				Return Me._FechaInsercion
			End Get
			Set
				If (Me._FechaInsercion.Equals(value) = false) Then
					Me.OnFechaInsercionChanging(value)
					Me.SendPropertyChanging
					Me._FechaInsercion = value
					Me.SendPropertyChanged("FechaInsercion")
					Me.OnFechaInsercionChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Tipo", DbType:="SmallInt")>  _
		Public Property Tipo() As System.Nullable(Of Short)
			Get
				Return Me._Tipo
			End Get
			Set
				If (Me._Tipo.Equals(value) = false) Then
					Me.OnTipoChanging(value)
					Me.SendPropertyChanging
					Me._Tipo = value
					Me.SendPropertyChanged("Tipo")
					Me.OnTipoChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Referencia", DbType:="NVarChar(50)")>  _
		Public Property Referencia() As String
			Get
				Return Me._Referencia
			End Get
			Set
				If (String.Equals(Me._Referencia, value) = false) Then
					Me.OnReferenciaChanging(value)
					Me.SendPropertyChanging
					Me._Referencia = value
					Me.SendPropertyChanged("Referencia")
					Me.OnReferenciaChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IdNivel", DbType:="Int")>  _
		Public Property IdNivel() As System.Nullable(Of Integer)
			Get
				Return Me._IdNivel
			End Get
			Set
				If (Me._IdNivel.Equals(value) = false) Then
					Me.OnIdNivelChanging(value)
					Me.SendPropertyChanging
					Me._IdNivel = value
					Me.SendPropertyChanged("IdNivel")
					Me.OnIdNivelChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Documento", DbType:="Image", CanBeNull:=true, UpdateCheck:=UpdateCheck.Never)>  _
		Public Property Documento() As System.Data.Linq.Binary
			Get
				Return Me._Documento
			End Get
			Set
				If (Object.Equals(Me._Documento, value) = false) Then
					Me.OnDocumentoChanging(value)
					Me.SendPropertyChanging
					Me._Documento = value
					Me.SendPropertyChanged("Documento")
					Me.OnDocumentoChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Usuario", DbType:="Int")>  _
		Public Property Usuario() As System.Nullable(Of Integer)
			Get
				Return Me._Usuario
			End Get
			Set
				If (Me._Usuario.Equals(value) = false) Then
					Me.OnUsuarioChanging(value)
					Me.SendPropertyChanging
					Me._Usuario = value
					Me.SendPropertyChanged("Usuario")
					Me.OnUsuarioChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Maquina", DbType:="NVarChar(50)")>  _
		Public Property Maquina() As String
			Get
				Return Me._Maquina
			End Get
			Set
				If (String.Equals(Me._Maquina, value) = false) Then
					Me.OnMaquinaChanging(value)
					Me.SendPropertyChanging
					Me._Maquina = value
					Me.SendPropertyChanged("Maquina")
					Me.OnMaquinaChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IdPlanta", DbType:="Int")>  _
		Public Property IdPlanta() As System.Nullable(Of Integer)
			Get
				Return Me._IdPlanta
			End Get
			Set
				If (Me._IdPlanta.Equals(value) = false) Then
					Me.OnIdPlantaChanging(value)
					Me.SendPropertyChanging
					Me._IdPlanta = value
					Me.SendPropertyChanged("IdPlanta")
					Me.OnIdPlantaChanged
				End If
			End Set
		End Property
		
		Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
		
		Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
		
		Protected Overridable Sub SendPropertyChanging()
			If ((Me.PropertyChangingEvent Is Nothing)  _
						= false) Then
				RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
			End If
		End Sub
		
		Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
			If ((Me.PropertyChangedEvent Is Nothing)  _
						= false) Then
				RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
			End If
		End Sub
	End Class
End Namespace
