'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ASSET
    Public Property COMPANY As String
    Public Property ASSET1 As String
    Public Property ASSETNAME As String
    Public Property EQUIPMENTTYPE As String
    Public Property BUSINESSUNIT As String
    Public Property PARENTASSET As String
    Public Property COMPANYLEVEL As Short
    Public Property LOCATION As String
    Public Property CUSTOMER As String
    Public Property PRIORITY As Short
    Public Property EQUIPMENT As String
    Public Property EQUIPMENTASSOCDATE As Nullable(Of Date)
    Public Property EQUIPMENTSTATE As String
    Public Property CALENDAR As String
    Public Property DEFAULTWORKSHOP As String
    Public Property DOWNTIMEHOURRATE As Nullable(Of Decimal)
    Public Property SAFETYPLAN As String
    Public Property RECORDSTATE As String
    Public Property CREATIONUSER As String
    Public Property CREATIONDATA As Nullable(Of Date)
    Public Property LASTUPDATEUSER As String
    Public Property LASTUPDATEDATA As Nullable(Of Date)

    Public Overridable Property ASSET11 As ICollection(Of ASSET) = New HashSet(Of ASSET)
    Public Overridable Property ASSET2 As ASSET

End Class
