CREATE TABLE "BIDAIAK"."TMP_ASIENTO_CONT"
  (
    "ID_SAB"       NUMBER NOT NULL ENABLE,
    "NUM_TRA"      NUMBER NOT NULL ENABLE,
    "NOMBRE"       VARCHAR2(40 BYTE) NOT NULL ENABLE,
    "COD_DEPART"   NUMBER NOT NULL ENABLE,
    "DEPARTAMENTO" VARCHAR2(75 BYTE) NOT NULL ENABLE,
    "BASEEXE_0"    NUMBER NOT NULL ENABLE,
    "BASEIR_8"     NUMBER NOT NULL ENABLE,
    "BASEIG_18"    NUMBER NOT NULL ENABLE,
    "FECHA_INSERCION" DATE NOT NULL ENABLE,
    "ID_PLANTA"           NUMBER NOT NULL ENABLE,
    "UNIDAD_ORGANIZATIVA" VARCHAR2(75 BYTE),
    "CUOTAG_18"           NUMBER,
    "CUOTAR_8"            NUMBER,
    "CUOTARE_0"           NUMBER,
    "REGESP"              NUMBER,
    "CUENTA_18"           NUMBER NOT NULL ENABLE,
    "CUENTA_8"            NUMBER NOT NULL ENABLE,
    "CUENTA_0"            NUMBER NOT NULL ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "BIDAIAK" ;
COMMENT ON COLUMN "BIDAIAK"."TMP_ASIENTO_CONT"."ID_SAB"
IS
  'Id de Sab del usuario';
  COMMENT ON COLUMN "BIDAIAK"."TMP_ASIENTO_CONT"."NUM_TRA"
IS
  'Numero de trabajador';
  COMMENT ON COLUMN "BIDAIAK"."TMP_ASIENTO_CONT"."NOMBRE"
IS
  'Nombre completo de la persona';
  COMMENT ON COLUMN "BIDAIAK"."TMP_ASIENTO_CONT"."COD_DEPART"
IS
  'Codigo del departamento';
  COMMENT ON COLUMN "BIDAIAK"."TMP_ASIENTO_CONT"."DEPARTAMENTO"
IS
  'Descripcion del departamento';
  COMMENT ON COLUMN "BIDAIAK"."TMP_ASIENTO_CONT"."BASEEXE_0"
IS
  'Importe base al 0%';
  COMMENT ON COLUMN "BIDAIAK"."TMP_ASIENTO_CONT"."BASEIR_8"
IS
  'Importe base al 8% IVA';
  COMMENT ON COLUMN "BIDAIAK"."TMP_ASIENTO_CONT"."BASEIG_18"
IS
  'Importe base al 18% de IVA';
  COMMENT ON COLUMN "BIDAIAK"."TMP_ASIENTO_CONT"."FECHA_INSERCION"
IS
  'Fecha en la que se inserto';
  COMMENT ON COLUMN "BIDAIAK"."TMP_ASIENTO_CONT"."ID_PLANTA"
IS
  'Id de la planta';
  COMMENT ON COLUMN "BIDAIAK"."TMP_ASIENTO_CONT"."UNIDAD_ORGANIZATIVA"
IS
  'Nombre de la unidad organizativa a la que pertenece';
  COMMENT ON COLUMN "BIDAIAK"."TMP_ASIENTO_CONT"."CUOTAG_18"
IS
  'Iva del importe base del 18%';
  COMMENT ON COLUMN "BIDAIAK"."TMP_ASIENTO_CONT"."CUOTAR_8"
IS
  'Iva del importe base del 8%';
  COMMENT ON COLUMN "BIDAIAK"."TMP_ASIENTO_CONT"."CUOTARE_0"
IS
  'Iva del importe base sin iva';
  COMMENT ON COLUMN "BIDAIAK"."TMP_ASIENTO_CONT"."CUENTA_18"
IS
  'Cuenta al 18%';
  COMMENT ON COLUMN "BIDAIAK"."TMP_ASIENTO_CONT"."CUENTA_8"
IS
  'Cuenta al 8%';
  COMMENT ON COLUMN "BIDAIAK"."TMP_ASIENTO_CONT"."CUENTA_0"
IS
  'Cuenta al 0%';