CREATE TABLE "BIDAIAK"."TMP_FAKTURA_EROSKI"
  (
    "BONO" NVARCHAR2(30),
    "FACTURA" NVARCHAR2(30) NOT NULL ENABLE,
    "ALBARAN" NVARCHAR2(30) NOT NULL ENABLE,
    "FECHASERV" DATE,
    "DIAS" NUMBER,
    "PRODUCTO" NVARCHAR2(100),
    "DESTINO" NVARCHAR2(100),
    "PROVEEDOR" NVARCHAR2(100),
    "PERSONA" NVARCHAR2(100),
    "BASEIG"  NUMBER,
    "CUOTAG"  NUMBER,
    "BASEIR"  NUMBER,
    "CUOTAR"  NUMBER,
    "BASEEXE" NUMBER,
    "REGESP"  NUMBER,
    "CUOTARE" NUMBER,
    "IMPORTE" NUMBER,
    "NIVEL1" NVARCHAR2(100),
    "NIVEL2" NVARCHAR2(100),
    "NIVEL3" NVARCHAR2(100),
    "NIVEL4" NVARCHAR2(100),
    "ID_USER" NUMBER,
    "FECHA_INSERCION" DATE NOT NULL ENABLE,
    "ID_PLANTA" NUMBER DEFAULT NULL NOT NULL ENABLE,
    "ID_VIAJES" VARCHAR2(20 BYTE),
    "ID_SABORG" NUMBER,
    CONSTRAINT "TMP_FAKTURA_EROSKI__FK1" FOREIGN KEY ("ID_USER") REFERENCES "SAB"."USUARIOS" ("ID") ENABLE,
    CONSTRAINT "TMP_FAKTURA_EROSKI_FK2" FOREIGN KEY ("ID_PLANTA") REFERENCES "SAB"."PLANTAS" ("ID") ENABLE
  )
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "BIDAIAK" ;
COMMENT ON COLUMN "BIDAIAK"."TMP_FAKTURA_EROSKI"."BASEIG"
IS
  'IVA 18%';
  COMMENT ON COLUMN "BIDAIAK"."TMP_FAKTURA_EROSKI"."BASEIR"
IS
  'IVA 8%';
  COMMENT ON COLUMN "BIDAIAK"."TMP_FAKTURA_EROSKI"."BASEEXE"
IS
  'IVA 0%';
  COMMENT ON COLUMN "BIDAIAK"."TMP_FAKTURA_EROSKI"."NIVEL2"
IS
  'Organizador del viaje';
  COMMENT ON COLUMN "BIDAIAK"."TMP_FAKTURA_EROSKI"."ID_USER"
IS
  'Id del usuario con el que esta relacionado';
  COMMENT ON COLUMN "BIDAIAK"."TMP_FAKTURA_EROSKI"."ID_PLANTA"
IS
  'Id de la planta  a la que pertenece';
  COMMENT ON COLUMN "BIDAIAK"."TMP_FAKTURA_EROSKI"."ID_VIAJES"
IS
  'Indica el id viaje si lo ha encontrado. sino null. Puede que haya mas de un viaje porque un albaran puede estar en mas de un viaje';
  COMMENT ON COLUMN "BIDAIAK"."TMP_FAKTURA_EROSKI"."ID_SABORG"
IS
  'Id de Sab del organizador si se encuentra';
  COMMENT ON TABLE "BIDAIAK"."TMP_FAKTURA_EROSKI"
IS
  'Tabla donde dejaran los resultados temporalmente antes de insertarlos en la tabla de FAKTURAS_EROSKI';