CREATE TABLE "BIDAIAK"."CUENTAS_PLANTAS_FILIALES"
  (
    "ID_PLANTA"       NUMBER NOT NULL ENABLE,
    "CUENTA_18"       NUMBER NOT NULL ENABLE,
    "CUENTA_8"        NUMBER NOT NULL ENABLE,
    "CUENTA_0"        NUMBER NOT NULL ENABLE,
    "OF_IMPRODUCTIVA" NUMBER NOT NULL ENABLE,
    CONSTRAINT "CUENTAS_PLANTAS_FILIALES_PK" PRIMARY KEY ("ID_PLANTA", "CUENTA_18") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "BIDAIAK" ENABLE,
    CONSTRAINT "CUENTAS_PLANTAS_FILIALES__FK1" FOREIGN KEY ("ID_PLANTA") REFERENCES "SAB"."PLANTAS" ("ID") ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "BIDAIAK" ;
COMMENT ON COLUMN "BIDAIAK"."CUENTAS_PLANTAS_FILIALES"."ID_PLANTA"
IS
  'Id de la planta';
  COMMENT ON COLUMN "BIDAIAK"."CUENTAS_PLANTAS_FILIALES"."CUENTA_18"
IS
  'Nº de cuenta al 18%';
  COMMENT ON COLUMN "BIDAIAK"."CUENTAS_PLANTAS_FILIALES"."CUENTA_8"
IS
  'Nº de cuenta al 8%';
  COMMENT ON COLUMN "BIDAIAK"."CUENTAS_PLANTAS_FILIALES"."CUENTA_0"
IS
  'Nº de cuenta al 0%';
  COMMENT ON COLUMN "BIDAIAK"."CUENTAS_PLANTAS_FILIALES"."OF_IMPRODUCTIVA"
IS
  'Of improductiva asociada a un departamento. Cuando se realice un viaje sin of, esta of sera la que se registre en los costos';
  COMMENT ON TABLE "BIDAIAK"."CUENTAS_PLANTAS_FILIALES"
IS
  'Las plantas extranjeras, tendran asociadas una cuenta contable para todos los departamentos
Para las plantas de Igorre, habra asociada una cuenta contable para cada departamento y en esta tabla no estaran reflejados';