CREATE TABLE "BIDAIAK"."DEPARTAMENTOS"
  (
    "ID"              NUMBER,
    "NOMBRE"          VARCHAR2(100 BYTE),
    "OBSOLETO"        NUMBER(1,0) DEFAULT NULL NOT NULL ENABLE,
    "ID_PLANTA"       NUMBER DEFAULT NULL NOT NULL ENABLE,
    "CUENTA_18"       NUMBER NOT NULL ENABLE,
    "CUENTA_8"        NUMBER NOT NULL ENABLE,
    "CUENTA_0"        NUMBER NOT NULL ENABLE,
    "OF_IMPRODUCTIVA" NUMBER NOT NULL ENABLE,
    CONSTRAINT "DEPARTAMENTOS_PLANTAS_FK1" FOREIGN KEY ("ID_PLANTA") REFERENCES "SAB"."PLANTAS" ("ID") ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "BIDAIAK" ;
COMMENT ON COLUMN "BIDAIAK"."DEPARTAMENTOS"."ID"
IS
  'Codigo del departamento';
  COMMENT ON COLUMN "BIDAIAK"."DEPARTAMENTOS"."NOMBRE"
IS
  'Nombre del departamento';
  COMMENT ON COLUMN "BIDAIAK"."DEPARTAMENTOS"."OBSOLETO"
IS
  '0:Activo y 1:Obsoleto';
  COMMENT ON COLUMN "BIDAIAK"."DEPARTAMENTOS"."ID_PLANTA"
IS
  'Id de la planta';
  COMMENT ON COLUMN "BIDAIAK"."DEPARTAMENTOS"."CUENTA_18"
IS
  'Cuenta al 18%';
  COMMENT ON COLUMN "BIDAIAK"."DEPARTAMENTOS"."CUENTA_8"
IS
  'Cuenta al 8%';
  COMMENT ON COLUMN "BIDAIAK"."DEPARTAMENTOS"."CUENTA_0"
IS
  'Cuenta al 0%';
  COMMENT ON COLUMN "BIDAIAK"."DEPARTAMENTOS"."OF_IMPRODUCTIVA"
IS
  'Of improductiva asociada a un departamento. Cuando se realice un viaje sin of, esta of sera la que se registre en los costos';