--
-- Create Schema Script 
--   Database Version   : 11.1.0.7.0 
--   Toad Version       : 10.1.0.7 
--   DB Connect String  : GARAPEN 
--   Schema             : BIDAIAK 
--   Script Created by  : BIDAIAK 
--   Script Created at  : 26/04/2011 14:48:58 
--   Physical Location  :  
--   Notes              :  
--

-- Object Counts: 
--   Indexes: 24        Columns: 34         
--   Sequences: 13 
--   Tables: 25         Columns: 204        Constraints: 55     
--   Triggers: 11 


CREATE SEQUENCE BIDAIAK.SEQ_CONCEPTOS_BATZ
  START WITH 41
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


CREATE SEQUENCE BIDAIAK.SEQ_CUENTAS_CONT
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


CREATE SEQUENCE BIDAIAK.SEQ_HG_SIN_VIAJE
  START WITH 8
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


CREATE SEQUENCE BIDAIAK.SEQ_HOJAS_GASTOS
  START WITH 281
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


CREATE SEQUENCE BIDAIAK.SEQ_LINEAS_AGENCIA
  START WITH 297
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


CREATE SEQUENCE BIDAIAK.SEQ_LINEAS_HOJA_GASTOS
  START WITH 361
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


CREATE SEQUENCE BIDAIAK.SEQ_MOVIMIENTOS
  START WITH 327
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


CREATE SEQUENCE BIDAIAK.SEQ_MOV_VISA
  START WITH 1981
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


CREATE SEQUENCE BIDAIAK.SEQ_SERV_AGENCIA
  START WITH 45
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


CREATE SEQUENCE BIDAIAK.SEQ_TIPO_GASTOS
  START WITH 21
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


CREATE SEQUENCE BIDAIAK.SEQ_UNIDADES_ORG
  START WITH 41
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


CREATE SEQUENCE BIDAIAK.SEQ_VIAJES
  START WITH 270
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


CREATE SEQUENCE BIDAIAK.SEQ_VISAS
  START WITH 83
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


CREATE TABLE BIDAIAK.ANTICIPOS
(
  ID_VIAJE             NUMBER,
  FECHA_NECESIDAD      DATE,
  ESTADO               NUMBER                   NOT NULL,
  ID_RESP_LIQUIDACION  NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE BIDAIAK.ANTICIPOS IS 'Cabecera de los anticipos solicitados';

COMMENT ON COLUMN BIDAIAK.ANTICIPOS.ID_VIAJE IS 'Id del viaje';

COMMENT ON COLUMN BIDAIAK.ANTICIPOS.FECHA_NECESIDAD IS 'Fecha en la que se requiere el anticipo';

COMMENT ON COLUMN BIDAIAK.ANTICIPOS.ESTADO IS 'Estado del anticipo. 1:Solicitado,2:En tramite,3:Preparado,4:Entregado,5:Cerrado;0:Cancelado por el usuario';

COMMENT ON COLUMN BIDAIAK.ANTICIPOS.ID_RESP_LIQUIDACION IS 'Usuario responsable de un anticipo. Sera el que recoga el anticipo';


CREATE TABLE BIDAIAK.ANTICIPOS_ESTADOS
(
  ID_ANTICIPO  NUMBER                           NOT NULL,
  ESTADO       NUMBER                           NOT NULL,
  FECHA        DATE                             NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE BIDAIAK.ANTICIPOS_ESTADOS IS 'Guarda la fecha en la que el anticipo cambia de estado';

COMMENT ON COLUMN BIDAIAK.ANTICIPOS_ESTADOS.ID_ANTICIPO IS 'Id del anticipo';

COMMENT ON COLUMN BIDAIAK.ANTICIPOS_ESTADOS.ESTADO IS 'Estado del cambio';

COMMENT ON COLUMN BIDAIAK.ANTICIPOS_ESTADOS.FECHA IS 'Fecha de cambio';


CREATE TABLE BIDAIAK.CONCEPTOS_BATZ
(
  ID                NUMBER                      NOT NULL,
  NOMBRE            VARCHAR2(75 BYTE)           NOT NULL,
  REQUIERE_DETALLE  NUMBER(1)                   NOT NULL,
  MOSTRAR_HG        NUMBER(1)                   NOT NULL,
  OBSOLETO          NUMBER(1)                   NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE BIDAIAK.CONCEPTOS_BATZ IS 'En esta tabla se guardaran los conceptos declarados en batz, en los que se agruparan los conceptos de las visas y de las facturas de la agencia.
Por ejemplo:
En los conceptos de la visa, vienen RESTAURANTES, COMIDA RAPIDA, CAFETERIAS ,ETC..
Estos conceptos, se agruparan en un concepto de Batz denominado RESTAURANTES
El concepto 0, no se podra borrar ya que se utiliza para que al venir un concepto de visa no agrupado, por defecto le asigne este';

COMMENT ON COLUMN BIDAIAK.CONCEPTOS_BATZ.ID IS 'Identificador del concepto';

COMMENT ON COLUMN BIDAIAK.CONCEPTOS_BATZ.NOMBRE IS 'Nombre del concepto';

COMMENT ON COLUMN BIDAIAK.CONCEPTOS_BATZ.REQUIERE_DETALLE IS 'Puede que se creen algunos conceptos tipo otros,varios, en los que en ciertas paginas, haya que introducir un texto explicativo';

COMMENT ON COLUMN BIDAIAK.CONCEPTOS_BATZ.MOSTRAR_HG IS 'Indica si el concepto se mostrara en las hojas de gastos';

COMMENT ON COLUMN BIDAIAK.CONCEPTOS_BATZ.OBSOLETO IS '0:Activo, 1:Obsoleto';


CREATE TABLE BIDAIAK.CUENTAS_PLANTAS_FILIALES
(
  ID_PLANTA  NUMBER                             NOT NULL,
  CUENTA     NUMBER                             NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE BIDAIAK.CUENTAS_PLANTAS_FILIALES IS 'Las plantas extranjeras, tendran asociadas una cuenta contable para todos los departamentos
Para las plantas de Igorre, habra asociada una cuenta contable para cada departamento y en esta tabla no estaran reflejados';

COMMENT ON COLUMN BIDAIAK.CUENTAS_PLANTAS_FILIALES.ID_PLANTA IS 'Id de la planta';

COMMENT ON COLUMN BIDAIAK.CUENTAS_PLANTAS_FILIALES.CUENTA IS 'Nº de cuenta';


CREATE TABLE BIDAIAK.DEPARTAMENTOS
(
  ID         NUMBER,
  NOMBRE     VARCHAR2(100 BYTE),
  CUENTA     NUMBER,
  OBSOLETO   NUMBER(1)                          DEFAULT NULL                  NOT NULL,
  ID_PLANTA  NUMBER                             DEFAULT NULL                  NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN BIDAIAK.DEPARTAMENTOS.ID IS 'Codigo del departamento';

COMMENT ON COLUMN BIDAIAK.DEPARTAMENTOS.NOMBRE IS 'Nombre del departamento';

COMMENT ON COLUMN BIDAIAK.DEPARTAMENTOS.CUENTA IS 'Cuenta contable';

COMMENT ON COLUMN BIDAIAK.DEPARTAMENTOS.OBSOLETO IS '0:Activo y 1:Obsoleto';

COMMENT ON COLUMN BIDAIAK.DEPARTAMENTOS.ID_PLANTA IS 'Id de la planta';


CREATE TABLE BIDAIAK.FAKTURA_EROSKI
(
  BONO             NVARCHAR2(30),
  FACTURA          NVARCHAR2(30)                NOT NULL,
  ALBARAN          NVARCHAR2(30)                NOT NULL,
  FECHASERV        DATE,
  DIAS             NUMBER,
  PRODUCTO         NVARCHAR2(100),
  DESTINO          NVARCHAR2(100),
  PROVEEDOR        NVARCHAR2(100),
  PERSONA          NVARCHAR2(100),
  BASEIG           NUMBER,
  CUOTAG           NUMBER,
  BASEIR           NUMBER,
  CUOTAR           NUMBER,
  BASEEXE          NUMBER,
  REGESP           NUMBER,
  CUOTARE          NUMBER,
  IMPORTE          NUMBER,
  NIVEL1           NVARCHAR2(100),
  NIVEL2           NVARCHAR2(100),
  NIVEL3           NVARCHAR2(100),
  NIVEL4           NVARCHAR2(100),
  ID_USER          NUMBER,
  FECHA_INSERCION  DATE                         NOT NULL,
  ID_PLANTA        NUMBER                       DEFAULT NULL                  NOT NULL,
  ID_VIAJE         NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN BIDAIAK.FAKTURA_EROSKI.ID_USER IS 'Id del usuario con el que esta relacionado';

COMMENT ON COLUMN BIDAIAK.FAKTURA_EROSKI.ID_PLANTA IS 'Id de la planta  a la que pertenece';

COMMENT ON COLUMN BIDAIAK.FAKTURA_EROSKI.ID_VIAJE IS 'Indica el id viaje si lo ha encontrado. sino null';


CREATE TABLE BIDAIAK.IMPORTACION_DOCS
(
  FECHA          DATE                           NOT NULL,
  CON_VIAJE      NUMBER,
  SIN_VIAJE      NUMBER,
  TIPO           NUMBER                         NOT NULL,
  NUM_REGISTROS  NUMBER                         NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE BIDAIAK.IMPORTACION_DOCS IS 'Cada vez que se realice una importacion del fichero de visas o de facturas, se registrara en esta tabla';

COMMENT ON COLUMN BIDAIAK.IMPORTACION_DOCS.FECHA IS 'Fecha y hora en la que se sube';

COMMENT ON COLUMN BIDAIAK.IMPORTACION_DOCS.CON_VIAJE IS 'Indica el numero de registros de visa que se han podido enlazar con algun viaje';

COMMENT ON COLUMN BIDAIAK.IMPORTACION_DOCS.SIN_VIAJE IS 'Movimientos que no se han podido ligar con ningun viaje';

COMMENT ON COLUMN BIDAIAK.IMPORTACION_DOCS.TIPO IS 'Indicara el tipo de documento importado. 1:Visas, 2:Facturas(Agencia)';


CREATE TABLE BIDAIAK.MOVIMIENTOS_VISA
(
  USUARIO          VARCHAR2(75 BYTE),
  TARJETA          VARCHAR2(16 BYTE),
  SECTOR           VARCHAR2(75 BYTE),
  ESTABLECIMIENTO  VARCHAR2(75 BYTE),
  FECHA            DATE,
  MONEDA           VARCHAR2(5 BYTE),
  IMPORTE          NUMBER(8,2),
  ID_VIAJE         NUMBER,
  ID_PLANTA        NUMBER                       NOT NULL,
  FECHA_INSERCION  DATE                         NOT NULL,
  LOCALIDAD        VARCHAR2(50 BYTE),
  ID_MONEDA        NUMBER,
  ESTADO           NUMBER(1),
  ID_RESPONSABLE   NUMBER,
  ID_USUARIO       NUMBER,
  ID               NUMBER                       NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN BIDAIAK.MOVIMIENTOS_VISA.ID IS 'Autonumerico';

COMMENT ON COLUMN BIDAIAK.MOVIMIENTOS_VISA.USUARIO IS 'Nombre del usuario';

COMMENT ON COLUMN BIDAIAK.MOVIMIENTOS_VISA.TARJETA IS 'Numero de tarjeta';

COMMENT ON COLUMN BIDAIAK.MOVIMIENTOS_VISA.SECTOR IS 'Sector al que pertenece el establecimiento';

COMMENT ON COLUMN BIDAIAK.MOVIMIENTOS_VISA.ESTABLECIMIENTO IS 'Establecimiento del pago';

COMMENT ON COLUMN BIDAIAK.MOVIMIENTOS_VISA.FECHA IS 'Fecha del pago';

COMMENT ON COLUMN BIDAIAK.MOVIMIENTOS_VISA.MONEDA IS 'Moneda en la que se pago';

COMMENT ON COLUMN BIDAIAK.MOVIMIENTOS_VISA.IMPORTE IS 'Importe pagado';

COMMENT ON COLUMN BIDAIAK.MOVIMIENTOS_VISA.ID_VIAJE IS 'Id del viaje con el que puede estar asociado el pago';

COMMENT ON COLUMN BIDAIAK.MOVIMIENTOS_VISA.ID_PLANTA IS 'Planta en la que se realiza la gestion';

COMMENT ON COLUMN BIDAIAK.MOVIMIENTOS_VISA.FECHA_INSERCION IS 'Fecha en la que se inserta el registro';

COMMENT ON COLUMN BIDAIAK.MOVIMIENTOS_VISA.LOCALIDAD IS 'Localidad del pago';

COMMENT ON COLUMN BIDAIAK.MOVIMIENTOS_VISA.ID_MONEDA IS 'Id de la moneda';

COMMENT ON COLUMN BIDAIAK.MOVIMIENTOS_VISA.ESTADO IS 'Estado del gastos. 1 Sin validar, 2:Validado, 3 Rechazados y 4:Liquidados';

COMMENT ON COLUMN BIDAIAK.MOVIMIENTOS_VISA.ID_RESPONSABLE IS 'Id del usuario responsable';

COMMENT ON COLUMN BIDAIAK.MOVIMIENTOS_VISA.ID_USUARIO IS 'Id del usuario';


CREATE TABLE BIDAIAK.PERFILES
(
  ID_USER    NUMBER                             NOT NULL,
  ID_PLANTA  NUMBER                             NOT NULL,
  PERFIL     NUMBER                             NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE BIDAIAK.PERFILES IS 'Contiene los perfiles de los usuarios';

COMMENT ON COLUMN BIDAIAK.PERFILES.ID_USER IS 'Id del usuario';

COMMENT ON COLUMN BIDAIAK.PERFILES.ID_PLANTA IS 'Id de la planta';

COMMENT ON COLUMN BIDAIAK.PERFILES.PERFIL IS 'Perfil:Administrador = 1, Planificador = 2, Agencia = 3, Financiero = 4, Consultor = 5';


CREATE TABLE BIDAIAK.RELACION_CONCEPTOS
(
  CONCEPTO_FICHERO  VARCHAR2(75 BYTE)           NOT NULL,
  ID_CONCEPTO_BATZ  NUMBER                      NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE BIDAIAK.RELACION_CONCEPTOS IS 'Tabla para guardar la relacion de que conceptos importados de ficheros, se relacionan con conceptos de batz';

COMMENT ON COLUMN BIDAIAK.RELACION_CONCEPTOS.CONCEPTO_FICHERO IS 'El concepto que se importa de los ficheros de visa y de agencias';

COMMENT ON COLUMN BIDAIAK.RELACION_CONCEPTOS.ID_CONCEPTO_BATZ IS 'Id del concepto de batz con el que se relaciona';


CREATE TABLE BIDAIAK.SERV_AGENCIA
(
  ID           NUMBER                           NOT NULL,
  NOMBRE       VARCHAR2(30 BYTE)                NOT NULL,
  DESCRIPCION  VARCHAR2(75 BYTE),
  OBSOLETO     NUMBER(1)                        NOT NULL,
  ID_PLANTA    NUMBER                           NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE BIDAIAK.SERV_AGENCIA IS 'Servicios que ofrece la agencia que luego seran escogidos por las personas que vayan de viaje';

COMMENT ON COLUMN BIDAIAK.SERV_AGENCIA.ID IS 'Id autonumerico';

COMMENT ON COLUMN BIDAIAK.SERV_AGENCIA.NOMBRE IS 'Nombre del servicio que ofrece la agencia';

COMMENT ON COLUMN BIDAIAK.SERV_AGENCIA.DESCRIPCION IS 'Descripcion acerca de este servicio';

COMMENT ON COLUMN BIDAIAK.SERV_AGENCIA.OBSOLETO IS 'Indica si esta obsoleto o no';

COMMENT ON COLUMN BIDAIAK.SERV_AGENCIA.ID_PLANTA IS 'Id de la planta';


CREATE TABLE BIDAIAK.SOLICITUD_AGENCIA
(
  ID_VIAJE          NUMBER                      NOT NULL,
  COMEN_USER        VARCHAR2(200 BYTE),
  ESTADO            NUMBER                      NOT NULL,
  VALIDADA          NUMBER(1)                   NOT NULL,
  F_LIMITE_TARIFAS  DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE BIDAIAK.SOLICITUD_AGENCIA IS 'Cabecera de las solicitudes realizadas';

COMMENT ON COLUMN BIDAIAK.SOLICITUD_AGENCIA.ID_VIAJE IS 'Id del viaje';

COMMENT ON COLUMN BIDAIAK.SOLICITUD_AGENCIA.COMEN_USER IS 'Comentario del usuario';

COMMENT ON COLUMN BIDAIAK.SOLICITUD_AGENCIA.ESTADO IS 'Posible estado de la solicitud.1:Solicitado,2:Tramite,3:Gestionado;4:Cerrada;0:Cancelado por el usuario';

COMMENT ON COLUMN BIDAIAK.SOLICITUD_AGENCIA.VALIDADA IS 'Indica si ha sido validada por un responsable o no';

COMMENT ON COLUMN BIDAIAK.SOLICITUD_AGENCIA.F_LIMITE_TARIFAS IS 'Indica la fecha limite de vigencia de las tarifas puestas por el de la agencia';


CREATE TABLE BIDAIAK.TIPO_GASTOS
(
  ID           NUMBER                           NOT NULL,
  NOMBRE       VARCHAR2(30 BYTE)                NOT NULL,
  DESCRIPCION  VARCHAR2(75 BYTE),
  OBSOLETO     NUMBER(1)                        NOT NULL,
  ID_PLANTA    NUMBER                           NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE BIDAIAK.TIPO_GASTOS IS 'Posibles tipos de gastos (metalico, sin recibo, kilometraje....)';

COMMENT ON COLUMN BIDAIAK.TIPO_GASTOS.ID IS 'Id autonumerico';

COMMENT ON COLUMN BIDAIAK.TIPO_GASTOS.NOMBRE IS 'Nombre del tipo de gasto';


CREATE TABLE BIDAIAK.TMP_ASIENTO_CONT
(
  ID_SAB               NUMBER                   NOT NULL,
  NUM_TRA              NUMBER                   NOT NULL,
  NOMBRE               VARCHAR2(40 BYTE)        NOT NULL,
  COD_DEPART           NUMBER                   NOT NULL,
  DEPARTAMENTO         VARCHAR2(75 BYTE)        NOT NULL,
  CUENTA               NUMBER                   NOT NULL,
  IMPORTE_0            NUMBER                   NOT NULL,
  IMPORTE_8            NUMBER                   NOT NULL,
  IMPORTE_18           NUMBER                   NOT NULL,
  FECHA_INSERCION      DATE                     NOT NULL,
  ID_PLANTA            NUMBER                   NOT NULL,
  UNIDAD_ORGANIZATIVA  VARCHAR2(75 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN BIDAIAK.TMP_ASIENTO_CONT.ID_SAB IS 'Id de Sab del usuario';

COMMENT ON COLUMN BIDAIAK.TMP_ASIENTO_CONT.NUM_TRA IS 'Numero de trabajador';

COMMENT ON COLUMN BIDAIAK.TMP_ASIENTO_CONT.NOMBRE IS 'Nombre completo de la persona';

COMMENT ON COLUMN BIDAIAK.TMP_ASIENTO_CONT.COD_DEPART IS 'Codigo del departamento';

COMMENT ON COLUMN BIDAIAK.TMP_ASIENTO_CONT.DEPARTAMENTO IS 'Descripcion del departamento';

COMMENT ON COLUMN BIDAIAK.TMP_ASIENTO_CONT.CUENTA IS 'Cuenta contable del departamento';

COMMENT ON COLUMN BIDAIAK.TMP_ASIENTO_CONT.IMPORTE_0 IS 'Importe al 0%';

COMMENT ON COLUMN BIDAIAK.TMP_ASIENTO_CONT.IMPORTE_8 IS 'Importe al 8% IVA';

COMMENT ON COLUMN BIDAIAK.TMP_ASIENTO_CONT.IMPORTE_18 IS 'Importe al 18% de IVA';

COMMENT ON COLUMN BIDAIAK.TMP_ASIENTO_CONT.FECHA_INSERCION IS 'Fecha en la que se inserto';

COMMENT ON COLUMN BIDAIAK.TMP_ASIENTO_CONT.ID_PLANTA IS 'Id de la planta';

COMMENT ON COLUMN BIDAIAK.TMP_ASIENTO_CONT.UNIDAD_ORGANIZATIVA IS 'Nombre de la unidad organizativa a la que pertenece';


CREATE TABLE BIDAIAK.TMP_FAKTURA_EROSKI
(
  BONO             NVARCHAR2(30),
  FACTURA          NVARCHAR2(30)                NOT NULL,
  ALBARAN          NVARCHAR2(30)                NOT NULL,
  FECHASERV        DATE,
  DIAS             NUMBER,
  PRODUCTO         NVARCHAR2(100),
  DESTINO          NVARCHAR2(100),
  PROVEEDOR        NVARCHAR2(100),
  PERSONA          NVARCHAR2(100),
  BASEIG           NUMBER,
  CUOTAG           NUMBER,
  BASEIR           NUMBER,
  CUOTAR           NUMBER,
  BASEEXE          NUMBER,
  REGESP           NUMBER,
  CUOTARE          NUMBER,
  IMPORTE          NUMBER,
  NIVEL1           NVARCHAR2(100),
  NIVEL2           NVARCHAR2(100),
  NIVEL3           NVARCHAR2(100),
  NIVEL4           NVARCHAR2(100),
  ID_USER          NUMBER,
  FECHA_INSERCION  DATE                         NOT NULL,
  ID_PLANTA        NUMBER                       DEFAULT NULL                  NOT NULL,
  ID_VIAJE         NUMBER,
  ID_SABORG        NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE BIDAIAK.TMP_FAKTURA_EROSKI IS 'Tabla donde dejaran los resultados temporalmente antes de insertarlos en la tabla de FAKTURAS_EROSKI';

COMMENT ON COLUMN BIDAIAK.TMP_FAKTURA_EROSKI.BASEIG IS 'IVA 18%';

COMMENT ON COLUMN BIDAIAK.TMP_FAKTURA_EROSKI.BASEIR IS 'IVA 8%';

COMMENT ON COLUMN BIDAIAK.TMP_FAKTURA_EROSKI.BASEEXE IS 'IVA 0%';

COMMENT ON COLUMN BIDAIAK.TMP_FAKTURA_EROSKI.NIVEL2 IS 'Organizador del viaje';

COMMENT ON COLUMN BIDAIAK.TMP_FAKTURA_EROSKI.ID_USER IS 'Id del usuario con el que esta relacionado';

COMMENT ON COLUMN BIDAIAK.TMP_FAKTURA_EROSKI.ID_PLANTA IS 'Id de la planta  a la que pertenece';

COMMENT ON COLUMN BIDAIAK.TMP_FAKTURA_EROSKI.ID_VIAJE IS 'Indica el id viaje si lo ha encontrado. sino null';

COMMENT ON COLUMN BIDAIAK.TMP_FAKTURA_EROSKI.ID_SABORG IS 'Id de Sab del organizador si se encuentra';


CREATE TABLE BIDAIAK.UNIDADES_ORG
(
  ID                   NUMBER                   NOT NULL,
  NOMBRE               VARCHAR2(30 BYTE)        NOT NULL,
  ID_PLANTA            NUMBER                   NOT NULL,
  ID_RESPONSABLE       NUMBER                   NOT NULL,
  REQ_PROYCLI          NUMBER(1)                NOT NULL,
  STRING_CONEXION      VARCHAR2(150 BYTE)       NOT NULL,
  DEPART_IDENTIF       VARCHAR2(2 BYTE)         NOT NULL,
  REQ_CONSIN_PROYECTO  NUMBER(1)                NOT NULL,
  REQ_OF_IMPRODUCTIVA  NUMBER(1)                NOT NULL,
  REQ_OF_VALIDAR       NUMBER(1)                NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE BIDAIAK.UNIDADES_ORG IS 'Guarda las unidades organizativas';

COMMENT ON COLUMN BIDAIAK.UNIDADES_ORG.REQ_OF_VALIDAR IS 'Indica si debera introducir una of a validar';

COMMENT ON COLUMN BIDAIAK.UNIDADES_ORG.ID IS 'ID autonumerico';

COMMENT ON COLUMN BIDAIAK.UNIDADES_ORG.NOMBRE IS 'Nombre de la unidad';

COMMENT ON COLUMN BIDAIAK.UNIDADES_ORG.ID_PLANTA IS 'Id de la planta';

COMMENT ON COLUMN BIDAIAK.UNIDADES_ORG.ID_RESPONSABLE IS 'Id del usuario responsable del area';

COMMENT ON COLUMN BIDAIAK.UNIDADES_ORG.REQ_PROYCLI IS 'Indicara si requiere seleccionar un proyecto y un cliente';

COMMENT ON COLUMN BIDAIAK.UNIDADES_ORG.STRING_CONEXION IS 'String de conexion de la base de datos a la que habra que conectarse';

COMMENT ON COLUMN BIDAIAK.UNIDADES_ORG.DEPART_IDENTIF IS 'Nº identificativos de un departamento para saber a la unidad a la que pertenecen los usuarios';

COMMENT ON COLUMN BIDAIAK.UNIDADES_ORG.REQ_CONSIN_PROYECTO IS 'indica si se mostrara previamente una seleccion de con o sin proyecto';

COMMENT ON COLUMN BIDAIAK.UNIDADES_ORG.REQ_OF_IMPRODUCTIVA IS 'Indica si se debera elegir una of improductiva';


CREATE TABLE BIDAIAK.VIAJES
(
  ID               NUMBER                       NOT NULL,
  DESTINO          VARCHAR2(50 BYTE)            NOT NULL,
  NIVEL            NUMBER                       NOT NULL,
  FECHA_IDA        DATE                         NOT NULL,
  FECHA_VUELTA     DATE                         NOT NULL,
  ID_USER_SOLIC    NUMBER                       NOT NULL,
  FECHA_SOLICITUD  DATE                         NOT NULL,
  ID_UNIDAD_ORG    NUMBER                       NOT NULL,
  ID_PROGRAMA      NUMBER,
  TIPO_VIAJE       NUMBER                       NOT NULL,
  ESTADO           NUMBER                       NOT NULL,
  ID_PLANTA        NUMBER                       NOT NULL,
  DESCRIPCION      VARCHAR2(200 BYTE),
  CONSIN_PROYECTO  NUMBER(1),
  NUM_OF           VARCHAR2(10 BYTE),
  NUM_OP           NUMBER(2)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE BIDAIAK.VIAJES IS 'Se guardan las solciitudes de viaje realizadas';

COMMENT ON COLUMN BIDAIAK.VIAJES.ID IS 'Id del viaje';

COMMENT ON COLUMN BIDAIAK.VIAJES.DESTINO IS 'Destino del viaje';

COMMENT ON COLUMN BIDAIAK.VIAJES.NIVEL IS '1:Nacional,2:Internacional,3:Resto del mundo';

COMMENT ON COLUMN BIDAIAK.VIAJES.FECHA_IDA IS 'Fecha de ida';

COMMENT ON COLUMN BIDAIAK.VIAJES.FECHA_VUELTA IS 'Fecha de vuelta';

COMMENT ON COLUMN BIDAIAK.VIAJES.ID_USER_SOLIC IS 'Id del usuario que ha solicitado el viaje';

COMMENT ON COLUMN BIDAIAK.VIAJES.FECHA_SOLICITUD IS 'Fecha de la solicitud';

COMMENT ON COLUMN BIDAIAK.VIAJES.ID_UNIDAD_ORG IS 'Id de la unidad organizativa';

COMMENT ON COLUMN BIDAIAK.VIAJES.ID_PROGRAMA IS 'Si se elige Troqueleria, es el id del proyecto a partir del cual, se puede sacar tambien el cliente';

COMMENT ON COLUMN BIDAIAK.VIAJES.TIPO_VIAJE IS '1:Programado(hay una solicitud),2:Anticipo (se ha solicitado un anticipo sin solicitud de viaje. Es un viaje ficticio)';

COMMENT ON COLUMN BIDAIAK.VIAJES.ESTADO IS 'Indica el estado de la solicitud. 0:Activa, 1:Cancelada';

COMMENT ON COLUMN BIDAIAK.VIAJES.ID_PLANTA IS 'Id de la planta a la que pertenece';

COMMENT ON COLUMN BIDAIAK.VIAJES.DESCRIPCION IS 'Descripcion del viaje';

COMMENT ON COLUMN BIDAIAK.VIAJES.CONSIN_PROYECTO IS 'Para las unidades organizativas que requieran con/sin proyecto, indicara cual de los dos se ha seleccionado';

COMMENT ON COLUMN BIDAIAK.VIAJES.NUM_OF IS 'Numero de la of. Puede ser tambien una of de brain';

COMMENT ON COLUMN BIDAIAK.VIAJES.NUM_OP IS 'Numero de la op';


CREATE TABLE BIDAIAK.VISAS
(
  ID             NUMBER                         NOT NULL,
  NUM_TARJETA    VARCHAR2(20 BYTE)              NOT NULL,
  ID_USER        NUMBER                         NOT NULL,
  FECHA_ENTREGA  DATE                           NOT NULL,
  OBSOLETA       NUMBER(1)                      NOT NULL,
  ID_PLANTA      NUMBER                         NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE BIDAIAK.VISAS IS 'Se guarda la asociacion de las visas con las personas';

COMMENT ON COLUMN BIDAIAK.VISAS.ID IS 'Id autonumerico';

COMMENT ON COLUMN BIDAIAK.VISAS.NUM_TARJETA IS 'Nº de tarjeta';

COMMENT ON COLUMN BIDAIAK.VISAS.ID_USER IS 'Id del usuario al que pertenece';

COMMENT ON COLUMN BIDAIAK.VISAS.FECHA_ENTREGA IS 'Fecha en la que se le entrego';

COMMENT ON COLUMN BIDAIAK.VISAS.OBSOLETA IS 'Indica si es obsoleta o no';

COMMENT ON COLUMN BIDAIAK.VISAS.ID_PLANTA IS 'Id de la planta';


CREATE UNIQUE INDEX BIDAIAK.ANTICIPOS_ESTADOS_PK ON BIDAIAK.ANTICIPOS_ESTADOS
(ID_ANTICIPO, ESTADO, FECHA)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX BIDAIAK.ANTICIPOS_PK ON BIDAIAK.ANTICIPOS
(ID_VIAJE)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX BIDAIAK.CONCEPTOS_BATZ_PK ON BIDAIAK.CONCEPTOS_BATZ
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX BIDAIAK.CUENTAS_PLANTAS_FILIALES_PK ON BIDAIAK.CUENTAS_PLANTAS_FILIALES
(ID_PLANTA, CUENTA)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX BIDAIAK.IMPORTACION_VISAS_PK ON BIDAIAK.IMPORTACION_DOCS
(FECHA)
LOGGING
NOPARALLEL;


CREATE INDEX BIDAIAK.MOVIMIENTOS_VISA_INDEX1 ON BIDAIAK.MOVIMIENTOS_VISA
(TARJETA)
LOGGING
NOPARALLEL;


CREATE INDEX BIDAIAK.MOVIMIENTOS_VISA_INDEX2 ON BIDAIAK.MOVIMIENTOS_VISA
(ID_VIAJE)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX BIDAIAK.MOVIMIENTOS_VISA_PK ON BIDAIAK.MOVIMIENTOS_VISA
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX BIDAIAK.PERFILES_PK ON BIDAIAK.PERFILES
(ID_USER, ID_PLANTA)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX BIDAIAK.RELACION_CONCEPTOS_PK ON BIDAIAK.RELACION_CONCEPTOS
(CONCEPTO_FICHERO, ID_CONCEPTO_BATZ)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX BIDAIAK.SERV_AGENCIA_PK ON BIDAIAK.SERV_AGENCIA
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX BIDAIAK.SOLICITUD_AGENCIA_PK ON BIDAIAK.SOLICITUD_AGENCIA
(ID_VIAJE)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX BIDAIAK.TIPO_GASTO_PK ON BIDAIAK.TIPO_GASTOS
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX BIDAIAK.UNIDADES_ORG_PK ON BIDAIAK.UNIDADES_ORG
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX BIDAIAK.VIAJE_PK ON BIDAIAK.VIAJES
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX BIDAIAK.VISAS_PK ON BIDAIAK.VISAS
(ID)
LOGGING
NOPARALLEL;


CREATE OR REPLACE TRIGGER BIDAIAK."TR_TIPO_GASTOS" 
   BEFORE INSERT
   ON BIDAIAK.TIPO_GASTOS    REFERENCING NEW AS New OLD AS Old
   FOR EACH ROW
BEGIN
   SELECT SEQ_TIPO_GASTOS.NEXTVAL INTO :NEW.id FROM DUAL;
END TR_TIPO_GASTOS;
/
SHOW ERRORS;


CREATE OR REPLACE TRIGGER BIDAIAK."TR_VISAS" 
   BEFORE INSERT
   ON BIDAIAK.VISAS    REFERENCING NEW AS New OLD AS Old
   FOR EACH ROW
BEGIN
   SELECT SEQ_VISAS.NEXTVAL INTO :NEW.id FROM DUAL;
END TR_VISAS;
/
SHOW ERRORS;


CREATE OR REPLACE TRIGGER BIDAIAK."TR_VIAJES" 
   BEFORE INSERT
   ON BIDAIAK.VIAJES    REFERENCING NEW AS New OLD AS Old
   FOR EACH ROW
BEGIN
   SELECT SEQ_VIAJES.NEXTVAL INTO :NEW.id FROM DUAL;
END TR_VIAJES;
/
SHOW ERRORS;


CREATE OR REPLACE TRIGGER BIDAIAK."TR_UNIDADES_ORG" 
   BEFORE INSERT
   ON BIDAIAK.UNIDADES_ORG    REFERENCING NEW AS New OLD AS Old
   FOR EACH ROW
BEGIN
   SELECT SEQ_UNIDADES_ORG.NEXTVAL INTO :NEW.id FROM DUAL;
END TR_UNIDADES_ORG;
/
SHOW ERRORS;


CREATE OR REPLACE TRIGGER BIDAIAK."TR_SERV_AGENCIA" 
   BEFORE INSERT
   ON BIDAIAK.SERV_AGENCIA    REFERENCING NEW AS New OLD AS Old
   FOR EACH ROW
BEGIN
   SELECT SEQ_SERV_AGENCIA.NEXTVAL INTO :NEW.id FROM DUAL;
END TR_SERV_AGENCIA;
/
SHOW ERRORS;


CREATE OR REPLACE TRIGGER BIDAIAK."TR_MOV_VISA" 
   BEFORE INSERT
   ON BIDAIAK.MOVIMIENTOS_VISA    REFERENCING NEW AS New OLD AS Old
   FOR EACH ROW
BEGIN
   SELECT SEQ_MOV_VISA.NEXTVAL INTO :NEW.id FROM DUAL;
END TR_MOV_VISA;
/
SHOW ERRORS;


CREATE OR REPLACE TRIGGER BIDAIAK."TR_CONCEPTOS_BATZ" 
   BEFORE INSERT
   ON BIDAIAK.CONCEPTOS_BATZ    REFERENCING NEW AS New OLD AS Old
   FOR EACH ROW
BEGIN
   SELECT SEQ_CONCEPTOS_BATZ.NEXTVAL INTO :NEW.id FROM DUAL;
END TR_CONCEPTOS_BATZ;
/
SHOW ERRORS;


CREATE TABLE BIDAIAK.HOJA_GASTOS
(
  ID_VIAJE        NUMBER,
  ID_USER         NUMBER                        NOT NULL,
  ESTADO          NUMBER                        NOT NULL,
  FECHA_CREACION  DATE                          NOT NULL,
  ID              NUMBER                        NOT NULL,
  ID_VALIDADOR    NUMBER,
  FECHA_ENVIO     DATE,
  FECHA_DESDE     DATE,
  FECHA_HASTA     DATE,
  ID_SIN_VIAJES   NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE BIDAIAK.HOJA_GASTOS IS 'Cabecera de las hojas de gastos asociadas al viaje';

COMMENT ON COLUMN BIDAIAK.HOJA_GASTOS.ID_VIAJE IS 'Id del viaje al que esta asociado';

COMMENT ON COLUMN BIDAIAK.HOJA_GASTOS.ID_USER IS 'Id del usuario que ha rellenado la hoja';

COMMENT ON COLUMN BIDAIAK.HOJA_GASTOS.ESTADO IS 'Posible estado de la hoja. 1:Rellenada,2:Enviada,3:Validada,4:No validada;5:Liquidada';

COMMENT ON COLUMN BIDAIAK.HOJA_GASTOS.FECHA_CREACION IS 'Fecha de creacion de la pagina';

COMMENT ON COLUMN BIDAIAK.HOJA_GASTOS.ID IS 'Id autonumerico';

COMMENT ON COLUMN BIDAIAK.HOJA_GASTOS.ID_VALIDADOR IS 'Id del usuario validador';

COMMENT ON COLUMN BIDAIAK.HOJA_GASTOS.FECHA_ENVIO IS 'Fecha del envio de la hoja';

COMMENT ON COLUMN BIDAIAK.HOJA_GASTOS.FECHA_DESDE IS 'Si es una hoja sin viaje, sera la fecha desde la que tendra efecto';

COMMENT ON COLUMN BIDAIAK.HOJA_GASTOS.FECHA_HASTA IS 'Si es una hoja sin viaje, sera la fecha hasta la que tendra efecto';

COMMENT ON COLUMN BIDAIAK.HOJA_GASTOS.ID_SIN_VIAJES IS 'Si hoja sin viaje, autonumerico con trigger';


CREATE TABLE BIDAIAK.INTEGRANTES
(
  ID_VIAJE    NUMBER,
  ID_USUARIO  NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE BIDAIAK.INTEGRANTES IS 'Integrantes del viaje';

COMMENT ON COLUMN BIDAIAK.INTEGRANTES.ID_VIAJE IS 'Id del viaje';

COMMENT ON COLUMN BIDAIAK.INTEGRANTES.ID_USUARIO IS 'Id del usuario';


CREATE TABLE BIDAIAK.LINEAS_AGENCIA
(
  ID            NUMBER                          NOT NULL,
  ID_SOLICITUD  NUMBER                          NOT NULL,
  ID_SERV_AGEN  NUMBER,
  COSTE         NUMBER(8,2)                     NOT NULL,
  COMENTARIO    VARCHAR2(4000 BYTE),
  TIPO          NUMBER(1)                       NOT NULL,
  ID_MONEDA     NUMBER                          NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE BIDAIAK.LINEAS_AGENCIA IS 'Lineas de los servicios de agencia solicitados';

COMMENT ON COLUMN BIDAIAK.LINEAS_AGENCIA.ID IS 'Id autonumerico';

COMMENT ON COLUMN BIDAIAK.LINEAS_AGENCIA.ID_SOLICITUD IS 'Id de la solicitud (cabecera)';

COMMENT ON COLUMN BIDAIAK.LINEAS_AGENCIA.ID_SERV_AGEN IS 'Id del servicio de la agencia solicitado. Puede ser null sino es de tipo 1';

COMMENT ON COLUMN BIDAIAK.LINEAS_AGENCIA.COSTE IS 'Coste del servicio';

COMMENT ON COLUMN BIDAIAK.LINEAS_AGENCIA.COMENTARIO IS 'Comentario puesto por el de la agencia';

COMMENT ON COLUMN BIDAIAK.LINEAS_AGENCIA.TIPO IS 'Indicara de que tipo es la linea. 1:De servicios (hotel, avion,...), 2:Otras opciones,3: Otros gastos';

COMMENT ON COLUMN BIDAIAK.LINEAS_AGENCIA.ID_MONEDA IS 'Id de la moneda de la agencia. En Igorre seran euros';


CREATE TABLE BIDAIAK.LINEAS_HOJA_GASTOS
(
  ID                NUMBER                      NOT NULL,
  ID_HOJA           NUMBER                      NOT NULL,
  ID_MONEDA         NUMBER                      NOT NULL,
  CANTIDAD          NUMBER(8,2)                 NOT NULL,
  FECHA             DATE                        NOT NULL,
  ID_TIPO_GASTO     NUMBER                      NOT NULL,
  CONCEPTO          VARCHAR2(75 BYTE),
  LUGAR_ORIGEN      VARCHAR2(75 BYTE),
  LUGAR_DESTINO     VARCHAR2(75 BYTE),
  KM                NUMBER(8,2),
  ID_USER           NUMBER,
  ID_CONCEPTO_BATZ  NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE BIDAIAK.LINEAS_HOJA_GASTOS IS 'Lineas de la hoja de gastos';

COMMENT ON COLUMN BIDAIAK.LINEAS_HOJA_GASTOS.ID IS 'Id autonumerico';

COMMENT ON COLUMN BIDAIAK.LINEAS_HOJA_GASTOS.ID_HOJA IS 'Id de la hoja de gastos cabecera';

COMMENT ON COLUMN BIDAIAK.LINEAS_HOJA_GASTOS.ID_MONEDA IS 'Moneda de la linea';

COMMENT ON COLUMN BIDAIAK.LINEAS_HOJA_GASTOS.CANTIDAD IS 'Cantidad de la linea';

COMMENT ON COLUMN BIDAIAK.LINEAS_HOJA_GASTOS.FECHA IS 'Fecha del concepto de la linea';

COMMENT ON COLUMN BIDAIAK.LINEAS_HOJA_GASTOS.ID_TIPO_GASTO IS 'Tipo de gasto. 1:Recibo,2:Sin recibo,3:Kilometraje';

COMMENT ON COLUMN BIDAIAK.LINEAS_HOJA_GASTOS.CONCEPTO IS 'Concepto de la linea. Este texto solo sera informado cuando el concepto seleccionado lo requiera';

COMMENT ON COLUMN BIDAIAK.LINEAS_HOJA_GASTOS.LUGAR_ORIGEN IS 'Lugar de origen cuando el gasto es de kilometraje';

COMMENT ON COLUMN BIDAIAK.LINEAS_HOJA_GASTOS.LUGAR_DESTINO IS 'Lugar de destino cuando el gasto es de kilometraje';

COMMENT ON COLUMN BIDAIAK.LINEAS_HOJA_GASTOS.KM IS 'Numero de kilometros recorridos';

COMMENT ON COLUMN BIDAIAK.LINEAS_HOJA_GASTOS.ID_USER IS 'Id del usuario de la linea';

COMMENT ON COLUMN BIDAIAK.LINEAS_HOJA_GASTOS.ID_CONCEPTO_BATZ IS 'Id del concepto seleccionado';


CREATE TABLE BIDAIAK.MOVIMIENTOS
(
  ID             NUMBER                         NOT NULL,
  ID_ANTICIPO    NUMBER                         NOT NULL,
  ID_MONEDA      NUMBER                         NOT NULL,
  CANTIDAD       NUMBER(8,2)                    NOT NULL,
  FECHA          DATE                           NOT NULL,
  ID_USER_ORIG   NUMBER                         NOT NULL,
  ID_USER_DEST   NUMBER,
  ID_VIAJE_ORIG  NUMBER,
  ID_VIAJE_DEST  NUMBER,
  COMENTARIO     VARCHAR2(75 BYTE),
  TIPO_MOV       NUMBER                         NOT NULL,
  OBSOLETO       NUMBER(1)                      NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE BIDAIAK.MOVIMIENTOS IS 'Se guardan todos los movimientos realizados, solicitudes, devoluciones, entregas, transferencias, etc..';

COMMENT ON COLUMN BIDAIAK.MOVIMIENTOS.ID IS 'Id autonumerico';

COMMENT ON COLUMN BIDAIAK.MOVIMIENTOS.ID_ANTICIPO IS 'Id del anticipo';

COMMENT ON COLUMN BIDAIAK.MOVIMIENTOS.ID_MONEDA IS 'Moneda del movimiento';

COMMENT ON COLUMN BIDAIAK.MOVIMIENTOS.CANTIDAD IS 'Cantidad del movimiento';

COMMENT ON COLUMN BIDAIAK.MOVIMIENTOS.FECHA IS 'Fecha';

COMMENT ON COLUMN BIDAIAK.MOVIMIENTOS.ID_USER_ORIG IS 'Id del usuario origen, el que realiza la accion';

COMMENT ON COLUMN BIDAIAK.MOVIMIENTOS.ID_USER_DEST IS 'En las transferencias, sera el usuario al que se le da el dinero';

COMMENT ON COLUMN BIDAIAK.MOVIMIENTOS.ID_VIAJE_ORIG IS 'En las transferencias el viaje de origen';

COMMENT ON COLUMN BIDAIAK.MOVIMIENTOS.ID_VIAJE_DEST IS 'En las transferencias el viaje destino';

COMMENT ON COLUMN BIDAIAK.MOVIMIENTOS.COMENTARIO IS 'Posible comentario';

COMMENT ON COLUMN BIDAIAK.MOVIMIENTOS.TIPO_MOV IS 'Indica el tipo de movimiento=>1:solicitud,2:entrega,3:devolucion,4:transferencia,5:diferencia de cambio';


CREATE TABLE BIDAIAK.OFS_IMPRODUCTIVAS
(
  NUM_OF         NUMBER(4)                      NOT NULL,
  NUM_OP         NUMBER(2)                      NOT NULL,
  DESCRIPCION    VARCHAR2(50 BYTE)              NOT NULL,
  ID_UNIDAD_ORG  NUMBER                         NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN BIDAIAK.OFS_IMPRODUCTIVAS.NUM_OF IS 'OF';

COMMENT ON COLUMN BIDAIAK.OFS_IMPRODUCTIVAS.NUM_OP IS 'OP';

COMMENT ON COLUMN BIDAIAK.OFS_IMPRODUCTIVAS.DESCRIPCION IS 'Descripcion de la of';

COMMENT ON COLUMN BIDAIAK.OFS_IMPRODUCTIVAS.ID_UNIDAD_ORG IS 'Id unidad organizativa';


CREATE TABLE BIDAIAK.SOLAGEN_ALBARANES
(
  ID_SOLICITUD  NUMBER                          NOT NULL,
  ALBARAN       VARCHAR2(20 BYTE)               NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE BIDAIAK.SOLAGEN_ALBARANES IS 'Se guardan los distintos albaranes que puede tener una solicitud de agencia';

COMMENT ON COLUMN BIDAIAK.SOLAGEN_ALBARANES.ID_SOLICITUD IS 'Id del viaje que corresponde con el id de la solicitud de agencia';

COMMENT ON COLUMN BIDAIAK.SOLAGEN_ALBARANES.ALBARAN IS 'Numero de Albaran';


CREATE UNIQUE INDEX BIDAIAK.HOJA_GASTOS_PK ON BIDAIAK.HOJA_GASTOS
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX BIDAIAK.INTEGRANTES_PK ON BIDAIAK.INTEGRANTES
(ID_VIAJE, ID_USUARIO)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX BIDAIAK.LINEAS_AGENCIA_PK ON BIDAIAK.LINEAS_AGENCIA
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX BIDAIAK.LINEAS_HOJA_GASTOS_PK ON BIDAIAK.LINEAS_HOJA_GASTOS
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX BIDAIAK.MOVIMIENTOS_PK ON BIDAIAK.MOVIMIENTOS
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX BIDAIAK.OFS_IMPRODUCTIVAS_PK ON BIDAIAK.OFS_IMPRODUCTIVAS
(NUM_OF, NUM_OP, ID_UNIDAD_ORG)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX BIDAIAK.OFS_IMPRODUCTIVAS_PK1 ON BIDAIAK.OFS_IMPRODUCTIVAS
(NUM_OF, NUM_OP)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX BIDAIAK.SOLAGEN_ALBARANES_PK ON BIDAIAK.SOLAGEN_ALBARANES
(ID_SOLICITUD, ALBARAN)
LOGGING
NOPARALLEL;


CREATE OR REPLACE TRIGGER BIDAIAK."TR_LINEAS_HOJA_GASTOS" 
   BEFORE INSERT
   ON BIDAIAK.LINEAS_HOJA_GASTOS    REFERENCING NEW AS New OLD AS Old
   FOR EACH ROW
BEGIN
   SELECT SEQ_LINEAS_HOJA_GASTOS.NEXTVAL INTO :NEW.id FROM DUAL;
END TR_LINEAS_HOJAS_GASTOS;
/
SHOW ERRORS;


CREATE OR REPLACE TRIGGER BIDAIAK."TR_HOJAS_GASTOS"
   BEFORE INSERT
   ON BIDAIAK.HOJA_GASTOS    REFERENCING NEW AS New OLD AS Old
   FOR EACH ROW
BEGIN
   SELECT SEQ_HOJAS_GASTOS.NEXTVAL INTO :NEW.id FROM DUAL;

   IF :NEW.id_viaje IS NULL
   THEN
      SELECT seq_hg_sin_viaje.NEXTVAL INTO :NEW.id_sin_viajes FROM DUAL;
   END IF;
END TR_HOJAS_GASTOS;
/
SHOW ERRORS;


CREATE OR REPLACE TRIGGER BIDAIAK."TR_LINEAS_AGENCIA" 
   BEFORE INSERT
   ON BIDAIAK.LINEAS_AGENCIA    REFERENCING NEW AS New OLD AS Old
   FOR EACH ROW
BEGIN
   SELECT SEQ_LINEAS_AGENCIA.NEXTVAL INTO :NEW.id FROM DUAL;
END TR_LINEAS_AGENCIA;
/
SHOW ERRORS;


CREATE OR REPLACE TRIGGER BIDAIAK."TR_MOVIMIENTOS" 
   BEFORE INSERT
   ON BIDAIAK.MOVIMIENTOS    REFERENCING NEW AS New OLD AS Old
   FOR EACH ROW
BEGIN
   SELECT SEQ_MOVIMIENTOS.NEXTVAL INTO :NEW.id FROM DUAL;
END TR_MOVIMIENTOS;
/
SHOW ERRORS;


ALTER TABLE BIDAIAK.ANTICIPOS ADD (
  CONSTRAINT ANTICIPOS_PK
 PRIMARY KEY
 (ID_VIAJE));

ALTER TABLE BIDAIAK.ANTICIPOS_ESTADOS ADD (
  CONSTRAINT ANTICIPOS_ESTADOS_PK
 PRIMARY KEY
 (ID_ANTICIPO, ESTADO, FECHA));

ALTER TABLE BIDAIAK.CONCEPTOS_BATZ ADD (
  CONSTRAINT CONCEPTOS_BATZ_PK
 PRIMARY KEY
 (ID));

ALTER TABLE BIDAIAK.CUENTAS_PLANTAS_FILIALES ADD (
  CONSTRAINT CUENTAS_PLANTAS_FILIALES_PK
 PRIMARY KEY
 (ID_PLANTA, CUENTA));

ALTER TABLE BIDAIAK.IMPORTACION_DOCS ADD (
  CONSTRAINT IMPORTACION_VISAS_PK
 PRIMARY KEY
 (FECHA));

ALTER TABLE BIDAIAK.MOVIMIENTOS_VISA ADD (
  CONSTRAINT MOVIMIENTOS_VISA_PK
 PRIMARY KEY
 (ID));

ALTER TABLE BIDAIAK.PERFILES ADD (
  CONSTRAINT PERFILES_PK
 PRIMARY KEY
 (ID_USER, ID_PLANTA));

ALTER TABLE BIDAIAK.RELACION_CONCEPTOS ADD (
  CONSTRAINT RELACION_CONCEPTOS_PK
 PRIMARY KEY
 (CONCEPTO_FICHERO, ID_CONCEPTO_BATZ));

ALTER TABLE BIDAIAK.SERV_AGENCIA ADD (
  CONSTRAINT SERV_AGENCIA_PK
 PRIMARY KEY
 (ID));

ALTER TABLE BIDAIAK.SOLICITUD_AGENCIA ADD (
  CONSTRAINT SOLICITUD_AGENCIA_PK
 PRIMARY KEY
 (ID_VIAJE));

ALTER TABLE BIDAIAK.TIPO_GASTOS ADD (
  CONSTRAINT TIPO_GASTOS_PK
 PRIMARY KEY
 (ID));

ALTER TABLE BIDAIAK.UNIDADES_ORG ADD (
  CONSTRAINT UNIDADES_ORG_PK
 PRIMARY KEY
 (ID));

ALTER TABLE BIDAIAK.VIAJES ADD (
  CONSTRAINT VIAJES_PK
 PRIMARY KEY
 (ID));

ALTER TABLE BIDAIAK.VISAS ADD (
  CONSTRAINT VISAS_PK
 PRIMARY KEY
 (ID));

ALTER TABLE BIDAIAK.HOJA_GASTOS ADD (
  CONSTRAINT HOJA_GASTOS_PK
 PRIMARY KEY
 (ID));

ALTER TABLE BIDAIAK.INTEGRANTES ADD (
  CONSTRAINT INTEGRANTES_PK
 PRIMARY KEY
 (ID_VIAJE, ID_USUARIO));

ALTER TABLE BIDAIAK.LINEAS_AGENCIA ADD (
  CONSTRAINT LINEAS_AGENCIA_PK
 PRIMARY KEY
 (ID));

ALTER TABLE BIDAIAK.LINEAS_HOJA_GASTOS ADD (
  CONSTRAINT LINEAS_HOJA_GASTOS_PK
 PRIMARY KEY
 (ID));

ALTER TABLE BIDAIAK.MOVIMIENTOS ADD (
  CONSTRAINT MOVIMIENTOS_PK
 PRIMARY KEY
 (ID));

ALTER TABLE BIDAIAK.OFS_IMPRODUCTIVAS ADD (
  CONSTRAINT OFS_IMPRODUCTIVAS_PK1
 PRIMARY KEY
 (NUM_OF, NUM_OP));

ALTER TABLE BIDAIAK.SOLAGEN_ALBARANES ADD (
  CONSTRAINT SOLAGEN_ALBARANES_PK
 PRIMARY KEY
 (ID_SOLICITUD, ALBARAN));

ALTER TABLE BIDAIAK.ANTICIPOS ADD (
  CONSTRAINT ANTICIPOS_USUARIOS_FK1 
 FOREIGN KEY (ID_RESP_LIQUIDACION) 
 REFERENCES SAB.USUARIOS (ID));

ALTER TABLE BIDAIAK.CUENTAS_PLANTAS_FILIALES ADD (
  CONSTRAINT CUENTAS_PLANTAS_FILIALES__FK1 
 FOREIGN KEY (ID_PLANTA) 
 REFERENCES SAB.PLANTAS (ID));

ALTER TABLE BIDAIAK.DEPARTAMENTOS ADD (
  CONSTRAINT DEPARTAMENTOS_PLANTAS_FK1 
 FOREIGN KEY (ID_PLANTA) 
 REFERENCES SAB.PLANTAS (ID));

ALTER TABLE BIDAIAK.FAKTURA_EROSKI ADD (
  CONSTRAINT FAKTURA_EROSKI_PLANTAS_FK1 
 FOREIGN KEY (ID_PLANTA) 
 REFERENCES SAB.PLANTAS (ID),
  CONSTRAINT FAKTURA_EROSKI_USUARIOS_FK1 
 FOREIGN KEY (ID_USER) 
 REFERENCES SAB.USUARIOS (ID));

ALTER TABLE BIDAIAK.PERFILES ADD (
  CONSTRAINT PERFILES_PLANTAS_FK1 
 FOREIGN KEY (ID_PLANTA) 
 REFERENCES SAB.PLANTAS (ID),
  CONSTRAINT PERFILES_USUARIOS_FK1 
 FOREIGN KEY (ID_USER) 
 REFERENCES SAB.USUARIOS (ID));

ALTER TABLE BIDAIAK.RELACION_CONCEPTOS ADD (
  CONSTRAINT RELACION_CONCEPTOS_CONCEP_FK1 
 FOREIGN KEY (ID_CONCEPTO_BATZ) 
 REFERENCES BIDAIAK.CONCEPTOS_BATZ (ID));

ALTER TABLE BIDAIAK.SERV_AGENCIA ADD (
  CONSTRAINT SERV_AGENCIA_PLANTAS_FK1 
 FOREIGN KEY (ID_PLANTA) 
 REFERENCES SAB.PLANTAS (ID));

ALTER TABLE BIDAIAK.TIPO_GASTOS ADD (
  CONSTRAINT TIPO_GASTOS_PLANTAS_FK1 
 FOREIGN KEY (ID_PLANTA) 
 REFERENCES SAB.PLANTAS (ID));

ALTER TABLE BIDAIAK.TMP_FAKTURA_EROSKI ADD (
  CONSTRAINT TMP_FAKTURA_EROSKI__FK1 
 FOREIGN KEY (ID_USER) 
 REFERENCES SAB.USUARIOS (ID),
  CONSTRAINT TMP_FAKTURA_EROSKI_FK2 
 FOREIGN KEY (ID_PLANTA) 
 REFERENCES SAB.PLANTAS (ID));

ALTER TABLE BIDAIAK.UNIDADES_ORG ADD (
  CONSTRAINT UNIDADES_ORG_PLANTAS_FK1 
 FOREIGN KEY (ID_PLANTA) 
 REFERENCES SAB.PLANTAS (ID),
  CONSTRAINT UNIDADES_ORG_USUARIOS_FK1 
 FOREIGN KEY (ID_RESPONSABLE) 
 REFERENCES SAB.USUARIOS (ID));

ALTER TABLE BIDAIAK.VIAJES ADD (
  CONSTRAINT VIAJES_PLANTAS_FK1 
 FOREIGN KEY (ID_PLANTA) 
 REFERENCES SAB.PLANTAS (ID),
  CONSTRAINT VIAJES_USUARIOS_FK1 
 FOREIGN KEY (ID_USER_SOLIC) 
 REFERENCES SAB.USUARIOS (ID));

ALTER TABLE BIDAIAK.VISAS ADD (
  CONSTRAINT VISAS_PLANTAS_FK1 
 FOREIGN KEY (ID_PLANTA) 
 REFERENCES SAB.PLANTAS (ID),
  CONSTRAINT VISAS_USUARIOS_FK1 
 FOREIGN KEY (ID_USER) 
 REFERENCES SAB.USUARIOS (ID));

ALTER TABLE BIDAIAK.HOJA_GASTOS ADD (
  CONSTRAINT HOJA_GASTOS_USUARIOS_FK1 
 FOREIGN KEY (ID_USER) 
 REFERENCES SAB.USUARIOS (ID),
  CONSTRAINT HOJA_GASTOS_USUARIOS_FK2 
 FOREIGN KEY (ID_VALIDADOR) 
 REFERENCES SAB.USUARIOS (ID),
  CONSTRAINT HOJA_GASTOS_VIAJES_FK1 
 FOREIGN KEY (ID_VIAJE) 
 REFERENCES BIDAIAK.VIAJES (ID));

ALTER TABLE BIDAIAK.INTEGRANTES ADD (
  CONSTRAINT INTEGRANTES_USUARIOS_FK1 
 FOREIGN KEY (ID_USUARIO) 
 REFERENCES SAB.USUARIOS (ID),
  CONSTRAINT INTEGRANTES_VIAJES_FK1 
 FOREIGN KEY (ID_VIAJE) 
 REFERENCES BIDAIAK.VIAJES (ID));

ALTER TABLE BIDAIAK.LINEAS_AGENCIA ADD (
  CONSTRAINT LINEAS_AGENCIA_SERV_AGENC_FK1 
 FOREIGN KEY (ID_SERV_AGEN) 
 REFERENCES BIDAIAK.SERV_AGENCIA (ID));

ALTER TABLE BIDAIAK.LINEAS_HOJA_GASTOS ADD (
  CONSTRAINT LINEAS_HOJA_GASTOS_CONCEP_FK1 
 FOREIGN KEY (ID_CONCEPTO_BATZ) 
 REFERENCES BIDAIAK.CONCEPTOS_BATZ (ID),
  CONSTRAINT LINEAS_HOJA_GASTOS_HOJA_G_FK1 
 FOREIGN KEY (ID_HOJA) 
 REFERENCES BIDAIAK.HOJA_GASTOS (ID),
  CONSTRAINT LINEAS_HOJA_GASTOS_USUARI_FK1 
 FOREIGN KEY (ID_USER) 
 REFERENCES SAB.USUARIOS (ID));

ALTER TABLE BIDAIAK.MOVIMIENTOS ADD (
  CONSTRAINT MOVIMIENTOS_ANTICIPOS_FK1 
 FOREIGN KEY (ID_ANTICIPO) 
 REFERENCES BIDAIAK.ANTICIPOS (ID_VIAJE),
  CONSTRAINT MOVIMIENTOS_USUARIOS_FK1 
 FOREIGN KEY (ID_USER_ORIG) 
 REFERENCES SAB.USUARIOS (ID),
  CONSTRAINT MOVIMIENTOS_USUARIOS_FK2 
 FOREIGN KEY (ID_USER_DEST) 
 REFERENCES SAB.USUARIOS (ID),
  CONSTRAINT MOVIMIENTOS_VIAJES_FK1 
 FOREIGN KEY (ID_VIAJE_ORIG) 
 REFERENCES BIDAIAK.VIAJES (ID),
  CONSTRAINT MOVIMIENTOS_VIAJES_FK2 
 FOREIGN KEY (ID_VIAJE_DEST) 
 REFERENCES BIDAIAK.VIAJES (ID));

ALTER TABLE BIDAIAK.OFS_IMPRODUCTIVAS ADD (
  CONSTRAINT OFS_IMPRODUCTIVAS_UNIDADE_FK1 
 FOREIGN KEY (ID_UNIDAD_ORG) 
 REFERENCES BIDAIAK.UNIDADES_ORG (ID));

ALTER TABLE BIDAIAK.SOLAGEN_ALBARANES ADD (
  CONSTRAINT SOLAGEN_ALBARANES_SOLICIT_FK1 
 FOREIGN KEY (ID_SOLICITUD) 
 REFERENCES BIDAIAK.SOLICITUD_AGENCIA (ID_VIAJE));