CREATE TABLE "BIDAIAK"."EJECUCION_FACTURA_AGENCIA"
  (
    "FECHA" DATE NOT NULL ENABLE,
    "USUARIO" VARCHAR2(30 BYTE) NOT NULL ENABLE,
    "PASO"    NUMBER NOT NULL ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "BIDAIAK" ;
COMMENT ON COLUMN "BIDAIAK"."EJECUCION_FACTURA_AGENCIA"."FECHA"
IS
  'Fecha y hora de la ejecucion';
  COMMENT ON COLUMN "BIDAIAK"."EJECUCION_FACTURA_AGENCIA"."USUARIO"
IS
  'Usuario que esta ejecutando el proceso';
  COMMENT ON COLUMN "BIDAIAK"."EJECUCION_FACTURA_AGENCIA"."PASO"
IS
  'Nº del paso de la ejecucion en la que se quedo. 3->Resumen,4->PreAsiento,5->Finalizacion(antes de finalizar)';