CREATE TABLE "BIDAIAK"."CAB_FAKTURA_EROSKI"
  (
    "DOCBATZ" NUMBER(6,0) NOT NULL ENABLE,
    "FECHACON" DATE NOT NULL ENABLE,
    "FECHAEMI" DATE NOT NULL ENABLE,
    "FECHAVENCI" DATE NOT NULL ENABLE,
    "NFACTURA"  VARCHAR2(20 BYTE) NOT NULL ENABLE,
    "ID_PLANTA" NUMBER NOT NULL ENABLE,
    "FECHAINSER" DATE NOT NULL ENABLE,
    CONSTRAINT "CAB_FAKTURA_EROSKI_PK" PRIMARY KEY ("NFACTURA", "ID_PLANTA") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "BIDAIAK" ENABLE,
    CONSTRAINT "CAB_FAKTURA_EROSKI_PLANTA_FK1" FOREIGN KEY ("ID_PLANTA") REFERENCES "SAB"."PLANTAS" ("ID") ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "BIDAIAK" ;
COMMENT ON COLUMN "BIDAIAK"."CAB_FAKTURA_EROSKI"."DOCBATZ"
IS
  'Documento Batz';
  COMMENT ON COLUMN "BIDAIAK"."CAB_FAKTURA_EROSKI"."FECHACON"
IS
  'Fecha contabilizacion';
  COMMENT ON COLUMN "BIDAIAK"."CAB_FAKTURA_EROSKI"."FECHAEMI"
IS
  'Fecha de emision';
  COMMENT ON COLUMN "BIDAIAK"."CAB_FAKTURA_EROSKI"."FECHAVENCI"
IS
  'Fecha de vencimiento';
  COMMENT ON COLUMN "BIDAIAK"."CAB_FAKTURA_EROSKI"."NFACTURA"
IS
  'Nº de factura';
  COMMENT ON COLUMN "BIDAIAK"."CAB_FAKTURA_EROSKI"."ID_PLANTA"
IS
  'Id de la planta';
  COMMENT ON COLUMN "BIDAIAK"."CAB_FAKTURA_EROSKI"."FECHAINSER"
IS
  'Fecha de insercion';
  COMMENT ON TABLE "BIDAIAK"."CAB_FAKTURA_EROSKI"
IS
  'Se guardaran datos que seran necesarios para realizar el asiento final en las facturas de eroski';