CREATE TABLE "BIDAIAK"."PARAMETROS"
  (
    "PRECIOKM"             NUMBER,
    "CODPROV_AGENCIA"      VARCHAR2(20 BYTE),
    "ID_PLANTA"            NUMBER NOT NULL ENABLE,
    "CADUCIDAD_VIAJE"      NUMBER,
    "DIAS_SOLICITAR_ANTIC" NUMBER,
    CONSTRAINT "PARAMETROS_PLANTAS_FK1" FOREIGN KEY ("ID_PLANTA") REFERENCES "SAB"."PLANTAS" ("ID") ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "BIDAIAK" ;
COMMENT ON COLUMN "BIDAIAK"."PARAMETROS"."PRECIOKM"
IS
  'Precio que va a tener el km';
  COMMENT ON COLUMN "BIDAIAK"."PARAMETROS"."CODPROV_AGENCIA"
IS
  'Codigo de proveedor de la agencia de viajes';
  COMMENT ON COLUMN "BIDAIAK"."PARAMETROS"."ID_PLANTA"
IS
  'Id de la planta a la que pertenece';
  COMMENT ON COLUMN "BIDAIAK"."PARAMETROS"."CADUCIDAD_VIAJE"
IS
  'Indica el nº de dias que deberan pasar para que un viaje se considere caducado';
  COMMENT ON COLUMN "BIDAIAK"."PARAMETROS"."DIAS_SOLICITAR_ANTIC"
IS
  'Dias minimos para solicitar un anticipo';