DECLARE @STARTDATE DATE = '2018-01-01' -- ESTO SE EJECUTARÁ EL DÍA 9 DE CADA MES (POR EJ)
	-- IDPLANTA = 1 (IGORRE) ESTÁ 'HARDCODEADO', POR AHORA SÓLO IMPLEMENTAMOS ESTA PLANTA

WHILE @STARTDATE < CONVERT(date, GETDATE())
BEGIN

	DECLARE @STARTINGYEAR1 INT, @STARTINGYEAR2 INT, @STARTINGMONTH1 INT, @STARTINGMONTH2 INT, @ENDINGYEAR INT, @ENDINGMONTH INT
	SET @STARTINGYEAR1 = YEAR(DATEADD(MONTH, -12, @STARTDATE)) -- cálculo anual
	SET @STARTINGMONTH1 = MONTH(DATEADD(MONTH, -12, @STARTDATE)) -- cálculo anual
	SET @STARTINGYEAR2 = YEAR(DATEADD(MONTH, -6, @STARTDATE)) -- cálculo semestral
	SET @STARTINGMONTH2 = MONTH(DATEADD(MONTH, -6, @STARTDATE)) -- cálculo semestral
	SET @ENDINGYEAR = YEAR(DATEADD(MONTH, -1, @STARTDATE)) -- a mes vencido
	SET @ENDINGMONTH = MONTH(DATEADD(MONTH, -1, @STARTDATE)) -- a mes vencido
	DECLARE @SUMAANUALPARAFECHA INT
	DECLARE @SUMASEMESTRALPARAFECHA INT

		 SELECT @SUMAANUALPARAFECHA =  SUM([CANTIDAD REAL]) 
		 FROM [supply].[dbo].[VENTAS_CSV]
		 WHERE EMP=1
		 AND (ANNO > @STARTINGYEAR1 OR (ANNO = @STARTINGYEAR1 AND MES >= @STARTINGMONTH1))
		 AND (ANNO < @ENDINGYEAR OR (ANNO = @ENDINGYEAR AND MES <= @ENDINGMONTH)) 
		 AND [SUBGRUPO CLIENTE] IN (SELECT * FROM OPENQUERY([ORACLE_SAB] , 'SELECT NOMBRE FROM BEZERRESIS.CLIENTES WHERE IDPLANTA = 1'))
		 AND [NEGOCIO] IN (SELECT * FROM OPENQUERY([ORACLE_SAB] , 'SELECT NOMBRE FROM BEZERRESIS.PRODUCTOS WHERE IDPLANTA = 1')) 
 
		 SELECT @SUMASEMESTRALPARAFECHA = SUM([CANTIDAD REAL])
		 FROM [supply].[dbo].[VENTAS_CSV]
		 WHERE EMP=1
		 AND (ANNO > @STARTINGYEAR2 OR (ANNO = @STARTINGYEAR2 AND MES >= @STARTINGMONTH2))
		 AND (ANNO < @ENDINGYEAR OR (ANNO = @ENDINGYEAR AND MES <= @ENDINGMONTH)) 
		 AND [SUBGRUPO CLIENTE] IN (SELECT * FROM OPENQUERY([ORACLE_SAB] , 'SELECT NOMBRE FROM BEZERRESIS.CLIENTES WHERE IDPLANTA = 1'))
		 AND [NEGOCIO] IN (SELECT * FROM OPENQUERY([ORACLE_SAB] , 'SELECT NOMBRE FROM BEZERRESIS.PRODUCTOS WHERE IDPLANTA = 1'))


	INSERT INTO [batzweb_TEST].[dbo].[Acumulados_Bezerresis] (PERIODO,CLIENTE,ANNO,MES,[SUMA PIEZAS],IDPLANTA)
	VALUES('ANUAL','TODOS', @ENDINGYEAR, @ENDINGMONTH, @SUMAANUALPARAFECHA,1)

	INSERT INTO [batzweb_TEST].[dbo].[Acumulados_Bezerresis] (PERIODO,CLIENTE,ANNO,MES,[SUMA PIEZAS],IDPLANTA)
	VALUES('SEMESTRAL','TODOS', @ENDINGYEAR, @ENDINGMONTH, @SUMASEMESTRALPARAFECHA,1)

	SET @STARTDATE = DATEADD(MONTH, 1, @STARTDATE)
END;

