'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CLIPRO
    Public Property IDCLI As Decimal
    Public Property IDPRO As Decimal
    Public Property ID As Decimal

    Public Overridable Property CLIENTES As CLIENTES
    Public Overridable Property PRODUCTOS As PRODUCTOS

End Class
