'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class GRUPOS
    Public Property ID As Decimal
    Public Property OBSOLETO As Decimal

    Public Overridable Property RECURSOS As ICollection(Of RECURSOS) = New HashSet(Of RECURSOS)
    Public Overridable Property USUARIOS As ICollection(Of USUARIOS) = New HashSet(Of USUARIOS)

End Class
