'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class Entities_BezerreSis
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=Entities_BezerreSis")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property CLIENTES() As DbSet(Of CLIENTES)
    Public Overridable Property INDICADORES() As DbSet(Of INDICADORES)
    Public Overridable Property PRODUCTOS() As DbSet(Of PRODUCTOS)
    Public Overridable Property PLANTAS() As DbSet(Of PLANTAS)
    Public Overridable Property OBJETIVOS() As DbSet(Of OBJETIVOS)
    Public Overridable Property CLIPRO() As DbSet(Of CLIPRO)
    Public Overridable Property GRUPOS() As DbSet(Of GRUPOS)
    Public Overridable Property RECURSOS() As DbSet(Of RECURSOS)
    Public Overridable Property USUARIOS() As DbSet(Of USUARIOS)
    Public Overridable Property RECLAMACIONES() As DbSet(Of RECLAMACIONES)
    Public Overridable Property RECLAMACIONES_CIERRE() As DbSet(Of RECLAMACIONES_CIERRE)

End Class
