'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OBJETIVOS
    Public Property ID As Decimal
    Public Property IDCLIENTE As Decimal
    Public Property FECHA As Date
    Public Property PPM_ANUAL As Nullable(Of Decimal)
    Public Property PPM_MENSUAL As Nullable(Of Decimal)
    Public Property IPB_SEMESTRAL As Nullable(Of Decimal)

    Public Overridable Property CLIENTES As CLIENTES

End Class
