'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OBJETIVOS_PRODUCTO
    Public Property ID As Decimal
    Public Property FECHA As Date
    Public Property PPM_ANUAL As Nullable(Of Decimal)
    Public Property PPM_MENSUAL As Nullable(Of Decimal)
    Public Property PRR_ANUAL As Nullable(Of Decimal)
    Public Property PRR_MENSUAL As Nullable(Of Decimal)
    Public Property IDCLIPRO As Decimal

    Public Overridable Property CLIPRO As CLIPRO

End Class
