'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PLANTAS
    Public Property ID As Decimal
    Public Property NOMBRE As String
    Public Property DESCRIP As String
    Public Property OBSOLETO As Nullable(Of Decimal)
    Public Property DOMINIO As String
    Public Property PATH_LDAP As String
    Public Property PATH_EXCHANGE As String
    Public Property TIMEZONE_ID As String
    Public Property MOSTRAR_RELOJ As Nullable(Of Boolean)
    Public Property TEXTO_RELOJ As String
    Public Property USER_LDAP As String
    Public Property PASS_LDAP As String
    Public Property CIF As String
    Public Property UBICACION As String
    Public Property ID_IZARO As Nullable(Of Decimal)
    Public Property ID_MONEDA As Nullable(Of Decimal)
    Public Property CIUDAD As String
    Public Property PAIS As String
    Public Property ID_BRAIN As String
    Public Property ID_EPSILON As String
    Public Property XBAT_CONSTRING As String
    Public Property DIRECCION As String
    Public Property CP As String
    Public Property PROVINCIA As String
    Public Property TELEFONO As String
    Public Property FAX As String
    Public Property EPSILON_CONSTRING As String

    Public Overridable Property CLIENTES As ICollection(Of CLIENTES) = New HashSet(Of CLIENTES)
    Public Overridable Property USUARIOS As ICollection(Of USUARIOS) = New HashSet(Of USUARIOS)
    Public Overridable Property PRODUCTOS As ICollection(Of PRODUCTOS) = New HashSet(Of PRODUCTOS)

End Class
