'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PRODUCTOS
    Public Property ID As Decimal
    Public Property CODIGO As String
    Public Property NOMBRE As String
    Public Property IDPLANTA As Decimal

    Public Overridable Property INDICADORES As ICollection(Of INDICADORES) = New HashSet(Of INDICADORES)
    Public Overridable Property CLIPRO As ICollection(Of CLIPRO) = New HashSet(Of CLIPRO)
    Public Overridable Property PLANTAS As PLANTAS
    Public Overridable Property RECLAMACIONES As ICollection(Of RECLAMACIONES) = New HashSet(Of RECLAMACIONES)

End Class
