'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RECLAMACIONES_CIERRE
    Public Property ID As Decimal
    Public Property FECHA_RESP_CONTENCION As Nullable(Of Date)
    Public Property FECHA_RESP_CORRECTIVAS As Nullable(Of Date)
    Public Property FECHA_CIERRECLIENTE As Nullable(Of Date)
    Public Property COSTE_REVISIONCLIENTE As Nullable(Of Decimal)
    Public Property COSTE_CARGOSCLIENTE As Nullable(Of Decimal)
    Public Property COSTE_REVISIONINTERNA As Nullable(Of Decimal)
    Public Property COSTE_MATERIALESCHATARRA As Nullable(Of Decimal)
    Public Property COSTE_OTROS As Nullable(Of Decimal)
    Public Property COSTE_OTROS_DESCRIPCION As String

    Public Overridable Property RECLAMACIONES As RECLAMACIONES

End Class
