'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RECLAMACIONES
    Public Property ID As Decimal
    Public Property CLIENTE As Decimal
    Public Property REFCLIENTE As String
    Public Property PLANTACLIENTE As String
    Public Property CODXCLIENTE As String
    Public Property FECHACREACION As Date
    Public Property REFINTERNAPIEZA As String
    Public Property DENOMINACION As String
    Public Property PROYECTO As String
    Public Property NUMPIEZASNOK As Integer
    Public Property DESCRIPCION As String
    Public Property PRODUCTO As Decimal
    Public Property PROCEDENCIA As Decimal
    Public Property CLASIFICACION As Decimal
    Public Property NIVELIMPORTANCIA As Decimal
    Public Property REPETITIVA As Decimal
    Public Property RECLAMACIONOFICIAL As Decimal
    Public Property CREADOR As Decimal

    Public Property AFECTA_INDICADORES As Decimal

    Public Overridable Property CLIENTES As CLIENTES
    Public Overridable Property PRODUCTOS As PRODUCTOS
    Public Overridable Property USUARIOS As USUARIOS
    Public Overridable Property RECLAMACIONES_CIERRE As RECLAMACIONES_CIERRE

End Class
