'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RECURSOS
    Public Property ID As Decimal
    Public Property IDPARENT As Nullable(Of Decimal)
    Public Property URL As String
    Public Property OBSOLETO As Decimal
    Public Property TIPO As String
    Public Property IMAGEN As Byte()
    Public Property VISIBLE As Nullable(Of Boolean)
    Public Property FICHERO As Byte()
    Public Property NOMBRE_FICHERO As String
    Public Property TARGET As String
    Public Property CATALOGABLE As Nullable(Of Boolean)
    Public Property IMG_CATALOGO As Byte()
    Public Property DESCRIP_CATALOGO As String
    Public Property NOMBRE_IMGCATALOGO As String
    Public Property ID_RESPONSABLE As Nullable(Of Decimal)

    Public Overridable Property GRUPOS As ICollection(Of GRUPOS) = New HashSet(Of GRUPOS)

End Class
