'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class USUARIOS
    Public Property ID As Decimal
    Public Property IDEMPRESAS As Decimal
    Public Property IDCULTURAS As String
    Public Property NOMBREUSUARIO As String
    Public Property IDDIRECTORIOACTIVO As String
    Public Property CODPERSONA As Nullable(Of Decimal)
    Public Property PWD As String
    Public Property FECHAALTA As Nullable(Of Date)
    Public Property FECHABAJA As Nullable(Of Date)
    Public Property APELLIDO1 As String
    Public Property APELLIDO2 As String
    Public Property IDMATRIX As String
    Public Property IDFTP As String
    Public Property EMAIL As String
    Public Property IDDEPARTAMENTO As String
    Public Property NOMBRE As String
    Public Property FOTO As Byte()
    Public Property DNI As String
    Public Property NIKEUSKARAZ As Nullable(Of Boolean)
    Public Property IDPLANTA As Nullable(Of Decimal)
    Public Property USUARIO_EMPRESA As Nullable(Of Boolean)

    Public Overridable Property PLANTAS As PLANTAS
    Public Overridable Property GRUPOS As ICollection(Of GRUPOS) = New HashSet(Of GRUPOS)
    Public Overridable Property RECLAMACIONES As ICollection(Of RECLAMACIONES) = New HashSet(Of RECLAMACIONES)

End Class
