'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Funcionalidad para autoguardar My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=ATXEKOITURRI;Initial Catalog=PAC_IGO_TEST;Persist Security Info=True;"& _ 
            "User ID=sa;Password=joane2005 ")>  _
        Public ReadOnly Property PAC_IGO_TESTConnectionString() As String
            Get
                Return CType(Me("PAC_IGO_TESTConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=ATXEKOITURRI;Initial Catalog=PAC_IGO_TEST;Persist Security Info=True;"& _ 
            "User ID=sa")>  _
        Public ReadOnly Property PAC_IGO_TESTConnectionString1() As String
            Get
                Return CType(Me("PAC_IGO_TESTConnectionString1"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=BTZSQLDB1\MSSQLINS1;Initial Catalog=KAPLAN_TEST;Persist Security Info"& _ 
            "=True;User ID=BtzSqlDbOwner;Password=btzsdbo")>  _
        Public ReadOnly Property KAPLAN_TESTConnectionString() As String
            Get
                Return CType(Me("KAPLAN_TESTConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=BTZSQLDB1\MSSQLINS1;Initial Catalog=KAPLAN_TEST;Persist Security Info"& _ 
            "=True;User ID=developer;Password=acyacpnthdd")>  _
        Public ReadOnly Property KAPLAN_TESTConnectionString1() As String
            Get
                Return CType(Me("KAPLAN_TESTConnectionString1"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=BTZSQLDB1\MSSQLINS1;Initial Catalog=KAPLAN;Persist Security Info=True"& _ 
            ";User ID=BtzSqlLoginWriter;Password=btzsw")>  _
        Public ReadOnly Property KAPLANConnectionString() As String
            Get
                Return CType(Me("KAPLANConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=BTZSQLDB1\MSSQLINS1;Initial Catalog=KAPLAN_TEST;Integrated Security=T"& _ 
            "rue")>  _
        Public ReadOnly Property KAPLAN_TESTConnectionString2() As String
            Get
                Return CType(Me("KAPLAN_TESTConnectionString2"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=btzsqldb1\MSSQLINS1;Initial Catalog=KAPLAN_TEST;Persist Security Info"& _ 
            "=True;User ID=BtzSqlDbOwner;Password=btzsdbo")>  _
        Public ReadOnly Property KAPLAN_TESTConnectionString3() As String
            Get
                Return CType(Me("KAPLAN_TESTConnectionString3"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=btzsqldb1\MSSQLINS1;Initial Catalog=KAPLAN_TEST;Persist Security Info"& _ 
            "=True;User ID=BtzSqlDbOwner")>  _
        Public ReadOnly Property KAPLAN_TESTConnectionString4() As String
            Get
                Return CType(Me("KAPLAN_TESTConnectionString4"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.KaPlanLib.My.MySettings
            Get
                Return Global.KaPlanLib.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
