'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AutocompleteGV
    
    '''<summary>
    '''divImgGV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divImgGV As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInput As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''hfValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfValue As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''imgBuscar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBuscar As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''helper control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents helper As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnFire control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFire As Global.System.Web.UI.WebControls.Button
End Class
