'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace Matrix_PLMV6
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="BzServicesBonosServiceSoapBinding", [Namespace]:="http://bzServices")>  _
    Partial Public Class BonosServiceService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private getCausaECOOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getCustomersOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getProjectsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getProductsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getProjectInfoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getProjectConceptRelatedRealProjectOperationCompleted As System.Threading.SendOrPostCallback
        
        Private updateProjectCostCarrierOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getAllProjectStatesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getProjectMembersWithRoleOperationCompleted As System.Threading.SendOrPostCallback
        
        Private updateProjectOfferNumberOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getProjectsByProductOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getProjectSerieAffectedOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.BonosSisLib.My.MySettings.Default.BonosSisLib_Matrix_PLMV6_BonosServiceService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event getCausaECOCompleted As getCausaECOCompletedEventHandler
        
        '''<remarks/>
        Public Event getCustomersCompleted As getCustomersCompletedEventHandler
        
        '''<remarks/>
        Public Event getProjectsCompleted As getProjectsCompletedEventHandler
        
        '''<remarks/>
        Public Event getProductsCompleted As getProductsCompletedEventHandler
        
        '''<remarks/>
        Public Event getProjectInfoCompleted As getProjectInfoCompletedEventHandler
        
        '''<remarks/>
        Public Event getProjectConceptRelatedRealProjectCompleted As getProjectConceptRelatedRealProjectCompletedEventHandler
        
        '''<remarks/>
        Public Event updateProjectCostCarrierCompleted As updateProjectCostCarrierCompletedEventHandler
        
        '''<remarks/>
        Public Event getAllProjectStatesCompleted As getAllProjectStatesCompletedEventHandler
        
        '''<remarks/>
        Public Event getProjectMembersWithRoleCompleted As getProjectMembersWithRoleCompletedEventHandler
        
        '''<remarks/>
        Public Event updateProjectOfferNumberCompleted As updateProjectOfferNumberCompletedEventHandler
        
        '''<remarks/>
        Public Event getProjectsByProductCompleted As getProjectsByProductCompletedEventHandler
        
        '''<remarks/>
        Public Event getProjectSerieAffectedCompleted As getProjectSerieAffectedCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://bzServices", ResponseNamespace:="http://bzServices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getCausaECO(ByVal in0 As String) As <System.Xml.Serialization.XmlElementAttribute("getCausaECOReturn")> String
            Dim results() As Object = Me.Invoke("getCausaECO", New Object() {in0})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getCausaECOAsync(ByVal in0 As String)
            Me.getCausaECOAsync(in0, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getCausaECOAsync(ByVal in0 As String, ByVal userState As Object)
            If (Me.getCausaECOOperationCompleted Is Nothing) Then
                Me.getCausaECOOperationCompleted = AddressOf Me.OngetCausaECOOperationCompleted
            End If
            Me.InvokeAsync("getCausaECO", New Object() {in0}, Me.getCausaECOOperationCompleted, userState)
        End Sub
        
        Private Sub OngetCausaECOOperationCompleted(ByVal arg As Object)
            If (Not (Me.getCausaECOCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getCausaECOCompleted(Me, New getCausaECOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://bzServices", ResponseNamespace:="http://bzServices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getCustomers() As <System.Xml.Serialization.XmlElementAttribute("getCustomersReturn")> String
            Dim results() As Object = Me.Invoke("getCustomers", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getCustomersAsync()
            Me.getCustomersAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getCustomersAsync(ByVal userState As Object)
            If (Me.getCustomersOperationCompleted Is Nothing) Then
                Me.getCustomersOperationCompleted = AddressOf Me.OngetCustomersOperationCompleted
            End If
            Me.InvokeAsync("getCustomers", New Object(-1) {}, Me.getCustomersOperationCompleted, userState)
        End Sub
        
        Private Sub OngetCustomersOperationCompleted(ByVal arg As Object)
            If (Not (Me.getCustomersCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getCustomersCompleted(Me, New getCustomersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://bzServices", ResponseNamespace:="http://bzServices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getProjects(ByVal in0 As String, ByVal in1 As String, ByVal in2 As String, ByVal in3 As String, ByVal in4 As Boolean) As <System.Xml.Serialization.XmlElementAttribute("getProjectsReturn")> combatzServicesBonosProject()
            Dim results() As Object = Me.Invoke("getProjects", New Object() {in0, in1, in2, in3, in4})
            Return CType(results(0),combatzServicesBonosProject())
        End Function
        
        '''<remarks/>
        Public Overloads Sub getProjectsAsync(ByVal in0 As String, ByVal in1 As String, ByVal in2 As String, ByVal in3 As String, ByVal in4 As Boolean)
            Me.getProjectsAsync(in0, in1, in2, in3, in4, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getProjectsAsync(ByVal in0 As String, ByVal in1 As String, ByVal in2 As String, ByVal in3 As String, ByVal in4 As Boolean, ByVal userState As Object)
            If (Me.getProjectsOperationCompleted Is Nothing) Then
                Me.getProjectsOperationCompleted = AddressOf Me.OngetProjectsOperationCompleted
            End If
            Me.InvokeAsync("getProjects", New Object() {in0, in1, in2, in3, in4}, Me.getProjectsOperationCompleted, userState)
        End Sub
        
        Private Sub OngetProjectsOperationCompleted(ByVal arg As Object)
            If (Not (Me.getProjectsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getProjectsCompleted(Me, New getProjectsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://bzServices", ResponseNamespace:="http://bzServices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getProducts() As <System.Xml.Serialization.XmlElementAttribute("getProductsReturn")> String
            Dim results() As Object = Me.Invoke("getProducts", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getProductsAsync()
            Me.getProductsAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getProductsAsync(ByVal userState As Object)
            If (Me.getProductsOperationCompleted Is Nothing) Then
                Me.getProductsOperationCompleted = AddressOf Me.OngetProductsOperationCompleted
            End If
            Me.InvokeAsync("getProducts", New Object(-1) {}, Me.getProductsOperationCompleted, userState)
        End Sub
        
        Private Sub OngetProductsOperationCompleted(ByVal arg As Object)
            If (Not (Me.getProductsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getProductsCompleted(Me, New getProductsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://bzServices", ResponseNamespace:="http://bzServices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getProjectInfo(ByVal in0 As String) As <System.Xml.Serialization.XmlElementAttribute("getProjectInfoReturn")> combatzServicesBonosProject
            Dim results() As Object = Me.Invoke("getProjectInfo", New Object() {in0})
            Return CType(results(0),combatzServicesBonosProject)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getProjectInfoAsync(ByVal in0 As String)
            Me.getProjectInfoAsync(in0, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getProjectInfoAsync(ByVal in0 As String, ByVal userState As Object)
            If (Me.getProjectInfoOperationCompleted Is Nothing) Then
                Me.getProjectInfoOperationCompleted = AddressOf Me.OngetProjectInfoOperationCompleted
            End If
            Me.InvokeAsync("getProjectInfo", New Object() {in0}, Me.getProjectInfoOperationCompleted, userState)
        End Sub
        
        Private Sub OngetProjectInfoOperationCompleted(ByVal arg As Object)
            If (Not (Me.getProjectInfoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getProjectInfoCompleted(Me, New getProjectInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://bzServices", ResponseNamespace:="http://bzServices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getProjectConceptRelatedRealProject(ByVal in0 As String) As <System.Xml.Serialization.XmlElementAttribute("getProjectConceptRelatedRealProjectReturn")> String
            Dim results() As Object = Me.Invoke("getProjectConceptRelatedRealProject", New Object() {in0})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getProjectConceptRelatedRealProjectAsync(ByVal in0 As String)
            Me.getProjectConceptRelatedRealProjectAsync(in0, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getProjectConceptRelatedRealProjectAsync(ByVal in0 As String, ByVal userState As Object)
            If (Me.getProjectConceptRelatedRealProjectOperationCompleted Is Nothing) Then
                Me.getProjectConceptRelatedRealProjectOperationCompleted = AddressOf Me.OngetProjectConceptRelatedRealProjectOperationCompleted
            End If
            Me.InvokeAsync("getProjectConceptRelatedRealProject", New Object() {in0}, Me.getProjectConceptRelatedRealProjectOperationCompleted, userState)
        End Sub
        
        Private Sub OngetProjectConceptRelatedRealProjectOperationCompleted(ByVal arg As Object)
            If (Not (Me.getProjectConceptRelatedRealProjectCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getProjectConceptRelatedRealProjectCompleted(Me, New getProjectConceptRelatedRealProjectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://bzServices", ResponseNamespace:="http://bzServices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function updateProjectCostCarrier(ByVal in0 As String, ByVal in1 As String) As <System.Xml.Serialization.XmlElementAttribute("updateProjectCostCarrierReturn")> Integer
            Dim results() As Object = Me.Invoke("updateProjectCostCarrier", New Object() {in0, in1})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub updateProjectCostCarrierAsync(ByVal in0 As String, ByVal in1 As String)
            Me.updateProjectCostCarrierAsync(in0, in1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub updateProjectCostCarrierAsync(ByVal in0 As String, ByVal in1 As String, ByVal userState As Object)
            If (Me.updateProjectCostCarrierOperationCompleted Is Nothing) Then
                Me.updateProjectCostCarrierOperationCompleted = AddressOf Me.OnupdateProjectCostCarrierOperationCompleted
            End If
            Me.InvokeAsync("updateProjectCostCarrier", New Object() {in0, in1}, Me.updateProjectCostCarrierOperationCompleted, userState)
        End Sub
        
        Private Sub OnupdateProjectCostCarrierOperationCompleted(ByVal arg As Object)
            If (Not (Me.updateProjectCostCarrierCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent updateProjectCostCarrierCompleted(Me, New updateProjectCostCarrierCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://bzServices", ResponseNamespace:="http://bzServices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getAllProjectStates() As <System.Xml.Serialization.XmlElementAttribute("getAllProjectStatesReturn")> String
            Dim results() As Object = Me.Invoke("getAllProjectStates", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getAllProjectStatesAsync()
            Me.getAllProjectStatesAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getAllProjectStatesAsync(ByVal userState As Object)
            If (Me.getAllProjectStatesOperationCompleted Is Nothing) Then
                Me.getAllProjectStatesOperationCompleted = AddressOf Me.OngetAllProjectStatesOperationCompleted
            End If
            Me.InvokeAsync("getAllProjectStates", New Object(-1) {}, Me.getAllProjectStatesOperationCompleted, userState)
        End Sub
        
        Private Sub OngetAllProjectStatesOperationCompleted(ByVal arg As Object)
            If (Not (Me.getAllProjectStatesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getAllProjectStatesCompleted(Me, New getAllProjectStatesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://bzServices", ResponseNamespace:="http://bzServices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getProjectMembersWithRole(ByVal in0 As String, ByVal in1 As String) As <System.Xml.Serialization.XmlElementAttribute("getProjectMembersWithRoleReturn")> combatzServicesProjectMember()
            Dim results() As Object = Me.Invoke("getProjectMembersWithRole", New Object() {in0, in1})
            Return CType(results(0),combatzServicesProjectMember())
        End Function
        
        '''<remarks/>
        Public Overloads Sub getProjectMembersWithRoleAsync(ByVal in0 As String, ByVal in1 As String)
            Me.getProjectMembersWithRoleAsync(in0, in1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getProjectMembersWithRoleAsync(ByVal in0 As String, ByVal in1 As String, ByVal userState As Object)
            If (Me.getProjectMembersWithRoleOperationCompleted Is Nothing) Then
                Me.getProjectMembersWithRoleOperationCompleted = AddressOf Me.OngetProjectMembersWithRoleOperationCompleted
            End If
            Me.InvokeAsync("getProjectMembersWithRole", New Object() {in0, in1}, Me.getProjectMembersWithRoleOperationCompleted, userState)
        End Sub
        
        Private Sub OngetProjectMembersWithRoleOperationCompleted(ByVal arg As Object)
            If (Not (Me.getProjectMembersWithRoleCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getProjectMembersWithRoleCompleted(Me, New getProjectMembersWithRoleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://bzServices", ResponseNamespace:="http://bzServices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function updateProjectOfferNumber(ByVal in0 As String, ByVal in1 As String) As <System.Xml.Serialization.XmlElementAttribute("updateProjectOfferNumberReturn")> Integer
            Dim results() As Object = Me.Invoke("updateProjectOfferNumber", New Object() {in0, in1})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub updateProjectOfferNumberAsync(ByVal in0 As String, ByVal in1 As String)
            Me.updateProjectOfferNumberAsync(in0, in1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub updateProjectOfferNumberAsync(ByVal in0 As String, ByVal in1 As String, ByVal userState As Object)
            If (Me.updateProjectOfferNumberOperationCompleted Is Nothing) Then
                Me.updateProjectOfferNumberOperationCompleted = AddressOf Me.OnupdateProjectOfferNumberOperationCompleted
            End If
            Me.InvokeAsync("updateProjectOfferNumber", New Object() {in0, in1}, Me.updateProjectOfferNumberOperationCompleted, userState)
        End Sub
        
        Private Sub OnupdateProjectOfferNumberOperationCompleted(ByVal arg As Object)
            If (Not (Me.updateProjectOfferNumberCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent updateProjectOfferNumberCompleted(Me, New updateProjectOfferNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://bzServices", ResponseNamespace:="http://bzServices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getProjectsByProduct(ByVal in0 As String) As <System.Xml.Serialization.XmlElementAttribute("getProjectsByProductReturn")> combatzServicesBonosProject()
            Dim results() As Object = Me.Invoke("getProjectsByProduct", New Object() {in0})
            Return CType(results(0),combatzServicesBonosProject())
        End Function
        
        '''<remarks/>
        Public Overloads Sub getProjectsByProductAsync(ByVal in0 As String)
            Me.getProjectsByProductAsync(in0, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getProjectsByProductAsync(ByVal in0 As String, ByVal userState As Object)
            If (Me.getProjectsByProductOperationCompleted Is Nothing) Then
                Me.getProjectsByProductOperationCompleted = AddressOf Me.OngetProjectsByProductOperationCompleted
            End If
            Me.InvokeAsync("getProjectsByProduct", New Object() {in0}, Me.getProjectsByProductOperationCompleted, userState)
        End Sub
        
        Private Sub OngetProjectsByProductOperationCompleted(ByVal arg As Object)
            If (Not (Me.getProjectsByProductCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getProjectsByProductCompleted(Me, New getProjectsByProductCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://bzServices", ResponseNamespace:="http://bzServices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getProjectSerieAffected(ByVal in0 As String) As <System.Xml.Serialization.XmlElementAttribute("getProjectSerieAffectedReturn")> String
            Dim results() As Object = Me.Invoke("getProjectSerieAffected", New Object() {in0})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getProjectSerieAffectedAsync(ByVal in0 As String)
            Me.getProjectSerieAffectedAsync(in0, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getProjectSerieAffectedAsync(ByVal in0 As String, ByVal userState As Object)
            If (Me.getProjectSerieAffectedOperationCompleted Is Nothing) Then
                Me.getProjectSerieAffectedOperationCompleted = AddressOf Me.OngetProjectSerieAffectedOperationCompleted
            End If
            Me.InvokeAsync("getProjectSerieAffected", New Object() {in0}, Me.getProjectSerieAffectedOperationCompleted, userState)
        End Sub
        
        Private Sub OngetProjectSerieAffectedOperationCompleted(ByVal arg As Object)
            If (Not (Me.getProjectSerieAffectedCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getProjectSerieAffectedCompleted(Me, New getProjectSerieAffectedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(TypeName:="com.batz.Services.BonosProject", [Namespace]:="http://bzServices")>  _
    Partial Public Class combatzServicesBonosProject
        
        Private ofField As String
        
        Private pGYearField As String
        
        Private causaECOField As String
        
        Private coOwnerField As String
        
        Private customerField As String
        
        Private descriptionField As String
        
        Private gate3ApprovedField As System.Nullable(Of Boolean)
        
        Private idField As String
        
        Private idFatherField As String
        
        Private idProyectoConceptoRealField As String
        
        Private indicatorField As System.Nullable(Of Boolean)
        
        Private isECOField As System.Nullable(Of Boolean)
        
        Private isPotencialField As System.Nullable(Of Boolean)
        
        Private nameField As String
        
        Private offerNumberField As String
        
        Private plantToChargeField As String
        
        Private policyField As String
        
        Private policyProyectoConceptoField As String
        
        Private productField As String
        
        Private programField As String
        
        Private responsibleField As String
        
        Private startDateField As String
        
        Private statusField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property [OF]() As String
            Get
                Return Me.ofField
            End Get
            Set
                Me.ofField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property PGYear() As String
            Get
                Return Me.pGYearField
            End Get
            Set
                Me.pGYearField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property causaECO() As String
            Get
                Return Me.causaECOField
            End Get
            Set
                Me.causaECOField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property coOwner() As String
            Get
                Return Me.coOwnerField
            End Get
            Set
                Me.coOwnerField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property customer() As String
            Get
                Return Me.customerField
            End Get
            Set
                Me.customerField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property description() As String
            Get
                Return Me.descriptionField
            End Get
            Set
                Me.descriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property gate3Approved() As System.Nullable(Of Boolean)
            Get
                Return Me.gate3ApprovedField
            End Get
            Set
                Me.gate3ApprovedField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property idFather() As String
            Get
                Return Me.idFatherField
            End Get
            Set
                Me.idFatherField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property idProyectoConceptoReal() As String
            Get
                Return Me.idProyectoConceptoRealField
            End Get
            Set
                Me.idProyectoConceptoRealField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property indicator() As System.Nullable(Of Boolean)
            Get
                Return Me.indicatorField
            End Get
            Set
                Me.indicatorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property isECO() As System.Nullable(Of Boolean)
            Get
                Return Me.isECOField
            End Get
            Set
                Me.isECOField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property isPotencial() As System.Nullable(Of Boolean)
            Get
                Return Me.isPotencialField
            End Get
            Set
                Me.isPotencialField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property offerNumber() As String
            Get
                Return Me.offerNumberField
            End Get
            Set
                Me.offerNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property plantToCharge() As String
            Get
                Return Me.plantToChargeField
            End Get
            Set
                Me.plantToChargeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property policy() As String
            Get
                Return Me.policyField
            End Get
            Set
                Me.policyField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property policyProyectoConcepto() As String
            Get
                Return Me.policyProyectoConceptoField
            End Get
            Set
                Me.policyProyectoConceptoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property product() As String
            Get
                Return Me.productField
            End Get
            Set
                Me.productField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property program() As String
            Get
                Return Me.programField
            End Get
            Set
                Me.programField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property responsible() As String
            Get
                Return Me.responsibleField
            End Get
            Set
                Me.responsibleField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property startDate() As String
            Get
                Return Me.startDateField
            End Get
            Set
                Me.startDateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(TypeName:="com.batz.Services.ProjectMember", [Namespace]:="http://bzServices")>  _
    Partial Public Class combatzServicesProjectMember
        
        Private projectRoleField As String
        
        Private userNameField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property projectRole() As String
            Get
                Return Me.projectRoleField
            End Get
            Set
                Me.projectRoleField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property userName() As String
            Get
                Return Me.userNameField
            End Get
            Set
                Me.userNameField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub getCausaECOCompletedEventHandler(ByVal sender As Object, ByVal e As getCausaECOCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getCausaECOCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub getCustomersCompletedEventHandler(ByVal sender As Object, ByVal e As getCustomersCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getCustomersCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub getProjectsCompletedEventHandler(ByVal sender As Object, ByVal e As getProjectsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getProjectsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As combatzServicesBonosProject()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),combatzServicesBonosProject())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub getProductsCompletedEventHandler(ByVal sender As Object, ByVal e As getProductsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getProductsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub getProjectInfoCompletedEventHandler(ByVal sender As Object, ByVal e As getProjectInfoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getProjectInfoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As combatzServicesBonosProject
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),combatzServicesBonosProject)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub getProjectConceptRelatedRealProjectCompletedEventHandler(ByVal sender As Object, ByVal e As getProjectConceptRelatedRealProjectCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getProjectConceptRelatedRealProjectCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub updateProjectCostCarrierCompletedEventHandler(ByVal sender As Object, ByVal e As updateProjectCostCarrierCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class updateProjectCostCarrierCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub getAllProjectStatesCompletedEventHandler(ByVal sender As Object, ByVal e As getAllProjectStatesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getAllProjectStatesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub getProjectMembersWithRoleCompletedEventHandler(ByVal sender As Object, ByVal e As getProjectMembersWithRoleCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getProjectMembersWithRoleCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As combatzServicesProjectMember()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),combatzServicesProjectMember())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub updateProjectOfferNumberCompletedEventHandler(ByVal sender As Object, ByVal e As updateProjectOfferNumberCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class updateProjectOfferNumberCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub getProjectsByProductCompletedEventHandler(ByVal sender As Object, ByVal e As getProjectsByProductCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getProjectsByProductCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As combatzServicesBonosProject()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),combatzServicesBonosProject())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub getProjectSerieAffectedCompletedEventHandler(ByVal sender As Object, ByVal e As getProjectSerieAffectedCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getProjectSerieAffectedCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
