'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace ServicioOfertaTecnica
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ServiceCostCarriersSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ServiceCostCarriers
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private GetProductsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetProjectsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetProjectFactoriesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetActiveOfferOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetStepsFromTechnicalOfferOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetDatoReal_XPERTOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetDatoReal_BonosOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetQuantityInOtherCurrencyOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetOfferExchangeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetFactoryCurrencyOfferOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetCurrencyExchangeRateInDateOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetProductsIsProductManagerOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetProductManagersOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetFactoriesIsGerenteOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetGerenteOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetGerentesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.CostCarriersLib.My.MySettings.Default.CostCarriersLib_ServicioOfertaTecnica_ServiceCostCarriers
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event GetProductsCompleted As GetProductsCompletedEventHandler
        
        '''<remarks/>
        Public Event GetProjectsCompleted As GetProjectsCompletedEventHandler
        
        '''<remarks/>
        Public Event GetProjectFactoriesCompleted As GetProjectFactoriesCompletedEventHandler
        
        '''<remarks/>
        Public Event GetActiveOfferCompleted As GetActiveOfferCompletedEventHandler
        
        '''<remarks/>
        Public Event GetStepsFromTechnicalOfferCompleted As GetStepsFromTechnicalOfferCompletedEventHandler
        
        '''<remarks/>
        Public Event GetDatoReal_XPERTCompleted As GetDatoReal_XPERTCompletedEventHandler
        
        '''<remarks/>
        Public Event GetDatoReal_BonosCompleted As GetDatoReal_BonosCompletedEventHandler
        
        '''<remarks/>
        Public Event GetQuantityInOtherCurrencyCompleted As GetQuantityInOtherCurrencyCompletedEventHandler
        
        '''<remarks/>
        Public Event GetOfferExchangeCompleted As GetOfferExchangeCompletedEventHandler
        
        '''<remarks/>
        Public Event GetFactoryCurrencyOfferCompleted As GetFactoryCurrencyOfferCompletedEventHandler
        
        '''<remarks/>
        Public Event GetCurrencyExchangeRateInDateCompleted As GetCurrencyExchangeRateInDateCompletedEventHandler
        
        '''<remarks/>
        Public Event GetProductsIsProductManagerCompleted As GetProductsIsProductManagerCompletedEventHandler
        
        '''<remarks/>
        Public Event GetProductManagersCompleted As GetProductManagersCompletedEventHandler
        
        '''<remarks/>
        Public Event GetFactoriesIsGerenteCompleted As GetFactoriesIsGerenteCompletedEventHandler
        
        '''<remarks/>
        Public Event GetGerenteCompleted As GetGerenteCompletedEventHandler
        
        '''<remarks/>
        Public Event GetGerentesCompleted As GetGerentesCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetProducts", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetProducts(ByVal tipo As String, ByVal owner As String) As String
            Dim results() As Object = Me.Invoke("GetProducts", New Object() {tipo, owner})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetProductsAsync(ByVal tipo As String, ByVal owner As String)
            Me.GetProductsAsync(tipo, owner, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetProductsAsync(ByVal tipo As String, ByVal owner As String, ByVal userState As Object)
            If (Me.GetProductsOperationCompleted Is Nothing) Then
                Me.GetProductsOperationCompleted = AddressOf Me.OnGetProductsOperationCompleted
            End If
            Me.InvokeAsync("GetProducts", New Object() {tipo, owner}, Me.GetProductsOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetProductsOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetProductsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetProductsCompleted(Me, New GetProductsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetProjects", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetProjects(ByVal product As String, ByVal tipo As Integer, ByVal owner As String) As String
            Dim results() As Object = Me.Invoke("GetProjects", New Object() {product, tipo, owner})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetProjectsAsync(ByVal product As String, ByVal tipo As Integer, ByVal owner As String)
            Me.GetProjectsAsync(product, tipo, owner, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetProjectsAsync(ByVal product As String, ByVal tipo As Integer, ByVal owner As String, ByVal userState As Object)
            If (Me.GetProjectsOperationCompleted Is Nothing) Then
                Me.GetProjectsOperationCompleted = AddressOf Me.OnGetProjectsOperationCompleted
            End If
            Me.InvokeAsync("GetProjects", New Object() {product, tipo, owner}, Me.GetProjectsOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetProjectsOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetProjectsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetProjectsCompleted(Me, New GetProjectsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetProjectFactories", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetProjectFactories(ByVal idProject As String, ByVal idOffer As Integer) As String
            Dim results() As Object = Me.Invoke("GetProjectFactories", New Object() {idProject, idOffer})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetProjectFactoriesAsync(ByVal idProject As String, ByVal idOffer As Integer)
            Me.GetProjectFactoriesAsync(idProject, idOffer, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetProjectFactoriesAsync(ByVal idProject As String, ByVal idOffer As Integer, ByVal userState As Object)
            If (Me.GetProjectFactoriesOperationCompleted Is Nothing) Then
                Me.GetProjectFactoriesOperationCompleted = AddressOf Me.OnGetProjectFactoriesOperationCompleted
            End If
            Me.InvokeAsync("GetProjectFactories", New Object() {idProject, idOffer}, Me.GetProjectFactoriesOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetProjectFactoriesOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetProjectFactoriesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetProjectFactoriesCompleted(Me, New GetProjectFactoriesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetActiveOffer", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetActiveOffer(ByVal idProject As String) As String
            Dim results() As Object = Me.Invoke("GetActiveOffer", New Object() {idProject})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetActiveOfferAsync(ByVal idProject As String)
            Me.GetActiveOfferAsync(idProject, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetActiveOfferAsync(ByVal idProject As String, ByVal userState As Object)
            If (Me.GetActiveOfferOperationCompleted Is Nothing) Then
                Me.GetActiveOfferOperationCompleted = AddressOf Me.OnGetActiveOfferOperationCompleted
            End If
            Me.InvokeAsync("GetActiveOffer", New Object() {idProject}, Me.GetActiveOfferOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetActiveOfferOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetActiveOfferCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetActiveOfferCompleted(Me, New GetActiveOfferCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetStepsFromTechnicalOffer", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetStepsFromTechnicalOffer(ByVal idOffer As Integer, ByVal idPlantaSab As Integer, ByVal idCostGroup As Integer) As String
            Dim results() As Object = Me.Invoke("GetStepsFromTechnicalOffer", New Object() {idOffer, idPlantaSab, idCostGroup})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetStepsFromTechnicalOfferAsync(ByVal idOffer As Integer, ByVal idPlantaSab As Integer, ByVal idCostGroup As Integer)
            Me.GetStepsFromTechnicalOfferAsync(idOffer, idPlantaSab, idCostGroup, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetStepsFromTechnicalOfferAsync(ByVal idOffer As Integer, ByVal idPlantaSab As Integer, ByVal idCostGroup As Integer, ByVal userState As Object)
            If (Me.GetStepsFromTechnicalOfferOperationCompleted Is Nothing) Then
                Me.GetStepsFromTechnicalOfferOperationCompleted = AddressOf Me.OnGetStepsFromTechnicalOfferOperationCompleted
            End If
            Me.InvokeAsync("GetStepsFromTechnicalOffer", New Object() {idOffer, idPlantaSab, idCostGroup}, Me.GetStepsFromTechnicalOfferOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetStepsFromTechnicalOfferOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetStepsFromTechnicalOfferCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetStepsFromTechnicalOfferCompleted(Me, New GetStepsFromTechnicalOfferCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDatoReal_XPERT", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetDatoReal_XPERT(ByVal idPlantaSab As Integer, ByVal costCarrier As String, ByVal finalCurrency As String) As String
            Dim results() As Object = Me.Invoke("GetDatoReal_XPERT", New Object() {idPlantaSab, costCarrier, finalCurrency})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetDatoReal_XPERTAsync(ByVal idPlantaSab As Integer, ByVal costCarrier As String, ByVal finalCurrency As String)
            Me.GetDatoReal_XPERTAsync(idPlantaSab, costCarrier, finalCurrency, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetDatoReal_XPERTAsync(ByVal idPlantaSab As Integer, ByVal costCarrier As String, ByVal finalCurrency As String, ByVal userState As Object)
            If (Me.GetDatoReal_XPERTOperationCompleted Is Nothing) Then
                Me.GetDatoReal_XPERTOperationCompleted = AddressOf Me.OnGetDatoReal_XPERTOperationCompleted
            End If
            Me.InvokeAsync("GetDatoReal_XPERT", New Object() {idPlantaSab, costCarrier, finalCurrency}, Me.GetDatoReal_XPERTOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetDatoReal_XPERTOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetDatoReal_XPERTCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetDatoReal_XPERTCompleted(Me, New GetDatoReal_XPERTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDatoReal_Bonos", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetDatoReal_Bonos(ByVal idPlantaSab As Integer, ByVal idProject As String, ByVal state As String, ByVal idCostGroupBonos As Integer, ByVal idFinalCurrency As Integer) As String
            Dim results() As Object = Me.Invoke("GetDatoReal_Bonos", New Object() {idPlantaSab, idProject, state, idCostGroupBonos, idFinalCurrency})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetDatoReal_BonosAsync(ByVal idPlantaSab As Integer, ByVal idProject As String, ByVal state As String, ByVal idCostGroupBonos As Integer, ByVal idFinalCurrency As Integer)
            Me.GetDatoReal_BonosAsync(idPlantaSab, idProject, state, idCostGroupBonos, idFinalCurrency, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetDatoReal_BonosAsync(ByVal idPlantaSab As Integer, ByVal idProject As String, ByVal state As String, ByVal idCostGroupBonos As Integer, ByVal idFinalCurrency As Integer, ByVal userState As Object)
            If (Me.GetDatoReal_BonosOperationCompleted Is Nothing) Then
                Me.GetDatoReal_BonosOperationCompleted = AddressOf Me.OnGetDatoReal_BonosOperationCompleted
            End If
            Me.InvokeAsync("GetDatoReal_Bonos", New Object() {idPlantaSab, idProject, state, idCostGroupBonos, idFinalCurrency}, Me.GetDatoReal_BonosOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetDatoReal_BonosOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetDatoReal_BonosCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetDatoReal_BonosCompleted(Me, New GetDatoReal_BonosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetQuantityInOtherCurrency", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetQuantityInOtherCurrency(ByVal qty As Decimal, ByVal changeDate As Date, ByVal idCurrencyOrigen As Integer, ByVal idCurrencyDestino As Integer) As String
            Dim results() As Object = Me.Invoke("GetQuantityInOtherCurrency", New Object() {qty, changeDate, idCurrencyOrigen, idCurrencyDestino})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetQuantityInOtherCurrencyAsync(ByVal qty As Decimal, ByVal changeDate As Date, ByVal idCurrencyOrigen As Integer, ByVal idCurrencyDestino As Integer)
            Me.GetQuantityInOtherCurrencyAsync(qty, changeDate, idCurrencyOrigen, idCurrencyDestino, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetQuantityInOtherCurrencyAsync(ByVal qty As Decimal, ByVal changeDate As Date, ByVal idCurrencyOrigen As Integer, ByVal idCurrencyDestino As Integer, ByVal userState As Object)
            If (Me.GetQuantityInOtherCurrencyOperationCompleted Is Nothing) Then
                Me.GetQuantityInOtherCurrencyOperationCompleted = AddressOf Me.OnGetQuantityInOtherCurrencyOperationCompleted
            End If
            Me.InvokeAsync("GetQuantityInOtherCurrency", New Object() {qty, changeDate, idCurrencyOrigen, idCurrencyDestino}, Me.GetQuantityInOtherCurrencyOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetQuantityInOtherCurrencyOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetQuantityInOtherCurrencyCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetQuantityInOtherCurrencyCompleted(Me, New GetQuantityInOtherCurrencyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetOfferExchange", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetOfferExchange(ByVal changeDate As Date, ByVal idCurrencyOrigen As Integer, ByVal idCurrencyDestino As Integer) As Decimal
            Dim results() As Object = Me.Invoke("GetOfferExchange", New Object() {changeDate, idCurrencyOrigen, idCurrencyDestino})
            Return CType(results(0),Decimal)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetOfferExchangeAsync(ByVal changeDate As Date, ByVal idCurrencyOrigen As Integer, ByVal idCurrencyDestino As Integer)
            Me.GetOfferExchangeAsync(changeDate, idCurrencyOrigen, idCurrencyDestino, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetOfferExchangeAsync(ByVal changeDate As Date, ByVal idCurrencyOrigen As Integer, ByVal idCurrencyDestino As Integer, ByVal userState As Object)
            If (Me.GetOfferExchangeOperationCompleted Is Nothing) Then
                Me.GetOfferExchangeOperationCompleted = AddressOf Me.OnGetOfferExchangeOperationCompleted
            End If
            Me.InvokeAsync("GetOfferExchange", New Object() {changeDate, idCurrencyOrigen, idCurrencyDestino}, Me.GetOfferExchangeOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetOfferExchangeOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetOfferExchangeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetOfferExchangeCompleted(Me, New GetOfferExchangeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFactoryCurrencyOffer", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetFactoryCurrencyOffer(ByVal idPlanta As Integer) As Integer
            Dim results() As Object = Me.Invoke("GetFactoryCurrencyOffer", New Object() {idPlanta})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetFactoryCurrencyOfferAsync(ByVal idPlanta As Integer)
            Me.GetFactoryCurrencyOfferAsync(idPlanta, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetFactoryCurrencyOfferAsync(ByVal idPlanta As Integer, ByVal userState As Object)
            If (Me.GetFactoryCurrencyOfferOperationCompleted Is Nothing) Then
                Me.GetFactoryCurrencyOfferOperationCompleted = AddressOf Me.OnGetFactoryCurrencyOfferOperationCompleted
            End If
            Me.InvokeAsync("GetFactoryCurrencyOffer", New Object() {idPlanta}, Me.GetFactoryCurrencyOfferOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetFactoryCurrencyOfferOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetFactoryCurrencyOfferCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetFactoryCurrencyOfferCompleted(Me, New GetFactoryCurrencyOfferCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCurrencyExchangeRateInDate", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetCurrencyExchangeRateInDate(ByVal idCurrency As Integer, ByVal changeDate As Date) As String
            Dim results() As Object = Me.Invoke("GetCurrencyExchangeRateInDate", New Object() {idCurrency, changeDate})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetCurrencyExchangeRateInDateAsync(ByVal idCurrency As Integer, ByVal changeDate As Date)
            Me.GetCurrencyExchangeRateInDateAsync(idCurrency, changeDate, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetCurrencyExchangeRateInDateAsync(ByVal idCurrency As Integer, ByVal changeDate As Date, ByVal userState As Object)
            If (Me.GetCurrencyExchangeRateInDateOperationCompleted Is Nothing) Then
                Me.GetCurrencyExchangeRateInDateOperationCompleted = AddressOf Me.OnGetCurrencyExchangeRateInDateOperationCompleted
            End If
            Me.InvokeAsync("GetCurrencyExchangeRateInDate", New Object() {idCurrency, changeDate}, Me.GetCurrencyExchangeRateInDateOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetCurrencyExchangeRateInDateOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetCurrencyExchangeRateInDateCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetCurrencyExchangeRateInDateCompleted(Me, New GetCurrencyExchangeRateInDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetProductsIsProductManager", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetProductsIsProductManager(ByVal idUserSab As Integer) As String
            Dim results() As Object = Me.Invoke("GetProductsIsProductManager", New Object() {idUserSab})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetProductsIsProductManagerAsync(ByVal idUserSab As Integer)
            Me.GetProductsIsProductManagerAsync(idUserSab, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetProductsIsProductManagerAsync(ByVal idUserSab As Integer, ByVal userState As Object)
            If (Me.GetProductsIsProductManagerOperationCompleted Is Nothing) Then
                Me.GetProductsIsProductManagerOperationCompleted = AddressOf Me.OnGetProductsIsProductManagerOperationCompleted
            End If
            Me.InvokeAsync("GetProductsIsProductManager", New Object() {idUserSab}, Me.GetProductsIsProductManagerOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetProductsIsProductManagerOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetProductsIsProductManagerCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetProductsIsProductManagerCompleted(Me, New GetProductsIsProductManagerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetProductManagers", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetProductManagers(ByVal producto As String) As String
            Dim results() As Object = Me.Invoke("GetProductManagers", New Object() {producto})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetProductManagersAsync(ByVal producto As String)
            Me.GetProductManagersAsync(producto, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetProductManagersAsync(ByVal producto As String, ByVal userState As Object)
            If (Me.GetProductManagersOperationCompleted Is Nothing) Then
                Me.GetProductManagersOperationCompleted = AddressOf Me.OnGetProductManagersOperationCompleted
            End If
            Me.InvokeAsync("GetProductManagers", New Object() {producto}, Me.GetProductManagersOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetProductManagersOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetProductManagersCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetProductManagersCompleted(Me, New GetProductManagersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFactoriesIsGerente", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetFactoriesIsGerente(ByVal idUserSab As Integer) As String
            Dim results() As Object = Me.Invoke("GetFactoriesIsGerente", New Object() {idUserSab})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetFactoriesIsGerenteAsync(ByVal idUserSab As Integer)
            Me.GetFactoriesIsGerenteAsync(idUserSab, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetFactoriesIsGerenteAsync(ByVal idUserSab As Integer, ByVal userState As Object)
            If (Me.GetFactoriesIsGerenteOperationCompleted Is Nothing) Then
                Me.GetFactoriesIsGerenteOperationCompleted = AddressOf Me.OnGetFactoriesIsGerenteOperationCompleted
            End If
            Me.InvokeAsync("GetFactoriesIsGerente", New Object() {idUserSab}, Me.GetFactoriesIsGerenteOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetFactoriesIsGerenteOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetFactoriesIsGerenteCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetFactoriesIsGerenteCompleted(Me, New GetFactoriesIsGerenteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetGerente", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetGerente(ByVal idPlantaSab As Integer) As String
            Dim results() As Object = Me.Invoke("GetGerente", New Object() {idPlantaSab})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetGerenteAsync(ByVal idPlantaSab As Integer)
            Me.GetGerenteAsync(idPlantaSab, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetGerenteAsync(ByVal idPlantaSab As Integer, ByVal userState As Object)
            If (Me.GetGerenteOperationCompleted Is Nothing) Then
                Me.GetGerenteOperationCompleted = AddressOf Me.OnGetGerenteOperationCompleted
            End If
            Me.InvokeAsync("GetGerente", New Object() {idPlantaSab}, Me.GetGerenteOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetGerenteOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetGerenteCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetGerenteCompleted(Me, New GetGerenteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetGerentes", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetGerentes() As String
            Dim results() As Object = Me.Invoke("GetGerentes", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetGerentesAsync()
            Me.GetGerentesAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetGerentesAsync(ByVal userState As Object)
            If (Me.GetGerentesOperationCompleted Is Nothing) Then
                Me.GetGerentesOperationCompleted = AddressOf Me.OnGetGerentesOperationCompleted
            End If
            Me.InvokeAsync("GetGerentes", New Object(-1) {}, Me.GetGerentesOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetGerentesOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetGerentesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetGerentesCompleted(Me, New GetGerentesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub GetProductsCompletedEventHandler(ByVal sender As Object, ByVal e As GetProductsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetProductsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub GetProjectsCompletedEventHandler(ByVal sender As Object, ByVal e As GetProjectsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetProjectsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub GetProjectFactoriesCompletedEventHandler(ByVal sender As Object, ByVal e As GetProjectFactoriesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetProjectFactoriesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub GetActiveOfferCompletedEventHandler(ByVal sender As Object, ByVal e As GetActiveOfferCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetActiveOfferCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub GetStepsFromTechnicalOfferCompletedEventHandler(ByVal sender As Object, ByVal e As GetStepsFromTechnicalOfferCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetStepsFromTechnicalOfferCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub GetDatoReal_XPERTCompletedEventHandler(ByVal sender As Object, ByVal e As GetDatoReal_XPERTCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetDatoReal_XPERTCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub GetDatoReal_BonosCompletedEventHandler(ByVal sender As Object, ByVal e As GetDatoReal_BonosCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetDatoReal_BonosCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub GetQuantityInOtherCurrencyCompletedEventHandler(ByVal sender As Object, ByVal e As GetQuantityInOtherCurrencyCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetQuantityInOtherCurrencyCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub GetOfferExchangeCompletedEventHandler(ByVal sender As Object, ByVal e As GetOfferExchangeCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetOfferExchangeCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Decimal
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Decimal)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub GetFactoryCurrencyOfferCompletedEventHandler(ByVal sender As Object, ByVal e As GetFactoryCurrencyOfferCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetFactoryCurrencyOfferCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub GetCurrencyExchangeRateInDateCompletedEventHandler(ByVal sender As Object, ByVal e As GetCurrencyExchangeRateInDateCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetCurrencyExchangeRateInDateCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub GetProductsIsProductManagerCompletedEventHandler(ByVal sender As Object, ByVal e As GetProductsIsProductManagerCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetProductsIsProductManagerCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub GetProductManagersCompletedEventHandler(ByVal sender As Object, ByVal e As GetProductManagersCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetProductManagersCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub GetFactoriesIsGerenteCompletedEventHandler(ByVal sender As Object, ByVal e As GetFactoriesIsGerenteCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetFactoriesIsGerenteCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub GetGerenteCompletedEventHandler(ByVal sender As Object, ByVal e As GetGerenteCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetGerenteCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub GetGerentesCompletedEventHandler(ByVal sender As Object, ByVal e As GetGerentesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetGerentesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
