'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CATEGORIAS
    Public Property ID_CONVENIO As String
    Public Property ID_CATEGORIA As String
    Public Property D_CATEGORIA As String
    Public Property GR_COT As String
    Public Property ID_EPIGRAFE As String
    Public Property CL_TRABAJO As String
    Public Property CL_COTIZACION As String
    Public Property T_ANTIGUEDAD As String
    Public Property O_ANTIG As String
    Public Property ID_CATEGORIA_RH As String
    Public Property Grupo As String
    Public Property ID As Integer
    Public Property GCROWVER As Nullable(Of Date)
    Public Property TANT_F_INDEP As String

    Public Overridable Property CONVENIOS As CONVENIOS
    Public Overridable Property TRABAJADORES As ICollection(Of TRABAJADORES) = New HashSet(Of TRABAJADORES)

End Class
