'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class COD_TRA
    Public Property ID_EMPRESA As String
    Public Property ID_TRABAJADOR As String
    Public Property NIF As String
    Public Property ID As Integer
    Public Property GCROWVER As Date

    Public Overridable Property TRABAJADORES As ICollection(Of TRABAJADORES) = New HashSet(Of TRABAJADORES)
    Public Overridable Property PERSONAS As PERSONAS

End Class
