'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CONVENIOS
    Public Property ID_CONVENIO As String
    Public Property ID_PAR As String
    Public Property D_CONVENIO As String
    Public Property F_ULTREV As Nullable(Of Date)
    Public Property F_PROXVTO As Nullable(Of Date)
    Public Property HORAS_ANUALES As Nullable(Of Decimal)
    Public Property HORAS_SEMANALES As Nullable(Of Decimal)
    Public Property NUM_MENSUAL As Nullable(Of Decimal)
    Public Property CL_ANTIGUEDAD As String
    Public Property MES_ANTIGCOMP As Nullable(Of Decimal)
    Public Property M_OBS_CONV As String
    Public Property M_CALENDLAB As String
    Public Property T_ANTIGUEDAD As String
    Public Property CONV_COLECTIVO As String
    Public Property ID As Integer
    Public Property GCROWVER As Nullable(Of Date)
    Public Property TANT_F_INDEP As String
    Public Property CONV_ADMIN As String
    Public Property Jornadas_Semana As Nullable(Of Decimal)

    Public Overridable Property CATEGORIAS As ICollection(Of CATEGORIAS) = New HashSet(Of CATEGORIAS)

End Class
