'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class Entities_Epsilon
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=Entities_Epsilon")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property CATEGORIAS() As DbSet(Of CATEGORIAS)
    Public Overridable Property COD_TRA() As DbSet(Of COD_TRA)
    Public Overridable Property CONVENIOS() As DbSet(Of CONVENIOS)
    Public Overridable Property TRABAJADORES() As DbSet(Of TRABAJADORES)
    Public Overridable Property PERSONAS() As DbSet(Of PERSONAS)
    Public Overridable Property ORDEN() As DbSet(Of ORDEN)
    Public Overridable Property PUES_TRAB() As DbSet(Of PUES_TRAB)
    Public Overridable Property NIV_ORG() As DbSet(Of NIV_ORG)

End Class
