'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class NIV_ORG
    Public Property ID_ORGANIG As String
    Public Property ID_NIVEL As String
    Public Property CATEG_NIVEL As String
    Public Property ES_PUESTO As String
    Public Property D_NIVEL As String
    Public Property F_INHABILITACION As Nullable(Of Date)
    Public Property F_CREACION As Date
    Public Property IDENT_NIVEL As String
    Public Property NPLAZAS As Nullable(Of Decimal)
    Public Property ID_EMPRESA As String
    Public Property ID_PUESTO As String
    Public Property N_PLAZA As Nullable(Of Decimal)
    Public Property COD_ELEM As String
    Public Property RSV_PUESTO As String
    Public Property ID_EMP_RSV As String
    Public Property ID_PUE_RSV As String
    Public Property ID As Integer
    Public Property GCROWVER As Nullable(Of Date)
    Public Property ID_COMBI As Nullable(Of Decimal)
    Public Property T_RESPONSABLE As String

    Public Overridable Property ORDEN As ORDEN
    Public Overridable Property PUES_TRAB As ICollection(Of PUES_TRAB) = New HashSet(Of PUES_TRAB)

End Class
