'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ORDEN
    Public Property ID_ORGANIG As String
    Public Property ID_NIVEL_HIJO As String
    Public Property NIVEL As Decimal
    Public Property CAMINO As String
    Public Property N1 As String
    Public Property N2 As String
    Public Property N3 As String
    Public Property N4 As String
    Public Property N5 As String
    Public Property N6 As String
    Public Property N7 As String
    Public Property N8 As String
    Public Property N9 As String
    Public Property N10 As String

    Public Overridable Property NIV_ORG As NIV_ORG

End Class
