'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PERSONAS
    Public Property NIF As String
    Public Property ID_PF As String
    Public Property APELLIDO1 As String
    Public Property APELLIDO2 As String
    Public Property NOMBRE As String
    Public Property SIGLAS As String
    Public Property DOMICILIO As String
    Public Property NUM As String
    Public Property KM As String
    Public Property ESCALERA As String
    Public Property PISO As String
    Public Property PUERTA As String
    Public Property CPOSTAL As String
    Public Property ID_PROVINCIA As String
    Public Property ID_POBLACION As String
    Public Property PREFIJO1 As String
    Public Property TELEFONO1 As String
    Public Property PREFIJO2 As String
    Public Property TELEFONO2 As String
    Public Property ID_PAIS As String
    Public Property SEXO As String
    Public Property MINUSV As String
    Public Property E_CIVIL As String
    Public Property F_NAC As Nullable(Of Date)
    Public Property ID_PROVINCIA_NAC As String
    Public Property ID_POBLACION_NAC As String
    Public Property ID_N_ESTUDIOS As String
    Public Property NASS As String
    Public Property ID_S_MILITAR As String
    Public Property CURSO As String
    Public Property ID_SIT_FAM As String
    Public Property ID_SIT_LAB_PER As String
    Public Property F_N_ESTUDIOS As Nullable(Of Date)
    Public Property MATRICULA As String
    Public Property FAX As String
    Public Property PREFAX As String
    Public Property VEHICULO As String
    Public Property NIVOTRO As String
    Public Property NIVEXP As String
    Public Property NIVIDIOM As String
    Public Property NIVINF As String
    Public Property NIVCUR As String
    Public Property EMAIL As String
    Public Property RESIDENTE As String
    Public Property NIVEL_R As String
    Public Property ID As Integer
    Public Property GCROWVER As Nullable(Of Date)
    Public Property F_ALTA_PP As Nullable(Of Date)
    Public Property DOMIC_PP As String
    Public Property F_DOMIC_PP As Nullable(Of Date)
    Public Property N_MUFACE As String
    Public Property TELEF_EMERG As String
    Public Property ID_ATEP As String
    Public Property ID_PAIS_NAC As String
    Public Property N_ASANIT As String
    Public Property Ejec_Hipoteca As String
    Public Property email2 As String
    Public Property clv_pdf As String
    Public Property GRADO_MINUSVALIA As Nullable(Of Decimal)
    Public Property ES_FAMILIA_NUMEROSA As String

    Public Overridable Property COD_TRA As ICollection(Of COD_TRA) = New HashSet(Of COD_TRA)

End Class
