'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PUES_TRAB
    Public Property ID_EMPRESA As String
    Public Property ID_TRABAJADOR As String
    Public Property ID_ORGANIG As String
    Public Property ID_NIVEL As String
    Public Property P_PUESTO As Decimal
    Public Property ID_SECUENCIA As String
    Public Property PUES_DEFECTO As String
    Public Property F_INI_PUE As Date
    Public Property F_FIN_PUE As Nullable(Of Date)
    Public Property I_HORAS As Nullable(Of Decimal)
    Public Property T_OPERARIO As String
    Public Property COMENTARIO As String
    Public Property ID As Integer
    Public Property GCROWVER As Nullable(Of Date)
    Public Property ID_TRAB_SUST As String
    Public Property ID_EMP_SUST As String
    Public Property N_APUNTE As Nullable(Of Decimal)
    Public Property ID_OBSERV_COD As String

    Public Overridable Property TRABAJADORES As TRABAJADORES
    Public Overridable Property NIV_ORG As NIV_ORG

End Class
