'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TRABAJADORES
    Public Property ID_EMPRESA As String
    Public Property ID_TRABAJADOR As String
    Public Property ID_SECUENCIA As String
    Public Property CCC As String
    Public Property ID_CENTRO As String
    Public Property MATRICULA As String
    Public Property HORAS_TC2 As Nullable(Of Decimal)
    Public Property PER_IT As Nullable(Of Decimal)
    Public Property PUESTO As String
    Public Property ID_CONVENIO As String
    Public Property ID_CATEGORIA As String
    Public Property ID_CAT_ALT As String
    Public Property GR_COT As String
    Public Property ID_EPIGRAFE As String
    Public Property CL_DES_EPI As String
    Public Property NUM_HIJOS As Nullable(Of Decimal)
    Public Property P_RED As Nullable(Of Decimal)
    Public Property CL_ACT_IRPF As String
    Public Property CL_CAL_IRPF As String
    Public Property P_DIN As Nullable(Of Decimal)
    Public Property P_ESP As Nullable(Of Decimal)
    Public Property F_ANTIG As Nullable(Of Date)
    Public Property F_C_ANTIG As Nullable(Of Date)
    Public Property IMP_ANT As Nullable(Of Decimal)
    Public Property GR_COT_PLUR As String
    Public Property PLU_CCMIN As Nullable(Of Decimal)
    Public Property PLU_CCMAX As Nullable(Of Decimal)
    Public Property PLU_ACCMIN As Nullable(Of Decimal)
    Public Property PLU_ACCMAX As Nullable(Of Decimal)
    Public Property NUM_PLUR As String
    Public Property D_EMPPLUR As String
    Public Property P_JORNADA As Nullable(Of Decimal)
    Public Property DIAS_JOR As Nullable(Of Decimal)
    Public Property JOR_LUNES As Nullable(Of Decimal)
    Public Property JOR_MARTES As Nullable(Of Decimal)
    Public Property JOR_MIERCOLES As Nullable(Of Decimal)
    Public Property JOR_JUEVES As Nullable(Of Decimal)
    Public Property JOR_VIERNES As Nullable(Of Decimal)
    Public Property JOR_SABADO As Nullable(Of Decimal)
    Public Property JOR_DOMINGO As Nullable(Of Decimal)
    Public Property AFECTA_JOR As String
    Public Property AFECTA_HOR As String
    Public Property NUM_CAL As Nullable(Of Decimal)
    Public Property GUARDA_LEGAL As String
    Public Property ID_TPAGAS As String
    Public Property GPO_PROFES As String
    Public Property CL_REGTRA As String
    Public Property CL_AGRCOO As String
    Public Property CL_TRABAJO As String
    Public Property CL_COTIZACION As String
    Public Property CL_RETRIBUCION As String
    Public Property CL_COBRO As String
    Public Property CL_COBRO_ANT As String
    Public Property ID_DIVISA As String
    Public Property ID_C_SIND As String
    Public Property CL_AUSENCIAS As String
    Public Property CL_COMPL_NEG As String
    Public Property CL_P_IRPF As String
    Public Property F_ALTA As Nullable(Of Date)
    Public Property F_INI_SEC As Date
    Public Property F_BAJA As Nullable(Of Date)
    Public Property ID_BAJA As String
    Public Property SITUACION As String
    Public Property ID_CONTRATO As String
    Public Property F_BONIF As Nullable(Of Date)
    Public Property F_RESOL As Nullable(Of Date)
    Public Property F_INI_SUB As Nullable(Of Date)
    Public Property F_FIN_SUB As Nullable(Of Date)
    Public Property LOCAL_OFEMP As String
    Public Property N_REGISTRO As String
    Public Property F_OFEMP As Nullable(Of Date)
    Public Property F_INDEFINIDO As Nullable(Of Date)
    Public Property C_CONTRATO As String
    Public Property TRAB_OBSERV As String
    Public Property ID_BANCO As String
    Public Property ID_SUCURSAL As String
    Public Property ID_CUENTA As String
    Public Property CL_REC_FIN As String
    Public Property CL_DESG_FIN As String
    Public Property CL_PERIODO_CONT As String
    Public Property HORAS_CONTRATO As Nullable(Of Decimal)
    Public Property HORA_INIC_SEC As Nullable(Of Date)
    Public Property CL_SAL_IT As String
    Public Property F_AUT_PLUR As Nullable(Of Date)
    Public Property TIP_DES As String
    Public Property CL_RET_ATRASOS As String
    Public Property ID_PER_ADM As String
    Public Property ID_ORGANICA As String
    Public Property ID_FUNCION As String
    Public Property ID_TURNO As String
    Public Property N_TARJETA As String
    Public Property GRUPO As String
    Public Property NIVEL As Nullable(Of Decimal)
    Public Property ID_CPL_ESPECIFICO As String
    Public Property CL_COT_DUR As String
    Public Property COLECTIVO1 As String
    Public Property COLECTIVO2 As String
    Public Property COLECTIVO3 As String
    Public Property COLECTIVO4 As String
    Public Property P_IRPF_SOLIC As Nullable(Of Decimal)
    Public Property MESES_ANTIG As Nullable(Of Decimal)
    Public Property DIAS_ANTIG As Nullable(Of Decimal)
    Public Property EJERS_ANTIG As Nullable(Of Decimal)
    Public Property CL_JORNADA As String
    Public Property ID_PROYECTO As String
    Public Property ID As Integer
    Public Property GCROWVER As Nullable(Of Date)
    Public Property ID_HABILITACION As String
    Public Property ID_EMBARCACION As String
    Public Property ID_MAREA As String
    Public Property ORDEN_EMBARCO As String
    Public Property ID_CL_NOMINA As String
    Public Property ID_AGRNOM As String
    Public Property TRI_RC_1 As Nullable(Of Decimal)
    Public Property TRI_RC_2 As Nullable(Of Decimal)
    Public Property TRI_RC_3 As Nullable(Of Decimal)
    Public Property TRI_RC_4 As Nullable(Of Decimal)
    Public Property TRI_RC_5 As Nullable(Of Decimal)
    Public Property TRI_LAB As Nullable(Of Decimal)
    Public Property CL_APLPORCENTAJE As String
    Public Property CL_COBRO_MES As String
    Public Property HOR_COMPL As Nullable(Of Decimal)
    Public Property RESIDENTE As String
    Public Property CL_GESTANTFUN As String
    Public Property OCUPACION_INEM As String
    Public Property TRI_RC_6 As Nullable(Of Decimal)
    Public Property F_FIN_PRUEBA As Nullable(Of Date)
    Public Property id_t_lagunaro As String

    Public Overridable Property CATEGORIAS As CATEGORIAS
    Public Overridable Property COD_TRA As COD_TRA
    Public Overridable Property PUES_TRAB As ICollection(Of PUES_TRAB) = New HashSet(Of PUES_TRAB)

End Class
