
'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization


<Assembly: EdmSchemaAttribute("0d922ac0-8647-4763-af73-7cfcba54e8ad")>
#Region "Metadatos de relaciones en EDM"
<Assembly: EdmRelationshipAttribute("XBAT_BBDD", "ASSET_ASSET", "ASSET", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(ASSET), "ASSET1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(ASSET), True)>

#End Region

#Region "Contextos"

''' <summary>
''' No hay documentación de metadatos disponible.
''' </summary>
Public Partial Class Entities_Prisma
    Inherits ObjectContext

    #Region "Constructores"

    ''' <summary>
    ''' Inicializa un nuevo objeto Entities_Prisma usando la cadena de conexión encontrada en la sección 'Entities_Prisma' del archivo de configuración de la aplicación.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=Entities_Prisma", "Entities_Prisma")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Inicializar un nuevo objeto Entities_Prisma.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "Entities_Prisma")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Inicializar un nuevo objeto Entities_Prisma.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "Entities_Prisma")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Métodos parciales"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "Propiedades de ObjectSet"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    Public ReadOnly Property ASSET() As ObjectSet(Of ASSET)
        Get
            If (_ASSET Is Nothing) Then
                _ASSET = MyBase.CreateObjectSet(Of ASSET)("ASSET")
            End If
            Return _ASSET
        End Get
    End Property

    Private _ASSET As ObjectSet(Of ASSET)

    #End Region

    #Region "Métodos AddTo"

    ''' <summary>
    ''' Método desusado para agregar un nuevo objeto al EntitySet ASSET. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet(Of T) asociada.
    ''' </summary>
    Public Sub AddToASSET(ByVal aSSET As ASSET)
        MyBase.AddObject("ASSET", aSSET)
    End Sub

    #End Region

End Class

#End Region

#Region "Entidades"

''' <summary>
''' No hay documentación de metadatos disponible.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="XBAT_BBDD", Name:="ASSET")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class ASSET
    Inherits EntityObject
    #Region "Método de generador"

    ''' <summary>
    ''' Crear un nuevo objeto ASSET.
    ''' </summary>
    ''' <param name="cOMPANY">Valor inicial de la propiedad COMPANY.</param>
    ''' <param name="aSSET1">Valor inicial de la propiedad ASSET1.</param>
    ''' <param name="aSSETNAME">Valor inicial de la propiedad ASSETNAME.</param>
    ''' <param name="eQUIPMENTTYPE">Valor inicial de la propiedad EQUIPMENTTYPE.</param>
    ''' <param name="bUSINESSUNIT">Valor inicial de la propiedad BUSINESSUNIT.</param>
    ''' <param name="cOMPANYLEVEL">Valor inicial de la propiedad COMPANYLEVEL.</param>
    ''' <param name="pRIORITY">Valor inicial de la propiedad PRIORITY.</param>
    ''' <param name="eQUIPMENTSTATE">Valor inicial de la propiedad EQUIPMENTSTATE.</param>
    ''' <param name="rECORDSTATE">Valor inicial de la propiedad RECORDSTATE.</param>
    Public Shared Function CreateASSET(cOMPANY As Global.System.String, aSSET1 As Global.System.String, aSSETNAME As Global.System.String, eQUIPMENTTYPE As Global.System.String, bUSINESSUNIT As Global.System.String, cOMPANYLEVEL As Global.System.Int16, pRIORITY As Global.System.Int16, eQUIPMENTSTATE As Global.System.String, rECORDSTATE As Global.System.String) As ASSET
        Dim aSSET as ASSET = New ASSET
        aSSET.COMPANY = cOMPANY
        aSSET.ASSET1 = aSSET1
        aSSET.ASSETNAME = aSSETNAME
        aSSET.EQUIPMENTTYPE = eQUIPMENTTYPE
        aSSET.BUSINESSUNIT = bUSINESSUNIT
        aSSET.COMPANYLEVEL = cOMPANYLEVEL
        aSSET.PRIORITY = pRIORITY
        aSSET.EQUIPMENTSTATE = eQUIPMENTSTATE
        aSSET.RECORDSTATE = rECORDSTATE
        Return aSSET
    End Function

    #End Region

    #Region "Propiedades primitivas"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property COMPANY() As Global.System.String
        Get
            Return _COMPANY
        End Get
        Set
            If (_COMPANY <> Value) Then
                OnCOMPANYChanging(value)
                ReportPropertyChanging("COMPANY")
                _COMPANY = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("COMPANY")
                OnCOMPANYChanged()
            End If
        End Set
    End Property

    Private _COMPANY As Global.System.String
    Private Partial Sub OnCOMPANYChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCOMPANYChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ASSET1() As Global.System.String
        Get
            Return _ASSET1
        End Get
        Set
            If (_ASSET1 <> Value) Then
                OnASSET1Changing(value)
                ReportPropertyChanging("ASSET1")
                _ASSET1 = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("ASSET1")
                OnASSET1Changed()
            End If
        End Set
    End Property

    Private _ASSET1 As Global.System.String
    Private Partial Sub OnASSET1Changing(value As Global.System.String)
    End Sub

    Private Partial Sub OnASSET1Changed()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ASSETNAME() As Global.System.String
        Get
            Return _ASSETNAME
        End Get
        Set
            OnASSETNAMEChanging(value)
            ReportPropertyChanging("ASSETNAME")
            _ASSETNAME = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("ASSETNAME")
            OnASSETNAMEChanged()
        End Set
    End Property

    Private _ASSETNAME As Global.System.String
    Private Partial Sub OnASSETNAMEChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnASSETNAMEChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property EQUIPMENTTYPE() As Global.System.String
        Get
            Return _EQUIPMENTTYPE
        End Get
        Set
            OnEQUIPMENTTYPEChanging(value)
            ReportPropertyChanging("EQUIPMENTTYPE")
            _EQUIPMENTTYPE = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("EQUIPMENTTYPE")
            OnEQUIPMENTTYPEChanged()
        End Set
    End Property

    Private _EQUIPMENTTYPE As Global.System.String
    Private Partial Sub OnEQUIPMENTTYPEChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnEQUIPMENTTYPEChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property BUSINESSUNIT() As Global.System.String
        Get
            Return _BUSINESSUNIT
        End Get
        Set
            OnBUSINESSUNITChanging(value)
            ReportPropertyChanging("BUSINESSUNIT")
            _BUSINESSUNIT = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("BUSINESSUNIT")
            OnBUSINESSUNITChanged()
        End Set
    End Property

    Private _BUSINESSUNIT As Global.System.String
    Private Partial Sub OnBUSINESSUNITChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnBUSINESSUNITChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property PARENTASSET() As Global.System.String
        Get
            Return _PARENTASSET
        End Get
        Set
            OnPARENTASSETChanging(value)
            ReportPropertyChanging("PARENTASSET")
            _PARENTASSET = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("PARENTASSET")
            OnPARENTASSETChanged()
        End Set
    End Property

    Private _PARENTASSET As Global.System.String
    Private Partial Sub OnPARENTASSETChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnPARENTASSETChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property COMPANYLEVEL() As Global.System.Int16
        Get
            Return _COMPANYLEVEL
        End Get
        Set
            OnCOMPANYLEVELChanging(value)
            ReportPropertyChanging("COMPANYLEVEL")
            _COMPANYLEVEL = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("COMPANYLEVEL")
            OnCOMPANYLEVELChanged()
        End Set
    End Property

    Private _COMPANYLEVEL As Global.System.Int16
    Private Partial Sub OnCOMPANYLEVELChanging(value As Global.System.Int16)
    End Sub

    Private Partial Sub OnCOMPANYLEVELChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property LOCATION() As Global.System.String
        Get
            Return _LOCATION
        End Get
        Set
            OnLOCATIONChanging(value)
            ReportPropertyChanging("LOCATION")
            _LOCATION = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("LOCATION")
            OnLOCATIONChanged()
        End Set
    End Property

    Private _LOCATION As Global.System.String
    Private Partial Sub OnLOCATIONChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnLOCATIONChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property CUSTOMER() As Global.System.String
        Get
            Return _CUSTOMER
        End Get
        Set
            OnCUSTOMERChanging(value)
            ReportPropertyChanging("CUSTOMER")
            _CUSTOMER = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("CUSTOMER")
            OnCUSTOMERChanged()
        End Set
    End Property

    Private _CUSTOMER As Global.System.String
    Private Partial Sub OnCUSTOMERChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCUSTOMERChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property PRIORITY() As Global.System.Int16
        Get
            Return _PRIORITY
        End Get
        Set
            OnPRIORITYChanging(value)
            ReportPropertyChanging("PRIORITY")
            _PRIORITY = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("PRIORITY")
            OnPRIORITYChanged()
        End Set
    End Property

    Private _PRIORITY As Global.System.Int16
    Private Partial Sub OnPRIORITYChanging(value As Global.System.Int16)
    End Sub

    Private Partial Sub OnPRIORITYChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property EQUIPMENT() As Global.System.String
        Get
            Return _EQUIPMENT
        End Get
        Set
            OnEQUIPMENTChanging(value)
            ReportPropertyChanging("EQUIPMENT")
            _EQUIPMENT = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("EQUIPMENT")
            OnEQUIPMENTChanged()
        End Set
    End Property

    Private _EQUIPMENT As Global.System.String
    Private Partial Sub OnEQUIPMENTChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnEQUIPMENTChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property EQUIPMENTASSOCDATE() As Nullable(Of Global.System.DateTime)
        Get
            Return _EQUIPMENTASSOCDATE
        End Get
        Set
            OnEQUIPMENTASSOCDATEChanging(value)
            ReportPropertyChanging("EQUIPMENTASSOCDATE")
            _EQUIPMENTASSOCDATE = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("EQUIPMENTASSOCDATE")
            OnEQUIPMENTASSOCDATEChanged()
        End Set
    End Property

    Private _EQUIPMENTASSOCDATE As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnEQUIPMENTASSOCDATEChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnEQUIPMENTASSOCDATEChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property EQUIPMENTSTATE() As Global.System.String
        Get
            Return _EQUIPMENTSTATE
        End Get
        Set
            OnEQUIPMENTSTATEChanging(value)
            ReportPropertyChanging("EQUIPMENTSTATE")
            _EQUIPMENTSTATE = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("EQUIPMENTSTATE")
            OnEQUIPMENTSTATEChanged()
        End Set
    End Property

    Private _EQUIPMENTSTATE As Global.System.String
    Private Partial Sub OnEQUIPMENTSTATEChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnEQUIPMENTSTATEChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property CALENDAR() As Global.System.String
        Get
            Return _CALENDAR
        End Get
        Set
            OnCALENDARChanging(value)
            ReportPropertyChanging("CALENDAR")
            _CALENDAR = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("CALENDAR")
            OnCALENDARChanged()
        End Set
    End Property

    Private _CALENDAR As Global.System.String
    Private Partial Sub OnCALENDARChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCALENDARChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property DEFAULTWORKSHOP() As Global.System.String
        Get
            Return _DEFAULTWORKSHOP
        End Get
        Set
            OnDEFAULTWORKSHOPChanging(value)
            ReportPropertyChanging("DEFAULTWORKSHOP")
            _DEFAULTWORKSHOP = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("DEFAULTWORKSHOP")
            OnDEFAULTWORKSHOPChanged()
        End Set
    End Property

    Private _DEFAULTWORKSHOP As Global.System.String
    Private Partial Sub OnDEFAULTWORKSHOPChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnDEFAULTWORKSHOPChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property DOWNTIMEHOURRATE() As Nullable(Of Global.System.Decimal)
        Get
            Return _DOWNTIMEHOURRATE
        End Get
        Set
            OnDOWNTIMEHOURRATEChanging(value)
            ReportPropertyChanging("DOWNTIMEHOURRATE")
            _DOWNTIMEHOURRATE = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("DOWNTIMEHOURRATE")
            OnDOWNTIMEHOURRATEChanged()
        End Set
    End Property

    Private _DOWNTIMEHOURRATE As Nullable(Of Global.System.Decimal)
    Private Partial Sub OnDOWNTIMEHOURRATEChanging(value As Nullable(Of Global.System.Decimal))
    End Sub

    Private Partial Sub OnDOWNTIMEHOURRATEChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property SAFETYPLAN() As Global.System.String
        Get
            Return _SAFETYPLAN
        End Get
        Set
            OnSAFETYPLANChanging(value)
            ReportPropertyChanging("SAFETYPLAN")
            _SAFETYPLAN = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("SAFETYPLAN")
            OnSAFETYPLANChanged()
        End Set
    End Property

    Private _SAFETYPLAN As Global.System.String
    Private Partial Sub OnSAFETYPLANChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnSAFETYPLANChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property RECORDSTATE() As Global.System.String
        Get
            Return _RECORDSTATE
        End Get
        Set
            OnRECORDSTATEChanging(value)
            ReportPropertyChanging("RECORDSTATE")
            _RECORDSTATE = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("RECORDSTATE")
            OnRECORDSTATEChanged()
        End Set
    End Property

    Private _RECORDSTATE As Global.System.String
    Private Partial Sub OnRECORDSTATEChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnRECORDSTATEChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property CREATIONUSER() As Global.System.String
        Get
            Return _CREATIONUSER
        End Get
        Set
            OnCREATIONUSERChanging(value)
            ReportPropertyChanging("CREATIONUSER")
            _CREATIONUSER = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("CREATIONUSER")
            OnCREATIONUSERChanged()
        End Set
    End Property

    Private _CREATIONUSER As Global.System.String
    Private Partial Sub OnCREATIONUSERChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCREATIONUSERChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property CREATIONDATA() As Nullable(Of Global.System.DateTime)
        Get
            Return _CREATIONDATA
        End Get
        Set
            OnCREATIONDATAChanging(value)
            ReportPropertyChanging("CREATIONDATA")
            _CREATIONDATA = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("CREATIONDATA")
            OnCREATIONDATAChanged()
        End Set
    End Property

    Private _CREATIONDATA As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnCREATIONDATAChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnCREATIONDATAChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property LASTUPDATEUSER() As Global.System.String
        Get
            Return _LASTUPDATEUSER
        End Get
        Set
            OnLASTUPDATEUSERChanging(value)
            ReportPropertyChanging("LASTUPDATEUSER")
            _LASTUPDATEUSER = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("LASTUPDATEUSER")
            OnLASTUPDATEUSERChanged()
        End Set
    End Property

    Private _LASTUPDATEUSER As Global.System.String
    Private Partial Sub OnLASTUPDATEUSERChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnLASTUPDATEUSERChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property LASTUPDATEDATA() As Nullable(Of Global.System.DateTime)
        Get
            Return _LASTUPDATEDATA
        End Get
        Set
            OnLASTUPDATEDATAChanging(value)
            ReportPropertyChanging("LASTUPDATEDATA")
            _LASTUPDATEDATA = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("LASTUPDATEDATA")
            OnLASTUPDATEDATAChanged()
        End Set
    End Property

    Private _LASTUPDATEDATA As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnLASTUPDATEDATAChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnLASTUPDATEDATAChanged()
    End Sub

    #End Region

    #Region "Propiedades de navegación"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("XBAT_BBDD", "ASSET_ASSET", "ASSET1")>
     Public Property ASSET11() As EntityCollection(Of ASSET)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of ASSET)("XBAT_BBDD.ASSET_ASSET", "ASSET1")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of ASSET)("XBAT_BBDD.ASSET_ASSET", "ASSET1", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("XBAT_BBDD", "ASSET_ASSET", "ASSET")>
    Public Property ASSET2() As ASSET
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of ASSET)("XBAT_BBDD.ASSET_ASSET", "ASSET").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of ASSET)("XBAT_BBDD.ASSET_ASSET", "ASSET").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property ASSET2Reference() As EntityReference(Of ASSET)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of ASSET)("XBAT_BBDD.ASSET_ASSET", "ASSET")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of ASSET)("XBAT_BBDD.ASSET_ASSET", "ASSET", value)
            End If
        End Set
    End Property

    #End Region

End Class

#End Region


