'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CERTIFICADO
    Public Property IDCERTIFICADO As Decimal
    Public Property FECHACERTIFICADO As Nullable(Of Date)
    Public Property CERTIFICADO1 As Byte()
    Public Property NOMBRECERTF As String

End Class
