'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class GCLINPED
    Public Property NUMPEDLIN As Integer
    Public Property NUMLINLIN As Short
    Public Property CODPROLIN As String
    Public Property CODART As String
    Public Property DESCART As String
    Public Property DESCLISTA As String
    Public Property NUMORDF As Nullable(Of Integer)
    Public Property NUMOPE As Nullable(Of Short)
    Public Property NUMMAR As String
    Public Property CANPED As Nullable(Of Decimal)
    Public Property CANREC As Nullable(Of Decimal)
    Public Property CANFAC As Nullable(Of Decimal)
    Public Property PREUNI As Nullable(Of Decimal)
    Public Property DESCTO As Nullable(Of Decimal)
    Public Property ALEACION As Nullable(Of Short)
    Public Property IMPPED As Nullable(Of Decimal)
    Public Property IMPREC As Nullable(Of Decimal)
    Public Property IMPFAC As Nullable(Of Decimal)
    Public Property FECENTSOL As Nullable(Of Date)
    Public Property FECENTVIG As Date
    Public Property CODARPRO As String
    Public Property NUMNECES As Nullable(Of Integer)
    Public Property PDTE_PREC As String
    Public Property LANTEGI As Nullable(Of Short)
    Public Property LANTEGI_H As Nullable(Of Short)
    Public Property EPREUNI As Nullable(Of Decimal)
    Public Property EDIMPRE As Nullable(Of Integer)
    Public Property EALEACION As Nullable(Of Decimal)
    Public Property EIMPPED As Nullable(Of Decimal)
    Public Property EIMPREC As Nullable(Of Decimal)
    Public Property EIMPFAC As Nullable(Of Decimal)
    Public Property FECPDTEPRE As Nullable(Of Date)
    Public Property FECCALIDAD As Nullable(Of Date)
    Public Property ID_ESTADO As Nullable(Of Short)
    Public Property MATERIAL As String
    Public Property REF_PROV As String

End Class
