'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class INFORMES
    Public Property IDINFORME As Decimal
    Public Property VALOROF As String
    Public Property VALOROP As String
    Public Property MARCA As String
    Public Property CLIENTE As String
    Public Property PROYECTO As String
    Public Property NPIEZA As String
    Public Property DESCPIEZA As String
    Public Property NTROQUEL As String
    Public Property MATERIAL As String
    Public Property TRATAMSEC As String
    Public Property DUREZA As String
    Public Property TIPOINFORME As String
    Public Property FECHAINFORME As Nullable(Of Date)
    Public Property CREADOPOR As String
    Public Property TIPOSOLDADURADURO As String
    Public Property MATERIALAPORTACIONSOLDDURO As String
    Public Property MATERIALAPORTACIONSOLDBLANDO As String
    Public Property KGCONSUMIDOSSOLDDURO As String
    Public Property KGCONSUMIDOSSOLDBLANDO As String
    Public Property VARILLASOLDADURADURO As String
    Public Property VARILLASOLDADURABLANDO As String
    Public Property INTENSIDADSOLDADURADURO As String
    Public Property INTENSIDADSOLDADURABLANDO As String
    Public Property TRATAMIENTO As String
    Public Property ANTESTRATAM As String
    Public Property DESPUESTRATAM As String
    Public Property CALZO As String
    Public Property VALORCALZO As String
    Public Property LARGOCD As String
    Public Property ANCHOCD As String
    Public Property ALTOCD As String
    Public Property DUREZAREALTEMPLEMAX As String
    Public Property DUREZAREALTEMPLEMIN As String
    Public Property NUMEROMEDIDASTEMPLE As String
    Public Property TEMPERATURATEMPLE As String
    Public Property OPTICAPASO As String
    Public Property F As String
    Public Property NOTAS As String
    Public Property TIPOSOLDADURABLANDO As String
    Public Property ESTADO As String
    Public Property FECHABORRADO As Nullable(Of Date)
    Public Property BORRADOPOR As String
    Public Property METROS As String
    Public Property DUREZAREQUERIDATEMPLE As String
    Public Property VARILLASOLDADURABLANDO2 As String
    Public Property VARILLASOLDADURADURO2 As String

End Class
