'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class Entities_soldadura
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=Entities_soldadura")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property CERTIFICADO() As DbSet(Of CERTIFICADO)
    Public Overridable Property CONTIENE() As DbSet(Of CONTIENE)
    Public Overridable Property FOTOS() As DbSet(Of FOTOS)
    Public Overridable Property PESOVARILLAS() As DbSet(Of PESOVARILLAS)
    Public Overridable Property SOLDADORESINFORME() As DbSet(Of SOLDADORESINFORME)
    Public Overridable Property TIPOSOLDADURA() As DbSet(Of TIPOSOLDADURA)
    Public Overridable Property VALORESSOLDADURA() As DbSet(Of VALORESSOLDADURA)
    Public Overridable Property ABARCA() As DbSet(Of ABARCA)
    Public Overridable Property INFORME_PROVEEDOR() As DbSet(Of INFORME_PROVEEDOR)
    Public Overridable Property USUARIOS() As DbSet(Of USUARIOS)
    Public Overridable Property INFORMES() As DbSet(Of INFORMES)
    Public Overridable Property GCLINPED() As DbSet(Of GCLINPED)

End Class
