'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace ServicioTelefonia
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ServiceTelefonia1Soap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ServiceTelefonia1
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private getTelefonosOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.TarjetasVisitaLib.My.MySettings.Default.TarjetasVisitaLib_ServicioTelefonia_ServiceTelefonia1
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event getTelefonosCompleted As getTelefonosCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getTelefonos", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getTelefonos(ByVal idUser As Integer) As Telephone()
            Dim results() As Object = Me.Invoke("getTelefonos", New Object() {idUser})
            Return CType(results(0),Telephone())
        End Function
        
        '''<remarks/>
        Public Overloads Sub getTelefonosAsync(ByVal idUser As Integer)
            Me.getTelefonosAsync(idUser, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getTelefonosAsync(ByVal idUser As Integer, ByVal userState As Object)
            If (Me.getTelefonosOperationCompleted Is Nothing) Then
                Me.getTelefonosOperationCompleted = AddressOf Me.OngetTelefonosOperationCompleted
            End If
            Me.InvokeAsync("getTelefonos", New Object() {idUser}, Me.getTelefonosOperationCompleted, userState)
        End Sub
        
        Private Sub OngetTelefonosOperationCompleted(ByVal arg As Object)
            If (Not (Me.getTelefonosCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getTelefonosCompleted(Me, New getTelefonosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Telephone
        
        Private plantaField As String
        
        Private extensionFijaField As String
        
        Private fijoField As String
        
        Private extensionInalambricaField As String
        
        Private inalambricoField As String
        
        Private extensionMovilField As String
        
        Private movilField As String
        
        Private zoiperField As String

        Private idSabPlantaField As Integer

        '''<remarks/>
        Public Property Planta() As String
            Get
                Return Me.plantaField
            End Get
            Set
                Me.plantaField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ExtensionFija() As String
            Get
                Return Me.extensionFijaField
            End Get
            Set
                Me.extensionFijaField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Fijo() As String
            Get
                Return Me.fijoField
            End Get
            Set
                Me.fijoField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ExtensionInalambrica() As String
            Get
                Return Me.extensionInalambricaField
            End Get
            Set
                Me.extensionInalambricaField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Inalambrico() As String
            Get
                Return Me.inalambricoField
            End Get
            Set
                Me.inalambricoField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ExtensionMovil() As String
            Get
                Return Me.extensionMovilField
            End Get
            Set
                Me.extensionMovilField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Movil() As String
            Get
                Return Me.movilField
            End Get
            Set
                Me.movilField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Zoiper() As String
            Get
                Return Me.zoiperField
            End Get
            Set
                Me.zoiperField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property IdSabPlanta() As Integer
            Get
                Return Me.idSabPlantaField
            End Get
            Set
                Me.idSabPlantaField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")>  _
    Public Delegate Sub getTelefonosCompletedEventHandler(ByVal sender As Object, ByVal e As getTelefonosCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getTelefonosCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Telephone()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Telephone())
            End Get
        End Property
    End Class
End Namespace
