'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace ServicioBonos
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ServicioBonosSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ServicioBonos
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private AddBonoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DeleteLineaBonoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetMaquinaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetMaquinasOperationCompleted As System.Threading.SendOrPostCallback
        
        Private AddMaquinaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DeleteMaquinaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetTipoMaquinaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetTiposMaquinasOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetProjectPlantToChargesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetGrupoDistribucionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetGruposDistribucionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetDatosDistribucionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetAnyosDistribucionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetDatosDistribucionPorAnyosOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetHorasBonoGrupoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetProjectMembersByRolOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetOwnerOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetProjectInfoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private IsProjectInManagementPlantOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetProjectsAffectedOperationCompleted As System.Threading.SendOrPostCallback
        
        Private UpdateProjectCostCarrierOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TestOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.CostCarriersLib.My.MySettings.Default.CostCarriersLib_ServicioBonos_ServicioBonos
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event AddBonoCompleted As AddBonoCompletedEventHandler
        
        '''<remarks/>
        Public Event DeleteLineaBonoCompleted As DeleteLineaBonoCompletedEventHandler
        
        '''<remarks/>
        Public Event GetMaquinaCompleted As GetMaquinaCompletedEventHandler
        
        '''<remarks/>
        Public Event GetMaquinasCompleted As GetMaquinasCompletedEventHandler
        
        '''<remarks/>
        Public Event AddMaquinaCompleted As AddMaquinaCompletedEventHandler
        
        '''<remarks/>
        Public Event DeleteMaquinaCompleted As DeleteMaquinaCompletedEventHandler
        
        '''<remarks/>
        Public Event GetTipoMaquinaCompleted As GetTipoMaquinaCompletedEventHandler
        
        '''<remarks/>
        Public Event GetTiposMaquinasCompleted As GetTiposMaquinasCompletedEventHandler
        
        '''<remarks/>
        Public Event GetProjectPlantToChargesCompleted As GetProjectPlantToChargesCompletedEventHandler
        
        '''<remarks/>
        Public Event GetGrupoDistribucionCompleted As GetGrupoDistribucionCompletedEventHandler
        
        '''<remarks/>
        Public Event GetGruposDistribucionCompleted As GetGruposDistribucionCompletedEventHandler
        
        '''<remarks/>
        Public Event GetDatosDistribucionCompleted As GetDatosDistribucionCompletedEventHandler
        
        '''<remarks/>
        Public Event GetAnyosDistribucionCompleted As GetAnyosDistribucionCompletedEventHandler
        
        '''<remarks/>
        Public Event GetDatosDistribucionPorAnyosCompleted As GetDatosDistribucionPorAnyosCompletedEventHandler
        
        '''<remarks/>
        Public Event GetHorasBonoGrupoCompleted As GetHorasBonoGrupoCompletedEventHandler
        
        '''<remarks/>
        Public Event GetProjectMembersByRolCompleted As GetProjectMembersByRolCompletedEventHandler
        
        '''<remarks/>
        Public Event GetOwnerCompleted As GetOwnerCompletedEventHandler
        
        '''<remarks/>
        Public Event GetProjectInfoCompleted As GetProjectInfoCompletedEventHandler
        
        '''<remarks/>
        Public Event IsProjectInManagementPlantCompleted As IsProjectInManagementPlantCompletedEventHandler
        
        '''<remarks/>
        Public Event GetProjectsAffectedCompleted As GetProjectsAffectedCompletedEventHandler
        
        '''<remarks/>
        Public Event UpdateProjectCostCarrierCompleted As UpdateProjectCostCarrierCompletedEventHandler
        
        '''<remarks/>
        Public Event TestCompleted As TestCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddBono", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AddBono(ByVal idUsuario As Integer, ByVal idMaquina As Integer, ByVal fecha As Date, ByVal estadoBono As Integer, ByVal producto As String, ByVal proyecto As String, ByVal estadoProy As String, ByVal idActividad As Integer, ByVal horas As Decimal, ByVal procedencia As String, ByVal idIndicadorSolMed As Integer, ByRef mensaError As String) As Integer
            Dim results() As Object = Me.Invoke("AddBono", New Object() {idUsuario, idMaquina, fecha, estadoBono, producto, proyecto, estadoProy, idActividad, horas, procedencia, idIndicadorSolMed, mensaError})
            mensaError = CType(results(1),String)
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub AddBonoAsync(ByVal idUsuario As Integer, ByVal idMaquina As Integer, ByVal fecha As Date, ByVal estadoBono As Integer, ByVal producto As String, ByVal proyecto As String, ByVal estadoProy As String, ByVal idActividad As Integer, ByVal horas As Decimal, ByVal procedencia As String, ByVal idIndicadorSolMed As Integer, ByVal mensaError As String)
            Me.AddBonoAsync(idUsuario, idMaquina, fecha, estadoBono, producto, proyecto, estadoProy, idActividad, horas, procedencia, idIndicadorSolMed, mensaError, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AddBonoAsync(ByVal idUsuario As Integer, ByVal idMaquina As Integer, ByVal fecha As Date, ByVal estadoBono As Integer, ByVal producto As String, ByVal proyecto As String, ByVal estadoProy As String, ByVal idActividad As Integer, ByVal horas As Decimal, ByVal procedencia As String, ByVal idIndicadorSolMed As Integer, ByVal mensaError As String, ByVal userState As Object)
            If (Me.AddBonoOperationCompleted Is Nothing) Then
                Me.AddBonoOperationCompleted = AddressOf Me.OnAddBonoOperationCompleted
            End If
            Me.InvokeAsync("AddBono", New Object() {idUsuario, idMaquina, fecha, estadoBono, producto, proyecto, estadoProy, idActividad, horas, procedencia, idIndicadorSolMed, mensaError}, Me.AddBonoOperationCompleted, userState)
        End Sub
        
        Private Sub OnAddBonoOperationCompleted(ByVal arg As Object)
            If (Not (Me.AddBonoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent AddBonoCompleted(Me, New AddBonoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteLineaBono", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function DeleteLineaBono(ByVal idIndicadorSolMed As Integer, ByVal idActividad As Integer, ByRef mensaError As String) As Boolean
            Dim results() As Object = Me.Invoke("DeleteLineaBono", New Object() {idIndicadorSolMed, idActividad, mensaError})
            mensaError = CType(results(1),String)
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub DeleteLineaBonoAsync(ByVal idIndicadorSolMed As Integer, ByVal idActividad As Integer, ByVal mensaError As String)
            Me.DeleteLineaBonoAsync(idIndicadorSolMed, idActividad, mensaError, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DeleteLineaBonoAsync(ByVal idIndicadorSolMed As Integer, ByVal idActividad As Integer, ByVal mensaError As String, ByVal userState As Object)
            If (Me.DeleteLineaBonoOperationCompleted Is Nothing) Then
                Me.DeleteLineaBonoOperationCompleted = AddressOf Me.OnDeleteLineaBonoOperationCompleted
            End If
            Me.InvokeAsync("DeleteLineaBono", New Object() {idIndicadorSolMed, idActividad, mensaError}, Me.DeleteLineaBonoOperationCompleted, userState)
        End Sub
        
        Private Sub OnDeleteLineaBonoOperationCompleted(ByVal arg As Object)
            If (Not (Me.DeleteLineaBonoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DeleteLineaBonoCompleted(Me, New DeleteLineaBonoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMaquina", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetMaquina(ByVal id As Integer) As String()
            Dim results() As Object = Me.Invoke("GetMaquina", New Object() {id})
            Return CType(results(0),String())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetMaquinaAsync(ByVal id As Integer)
            Me.GetMaquinaAsync(id, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetMaquinaAsync(ByVal id As Integer, ByVal userState As Object)
            If (Me.GetMaquinaOperationCompleted Is Nothing) Then
                Me.GetMaquinaOperationCompleted = AddressOf Me.OnGetMaquinaOperationCompleted
            End If
            Me.InvokeAsync("GetMaquina", New Object() {id}, Me.GetMaquinaOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetMaquinaOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetMaquinaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetMaquinaCompleted(Me, New GetMaquinaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMaquinas", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetMaquinas(ByVal idPlanta As Integer, ByVal idTipo As Integer) As <System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString"), System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel:=1)> String()()
            Dim results() As Object = Me.Invoke("GetMaquinas", New Object() {idPlanta, idTipo})
            Return CType(results(0),String()())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetMaquinasAsync(ByVal idPlanta As Integer, ByVal idTipo As Integer)
            Me.GetMaquinasAsync(idPlanta, idTipo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetMaquinasAsync(ByVal idPlanta As Integer, ByVal idTipo As Integer, ByVal userState As Object)
            If (Me.GetMaquinasOperationCompleted Is Nothing) Then
                Me.GetMaquinasOperationCompleted = AddressOf Me.OnGetMaquinasOperationCompleted
            End If
            Me.InvokeAsync("GetMaquinas", New Object() {idPlanta, idTipo}, Me.GetMaquinasOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetMaquinasOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetMaquinasCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetMaquinasCompleted(Me, New GetMaquinasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddMaquina", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AddMaquina(ByVal nombre As String, ByVal idPlanta As Integer, ByVal idTipoMaq As Integer) As Integer
            Dim results() As Object = Me.Invoke("AddMaquina", New Object() {nombre, idPlanta, idTipoMaq})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub AddMaquinaAsync(ByVal nombre As String, ByVal idPlanta As Integer, ByVal idTipoMaq As Integer)
            Me.AddMaquinaAsync(nombre, idPlanta, idTipoMaq, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AddMaquinaAsync(ByVal nombre As String, ByVal idPlanta As Integer, ByVal idTipoMaq As Integer, ByVal userState As Object)
            If (Me.AddMaquinaOperationCompleted Is Nothing) Then
                Me.AddMaquinaOperationCompleted = AddressOf Me.OnAddMaquinaOperationCompleted
            End If
            Me.InvokeAsync("AddMaquina", New Object() {nombre, idPlanta, idTipoMaq}, Me.AddMaquinaOperationCompleted, userState)
        End Sub
        
        Private Sub OnAddMaquinaOperationCompleted(ByVal arg As Object)
            If (Not (Me.AddMaquinaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent AddMaquinaCompleted(Me, New AddMaquinaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteMaquina", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub DeleteMaquina(ByVal idMaq As Integer)
            Me.Invoke("DeleteMaquina", New Object() {idMaq})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DeleteMaquinaAsync(ByVal idMaq As Integer)
            Me.DeleteMaquinaAsync(idMaq, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DeleteMaquinaAsync(ByVal idMaq As Integer, ByVal userState As Object)
            If (Me.DeleteMaquinaOperationCompleted Is Nothing) Then
                Me.DeleteMaquinaOperationCompleted = AddressOf Me.OnDeleteMaquinaOperationCompleted
            End If
            Me.InvokeAsync("DeleteMaquina", New Object() {idMaq}, Me.DeleteMaquinaOperationCompleted, userState)
        End Sub
        
        Private Sub OnDeleteMaquinaOperationCompleted(ByVal arg As Object)
            If (Not (Me.DeleteMaquinaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DeleteMaquinaCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTipoMaquina", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetTipoMaquina(ByVal id As Integer) As String()
            Dim results() As Object = Me.Invoke("GetTipoMaquina", New Object() {id})
            Return CType(results(0),String())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetTipoMaquinaAsync(ByVal id As Integer)
            Me.GetTipoMaquinaAsync(id, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetTipoMaquinaAsync(ByVal id As Integer, ByVal userState As Object)
            If (Me.GetTipoMaquinaOperationCompleted Is Nothing) Then
                Me.GetTipoMaquinaOperationCompleted = AddressOf Me.OnGetTipoMaquinaOperationCompleted
            End If
            Me.InvokeAsync("GetTipoMaquina", New Object() {id}, Me.GetTipoMaquinaOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetTipoMaquinaOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetTipoMaquinaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetTipoMaquinaCompleted(Me, New GetTipoMaquinaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTiposMaquinas", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetTiposMaquinas(ByVal idPlanta As Integer, ByVal idTipo As Integer) As <System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString"), System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel:=1)> String()()
            Dim results() As Object = Me.Invoke("GetTiposMaquinas", New Object() {idPlanta, idTipo})
            Return CType(results(0),String()())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetTiposMaquinasAsync(ByVal idPlanta As Integer, ByVal idTipo As Integer)
            Me.GetTiposMaquinasAsync(idPlanta, idTipo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetTiposMaquinasAsync(ByVal idPlanta As Integer, ByVal idTipo As Integer, ByVal userState As Object)
            If (Me.GetTiposMaquinasOperationCompleted Is Nothing) Then
                Me.GetTiposMaquinasOperationCompleted = AddressOf Me.OnGetTiposMaquinasOperationCompleted
            End If
            Me.InvokeAsync("GetTiposMaquinas", New Object() {idPlanta, idTipo}, Me.GetTiposMaquinasOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetTiposMaquinasOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetTiposMaquinasCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetTiposMaquinasCompleted(Me, New GetTiposMaquinasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetProjectPlantToCharges", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetProjectPlantToCharges(ByVal idProj As String) As String
            Dim results() As Object = Me.Invoke("GetProjectPlantToCharges", New Object() {idProj})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetProjectPlantToChargesAsync(ByVal idProj As String)
            Me.GetProjectPlantToChargesAsync(idProj, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetProjectPlantToChargesAsync(ByVal idProj As String, ByVal userState As Object)
            If (Me.GetProjectPlantToChargesOperationCompleted Is Nothing) Then
                Me.GetProjectPlantToChargesOperationCompleted = AddressOf Me.OnGetProjectPlantToChargesOperationCompleted
            End If
            Me.InvokeAsync("GetProjectPlantToCharges", New Object() {idProj}, Me.GetProjectPlantToChargesOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetProjectPlantToChargesOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetProjectPlantToChargesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetProjectPlantToChargesCompleted(Me, New GetProjectPlantToChargesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetGrupoDistribucion", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetGrupoDistribucion(ByVal idGrupo As Integer) As String
            Dim results() As Object = Me.Invoke("GetGrupoDistribucion", New Object() {idGrupo})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetGrupoDistribucionAsync(ByVal idGrupo As Integer)
            Me.GetGrupoDistribucionAsync(idGrupo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetGrupoDistribucionAsync(ByVal idGrupo As Integer, ByVal userState As Object)
            If (Me.GetGrupoDistribucionOperationCompleted Is Nothing) Then
                Me.GetGrupoDistribucionOperationCompleted = AddressOf Me.OnGetGrupoDistribucionOperationCompleted
            End If
            Me.InvokeAsync("GetGrupoDistribucion", New Object() {idGrupo}, Me.GetGrupoDistribucionOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetGrupoDistribucionOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetGrupoDistribucionCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetGrupoDistribucionCompleted(Me, New GetGrupoDistribucionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetGruposDistribucion", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetGruposDistribucion(ByVal idPlanta As Integer) As String
            Dim results() As Object = Me.Invoke("GetGruposDistribucion", New Object() {idPlanta})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetGruposDistribucionAsync(ByVal idPlanta As Integer)
            Me.GetGruposDistribucionAsync(idPlanta, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetGruposDistribucionAsync(ByVal idPlanta As Integer, ByVal userState As Object)
            If (Me.GetGruposDistribucionOperationCompleted Is Nothing) Then
                Me.GetGruposDistribucionOperationCompleted = AddressOf Me.OnGetGruposDistribucionOperationCompleted
            End If
            Me.InvokeAsync("GetGruposDistribucion", New Object() {idPlanta}, Me.GetGruposDistribucionOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetGruposDistribucionOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetGruposDistribucionCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetGruposDistribucionCompleted(Me, New GetGruposDistribucionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDatosDistribucion", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetDatosDistribucion(ByVal idProj As String, ByVal tipoDistribucion As Integer, ByVal idGrupoDistrib As Integer, ByVal idCurrencyDestino As Integer) As String
            Dim results() As Object = Me.Invoke("GetDatosDistribucion", New Object() {idProj, tipoDistribucion, idGrupoDistrib, idCurrencyDestino})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetDatosDistribucionAsync(ByVal idProj As String, ByVal tipoDistribucion As Integer, ByVal idGrupoDistrib As Integer, ByVal idCurrencyDestino As Integer)
            Me.GetDatosDistribucionAsync(idProj, tipoDistribucion, idGrupoDistrib, idCurrencyDestino, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetDatosDistribucionAsync(ByVal idProj As String, ByVal tipoDistribucion As Integer, ByVal idGrupoDistrib As Integer, ByVal idCurrencyDestino As Integer, ByVal userState As Object)
            If (Me.GetDatosDistribucionOperationCompleted Is Nothing) Then
                Me.GetDatosDistribucionOperationCompleted = AddressOf Me.OnGetDatosDistribucionOperationCompleted
            End If
            Me.InvokeAsync("GetDatosDistribucion", New Object() {idProj, tipoDistribucion, idGrupoDistrib, idCurrencyDestino}, Me.GetDatosDistribucionOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetDatosDistribucionOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetDatosDistribucionCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetDatosDistribucionCompleted(Me, New GetDatosDistribucionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAnyosDistribucion", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetAnyosDistribucion(ByVal idProj As String, ByVal states() As String, ByVal tipoDistribucion As Integer) As String
            Dim results() As Object = Me.Invoke("GetAnyosDistribucion", New Object() {idProj, states, tipoDistribucion})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetAnyosDistribucionAsync(ByVal idProj As String, ByVal states() As String, ByVal tipoDistribucion As Integer)
            Me.GetAnyosDistribucionAsync(idProj, states, tipoDistribucion, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetAnyosDistribucionAsync(ByVal idProj As String, ByVal states() As String, ByVal tipoDistribucion As Integer, ByVal userState As Object)
            If (Me.GetAnyosDistribucionOperationCompleted Is Nothing) Then
                Me.GetAnyosDistribucionOperationCompleted = AddressOf Me.OnGetAnyosDistribucionOperationCompleted
            End If
            Me.InvokeAsync("GetAnyosDistribucion", New Object() {idProj, states, tipoDistribucion}, Me.GetAnyosDistribucionOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetAnyosDistribucionOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetAnyosDistribucionCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetAnyosDistribucionCompleted(Me, New GetAnyosDistribucionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDatosDistribucionPorAnyos", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetDatosDistribucionPorAnyos(ByVal idProj As String, ByVal tipoDistribucion As Integer, ByVal idGrupoDistrib As Integer, ByVal idCurrencyDestino As Integer) As String
            Dim results() As Object = Me.Invoke("GetDatosDistribucionPorAnyos", New Object() {idProj, tipoDistribucion, idGrupoDistrib, idCurrencyDestino})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetDatosDistribucionPorAnyosAsync(ByVal idProj As String, ByVal tipoDistribucion As Integer, ByVal idGrupoDistrib As Integer, ByVal idCurrencyDestino As Integer)
            Me.GetDatosDistribucionPorAnyosAsync(idProj, tipoDistribucion, idGrupoDistrib, idCurrencyDestino, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetDatosDistribucionPorAnyosAsync(ByVal idProj As String, ByVal tipoDistribucion As Integer, ByVal idGrupoDistrib As Integer, ByVal idCurrencyDestino As Integer, ByVal userState As Object)
            If (Me.GetDatosDistribucionPorAnyosOperationCompleted Is Nothing) Then
                Me.GetDatosDistribucionPorAnyosOperationCompleted = AddressOf Me.OnGetDatosDistribucionPorAnyosOperationCompleted
            End If
            Me.InvokeAsync("GetDatosDistribucionPorAnyos", New Object() {idProj, tipoDistribucion, idGrupoDistrib, idCurrencyDestino}, Me.GetDatosDistribucionPorAnyosOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetDatosDistribucionPorAnyosOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetDatosDistribucionPorAnyosCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetDatosDistribucionPorAnyosCompleted(Me, New GetDatosDistribucionPorAnyosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetHorasBonoGrupo", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetHorasBonoGrupo(ByVal idPlantaSab As Integer, ByVal idProject As String, ByVal state As String, ByVal idGrupoBono As Integer) As String
            Dim results() As Object = Me.Invoke("GetHorasBonoGrupo", New Object() {idPlantaSab, idProject, state, idGrupoBono})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetHorasBonoGrupoAsync(ByVal idPlantaSab As Integer, ByVal idProject As String, ByVal state As String, ByVal idGrupoBono As Integer)
            Me.GetHorasBonoGrupoAsync(idPlantaSab, idProject, state, idGrupoBono, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetHorasBonoGrupoAsync(ByVal idPlantaSab As Integer, ByVal idProject As String, ByVal state As String, ByVal idGrupoBono As Integer, ByVal userState As Object)
            If (Me.GetHorasBonoGrupoOperationCompleted Is Nothing) Then
                Me.GetHorasBonoGrupoOperationCompleted = AddressOf Me.OnGetHorasBonoGrupoOperationCompleted
            End If
            Me.InvokeAsync("GetHorasBonoGrupo", New Object() {idPlantaSab, idProject, state, idGrupoBono}, Me.GetHorasBonoGrupoOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetHorasBonoGrupoOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetHorasBonoGrupoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetHorasBonoGrupoCompleted(Me, New GetHorasBonoGrupoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetProjectMembersByRol", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetProjectMembersByRol(ByVal idProject As String, ByVal rolName As String) As String
            Dim results() As Object = Me.Invoke("GetProjectMembersByRol", New Object() {idProject, rolName})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetProjectMembersByRolAsync(ByVal idProject As String, ByVal rolName As String)
            Me.GetProjectMembersByRolAsync(idProject, rolName, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetProjectMembersByRolAsync(ByVal idProject As String, ByVal rolName As String, ByVal userState As Object)
            If (Me.GetProjectMembersByRolOperationCompleted Is Nothing) Then
                Me.GetProjectMembersByRolOperationCompleted = AddressOf Me.OnGetProjectMembersByRolOperationCompleted
            End If
            Me.InvokeAsync("GetProjectMembersByRol", New Object() {idProject, rolName}, Me.GetProjectMembersByRolOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetProjectMembersByRolOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetProjectMembersByRolCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetProjectMembersByRolCompleted(Me, New GetProjectMembersByRolCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetOwner", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetOwner(ByVal idProject As String) As String
            Dim results() As Object = Me.Invoke("GetOwner", New Object() {idProject})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetOwnerAsync(ByVal idProject As String)
            Me.GetOwnerAsync(idProject, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetOwnerAsync(ByVal idProject As String, ByVal userState As Object)
            If (Me.GetOwnerOperationCompleted Is Nothing) Then
                Me.GetOwnerOperationCompleted = AddressOf Me.OnGetOwnerOperationCompleted
            End If
            Me.InvokeAsync("GetOwner", New Object() {idProject}, Me.GetOwnerOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetOwnerOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetOwnerCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetOwnerCompleted(Me, New GetOwnerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetProjectInfo", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetProjectInfo(ByVal idProj As String) As String
            Dim results() As Object = Me.Invoke("GetProjectInfo", New Object() {idProj})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetProjectInfoAsync(ByVal idProj As String)
            Me.GetProjectInfoAsync(idProj, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetProjectInfoAsync(ByVal idProj As String, ByVal userState As Object)
            If (Me.GetProjectInfoOperationCompleted Is Nothing) Then
                Me.GetProjectInfoOperationCompleted = AddressOf Me.OnGetProjectInfoOperationCompleted
            End If
            Me.InvokeAsync("GetProjectInfo", New Object() {idProj}, Me.GetProjectInfoOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetProjectInfoOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetProjectInfoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetProjectInfoCompleted(Me, New GetProjectInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IsProjectInManagementPlant", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function IsProjectInManagementPlant(ByVal idProject As String, ByVal anno As Integer) As Integer
            Dim results() As Object = Me.Invoke("IsProjectInManagementPlant", New Object() {idProject, anno})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub IsProjectInManagementPlantAsync(ByVal idProject As String, ByVal anno As Integer)
            Me.IsProjectInManagementPlantAsync(idProject, anno, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub IsProjectInManagementPlantAsync(ByVal idProject As String, ByVal anno As Integer, ByVal userState As Object)
            If (Me.IsProjectInManagementPlantOperationCompleted Is Nothing) Then
                Me.IsProjectInManagementPlantOperationCompleted = AddressOf Me.OnIsProjectInManagementPlantOperationCompleted
            End If
            Me.InvokeAsync("IsProjectInManagementPlant", New Object() {idProject, anno}, Me.IsProjectInManagementPlantOperationCompleted, userState)
        End Sub
        
        Private Sub OnIsProjectInManagementPlantOperationCompleted(ByVal arg As Object)
            If (Not (Me.IsProjectInManagementPlantCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent IsProjectInManagementPlantCompleted(Me, New IsProjectInManagementPlantCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetProjectsAffected", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetProjectsAffected(ByVal idProj As String) As String
            Dim results() As Object = Me.Invoke("GetProjectsAffected", New Object() {idProj})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetProjectsAffectedAsync(ByVal idProj As String)
            Me.GetProjectsAffectedAsync(idProj, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetProjectsAffectedAsync(ByVal idProj As String, ByVal userState As Object)
            If (Me.GetProjectsAffectedOperationCompleted Is Nothing) Then
                Me.GetProjectsAffectedOperationCompleted = AddressOf Me.OnGetProjectsAffectedOperationCompleted
            End If
            Me.InvokeAsync("GetProjectsAffected", New Object() {idProj}, Me.GetProjectsAffectedOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetProjectsAffectedOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetProjectsAffectedCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetProjectsAffectedCompleted(Me, New GetProjectsAffectedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateProjectCostCarrier", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function UpdateProjectCostCarrier(ByVal idProject As String, ByVal costCarrier As String) As Integer
            Dim results() As Object = Me.Invoke("UpdateProjectCostCarrier", New Object() {idProject, costCarrier})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub UpdateProjectCostCarrierAsync(ByVal idProject As String, ByVal costCarrier As String)
            Me.UpdateProjectCostCarrierAsync(idProject, costCarrier, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateProjectCostCarrierAsync(ByVal idProject As String, ByVal costCarrier As String, ByVal userState As Object)
            If (Me.UpdateProjectCostCarrierOperationCompleted Is Nothing) Then
                Me.UpdateProjectCostCarrierOperationCompleted = AddressOf Me.OnUpdateProjectCostCarrierOperationCompleted
            End If
            Me.InvokeAsync("UpdateProjectCostCarrier", New Object() {idProject, costCarrier}, Me.UpdateProjectCostCarrierOperationCompleted, userState)
        End Sub
        
        Private Sub OnUpdateProjectCostCarrierOperationCompleted(ByVal arg As Object)
            If (Not (Me.UpdateProjectCostCarrierCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent UpdateProjectCostCarrierCompleted(Me, New UpdateProjectCostCarrierCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Test", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub Test()
            Me.Invoke("Test", New Object(-1) {})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TestAsync()
            Me.TestAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TestAsync(ByVal userState As Object)
            If (Me.TestOperationCompleted Is Nothing) Then
                Me.TestOperationCompleted = AddressOf Me.OnTestOperationCompleted
            End If
            Me.InvokeAsync("Test", New Object(-1) {}, Me.TestOperationCompleted, userState)
        End Sub
        
        Private Sub OnTestOperationCompleted(ByVal arg As Object)
            If (Not (Me.TestCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TestCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub AddBonoCompletedEventHandler(ByVal sender As Object, ByVal e As AddBonoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class AddBonoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property mensaError() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub DeleteLineaBonoCompletedEventHandler(ByVal sender As Object, ByVal e As DeleteLineaBonoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DeleteLineaBonoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property mensaError() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub GetMaquinaCompletedEventHandler(ByVal sender As Object, ByVal e As GetMaquinaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetMaquinaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub GetMaquinasCompletedEventHandler(ByVal sender As Object, ByVal e As GetMaquinasCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetMaquinasCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String()()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String()())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub AddMaquinaCompletedEventHandler(ByVal sender As Object, ByVal e As AddMaquinaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class AddMaquinaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub DeleteMaquinaCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub GetTipoMaquinaCompletedEventHandler(ByVal sender As Object, ByVal e As GetTipoMaquinaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetTipoMaquinaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub GetTiposMaquinasCompletedEventHandler(ByVal sender As Object, ByVal e As GetTiposMaquinasCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetTiposMaquinasCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String()()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String()())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub GetProjectPlantToChargesCompletedEventHandler(ByVal sender As Object, ByVal e As GetProjectPlantToChargesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetProjectPlantToChargesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub GetGrupoDistribucionCompletedEventHandler(ByVal sender As Object, ByVal e As GetGrupoDistribucionCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetGrupoDistribucionCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub GetGruposDistribucionCompletedEventHandler(ByVal sender As Object, ByVal e As GetGruposDistribucionCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetGruposDistribucionCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub GetDatosDistribucionCompletedEventHandler(ByVal sender As Object, ByVal e As GetDatosDistribucionCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetDatosDistribucionCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub GetAnyosDistribucionCompletedEventHandler(ByVal sender As Object, ByVal e As GetAnyosDistribucionCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetAnyosDistribucionCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub GetDatosDistribucionPorAnyosCompletedEventHandler(ByVal sender As Object, ByVal e As GetDatosDistribucionPorAnyosCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetDatosDistribucionPorAnyosCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub GetHorasBonoGrupoCompletedEventHandler(ByVal sender As Object, ByVal e As GetHorasBonoGrupoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetHorasBonoGrupoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub GetProjectMembersByRolCompletedEventHandler(ByVal sender As Object, ByVal e As GetProjectMembersByRolCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetProjectMembersByRolCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub GetOwnerCompletedEventHandler(ByVal sender As Object, ByVal e As GetOwnerCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetOwnerCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub GetProjectInfoCompletedEventHandler(ByVal sender As Object, ByVal e As GetProjectInfoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetProjectInfoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub IsProjectInManagementPlantCompletedEventHandler(ByVal sender As Object, ByVal e As IsProjectInManagementPlantCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class IsProjectInManagementPlantCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub GetProjectsAffectedCompletedEventHandler(ByVal sender As Object, ByVal e As GetProjectsAffectedCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetProjectsAffectedCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub UpdateProjectCostCarrierCompletedEventHandler(ByVal sender As Object, ByVal e As UpdateProjectCostCarrierCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class UpdateProjectCostCarrierCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub TestCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
End Namespace
