'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class RepartidorAlveolos

    '''<summary>
    '''tAlveolos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tAlveolos As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As Telefonia.MPTelefoniaAdm
        Get
            Return CType(MyBase.Master, Telefonia.MPTelefoniaAdm)
        End Get
    End Property
End Class
